### ISSUE TITLE
v-show 切换 `auto-resize` 的图表时图表没有自动重绘

### ISSUE THREAD

**Issue by hank2718** [ecomfe/vue-echarts#176]
请问一下，两个tab切换echarts图表，tab切到第二个图表会显示不全，100%宽度会变成100px，用v-if问题可以解决，但用v-show就不行，有什么好的解决方式？

**Comment by Justineo** [comment]
你用的什么版本？有没有使用 `auto-resize`？

**Comment by hank2718** [comment]
v3.0.1   echarts是4.0    有用auto-resize

**Comment by Justineo** [comment]
能否在 [CodeSandbox](https://codesandbox.io/s/vue) 上给一个可以复现的代码呢？

**Comment by ZiQiangWang** [comment]
遇到了相同的问题

**Comment by liwenda122** [comment]
这是echarts的bug

**Comment by ldwqh0** [comment]
这个问题基本是MVVM下canvas的一个通病，最好的办法就是用v-if

**Comment by ZiQiangWang** [comment]
使用v-if还是出现auto-resize不可用的情况

**Comment by Justineo** [comment]
@ZiQiangWang 请给出可重现的步骤，谢谢。

**Comment by Justineo** [comment]
@Sinosaurus 新版本的在 `v-show` 时应该是可以正常 resize 的，欢迎提供无法正常工作的场景的重现步骤。
