### ISSUE TITLE
vue-echarts升级后 build 报错

### ISSUE THREAD

**Issue by yugasun** [ecomfe/vue-echarts#178]
```
vue-echarts: 3.0.1
```

虽然这个问题有issue提到过，但是，这次的错误是应为依赖 `resize-detector` 的问题，先贴出错误：
```
ERROR in static/js/vendor.1d64d0208a5d4aefcbc4.js from UglifyJs
Unexpected token: name (raf) [./node_modules/resize-detector/esm/index.js:1,0][static/js/vendor.1d64d0208a5d4aefcbc4.js:15310,4]
```

我是使用 `vue-cli` 构建的项目，并通过 `import ECharts from 'vue-echarts/components/ECharts.vue'` 引入组件。

通过阅读源码发现，`./node_modules/resize-detector/esm/index.js` 中包含 `es6` 语法，babel并未对其进行编译成 `es5` 语法，所以才有此错误。

因此需要修改 `webpack` 有关 `babel-loader` 的配置，对其进行编译，修改如下：

```
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/vue-echarts'), resolve('node_modules/resize-detector')]
},
```

@Justineo 希望能在 readme中特别说明下。

**Comment by Justineo** [comment]
已经更新 README。

**Comment by yugasun** [comment]
@Justineo 666， 真效率~

**Comment by ChangeZhang** [comment]
@yugasun 为什么我这么改了之后还是报那个错呢

**Comment by eacan** [comment]
我的也是，改不改都那样

**Comment by wuweihust** [comment]
按照上述修改完webpack打包还是会报错，完全引用后打包正常
import ECharts from 'vue-echarts'
应该还是其他的依赖包是采用ES6或以上编写造成的

**Comment by Justineo** [comment]
统计一下，是不是遇到错误的用的都是 cnpm？

**Comment by wuweihust** [comment]
确实用的是cnpm

**Comment by Justineo** [comment]
https://github.com/ecomfe/vue-echarts/issues/242#issuecomment-392468591

**Comment by wuweihust** [comment]
感谢，原来是这个问题，摸索了两天了~~赞

**Comment by AILINGANGEL** [comment]
赞，又学了一点。

**Comment by ilexwg** [comment]
我也遇到了同样的问题, 我按照官网修改了 `babel-loader` 中的配置:
```
{
  test: /\.js$/,
  loader: 'babel-loader',
  include: [
    resolve('src'),
    resolve('test'),
    resolve('node_modules/vue-echarts'),
    resolve('node_modules/resize-detector')
  ]
},
```
重新执行 `npm run build` 还是报同样的错误,

然后, 我将 `node_modules` 目录删除, 重新用 `npm install` 安装了所有的依赖(之前是用 `cnpm install` 安装的), 接着再执行 `npm run build` 就可以啦! 

希望能给遇到同样报错的朋友一点点借鉴
