### ISSUE TITLE
用dataset无效

### ISSUE THREAD

**Issue by OneWafer** [ecomfe/vue-echarts#179]
用了最新的3.0.1版本，用数据集dataset的方式传数据图表显示不出来

**Comment by Justineo** [comment]
Vue-ECharts 是不感知 `options` 内容所有都是直接丢给 ECharts 处理的。应该是你别的什么地方配置有误？

**Comment by OneWafer** [comment]
我也挺奇怪的，用之前的方法写`options`内容就能正常显示，改成dataset方式就显示不出来了

**Comment by Justineo** [comment]
你可以先确认一下直接使用 ECharts 时能否生效。

**Comment by pissang** [comment]
有没有可能打包的还是老版本的 echarts？

**Comment by OneWafer** [comment]
知道为什么了，我`opitons`数据是参照echarts官网给的示例，里面没有设置颜色。我加上了一句`import 'echarts/theme/dark'`就显示出来了

**Comment by Justineo** [comment]
OK，那么就关闭了。
