### ISSUE TITLE
报错：util.js?8c8f:694 Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by allinshang** [ecomfe/vue-echarts#180]
![image](https://user-images.githubusercontent.com/914579/35664741-45ab1e1a-075e-11e8-97bf-8c8280bf3c84.png)

1.安装：npm install vue-echarts
2.按照提示修改了：
webpack.base.conf.js
![image](https://user-images.githubusercontent.com/914579/35664820-8a8f7fd0-075e-11e8-976f-b1d930e55ac1.png)
3. VueEchartsLine.vue文件：

4.报错util.js?8c8f:694 Uncaught ReferenceError: exports is not defined
求解。

**Comment by Justineo** [comment]
你代码里面是怎么引入和使用的？

**Comment by allinshang** [comment]
<template>
  <chart :options="polar"></chart>
</template>
<script>
import ECharts from 'vue-echarts/components/ECharts.vue'
import 'echarts/lib/chart/line'
export default {
  components: {
    chart: ECharts
  },
  data: function () {
    let data = []
    for (let i = 0; i <= 360; i++) {
      let t = i / 180 * Math.PI
      let r = Math.sin(2 * t) * Math.cos(2 * t)
      data.push([r, i])
    }
    return {
      polar: {
        title: {
          text: '极坐标双数值轴'
        },
        legend: {
          data: ['line']
        },
        polar: {
          center: ['50%', '54%']
        },
        tooltip: {
          trigger: 'axis',
          axisPointer: {
            type: 'cross'
          }
        },
        angleAxis: {
          type: 'value',
          startAngle: 0
        },
        radiusAxis: {
          min: 0
        },
        series: [
          {
            coordinateSystem: 'polar',
            name: 'line',
            type: 'line',
            showSymbol: false,
            data: data
          }
        ],
        animationDuration: 2000
      }
    }
  }
}
</script>
这么写的文件。

**Comment by Justineo** [comment]
````md
```vue
<template>
...
</template>
...
```
````

Markdown 是这么写的。

**Comment by Justineo** [comment]
你还是贴源码吧，不要截图。

**Comment by Justineo** [comment]
我本地还没复现你的问题，但是你少写了一句：

```js
import 'echarts/lib/component/polar'
```

**Comment by allinshang** [comment]
@Justineo 加了也不行呢。。。还是报一样的错误。

**Comment by Justineo** [comment]
初始化项目是 `vue init webpack`？

**Comment by allinshang** [comment]
恩，是的。

**Comment by Justineo** [comment]
```shell
$ vue init webpack test
$ cd test
$ npm i vue-echarts
$ npm run dev
```

无法复现你说的问题……

**Comment by allinshang** [comment]
恩。我自己刚才按照上边步骤新建了，也没有问题。
我观察了下，原来的vue init是12月份创建的。npm i vue-echarts，后原来的项目有个node_modules这个目录，今天新建的没有这个文件价。不知道跟这个有没有关系呢？
![image](https://user-images.githubusercontent.com/914579/35667874-2f51da9e-076a-11e8-9957-710ebe4fa68d.png)

**Comment by Justineo** [comment]
说明你之前的项目本身可能安装了 ECharts，而且和 Vue-ECharts 依赖的 ECharts 版本不同，导致在安装时又在 Vue-ECharts 下安装了别的版本的 ECharts.

**Comment by allinshang** [comment]
@Justineo 恩。卸载了之前项目有关的Echarts组件，再安装npm i vue-echarts就没有这个问题了。多谢。
