### ISSUE TITLE
Component series.bar not exists. Load it first.

### ISSUE THREAD

**Issue by chping2125** [ecomfe/vue-echarts#181]
我今天在使用 webpack externals 拆 echarts 时，webpack 打包正常，访问带有 vue-echarts 的页面报错，图表显示失败，报错信息如下：
```js
Error: Component series.bar not exists. Load it first.
    at Function.entity.getClass (clazz.js?3e66:166)
    at ExtendedClass.eval (Global.js?b9d3:195)
    at Array.forEach (<anonymous>)
    at each (util.js?10f4:272)
    at ExtendedClass.visitComponent (Global.js?b9d3:178)
    at Function.entity.topologicalTravel (component.js?cc72:89)
    at ExtendedClass.mergeOption (Global.js?b9d3:147)
    at ExtendedClass.initBase (Global.js?b9d3:642)
    at ExtendedClass.resetOption (Global.js?b9d3:92)
    at ExtendedClass.setOption (Global.js?b9d3:74)
```

echarts 在 window 上注册成功。
 
webpack 配置、vue-echarts 使用和提供 demo 一致。

看这个报错是不是 echarts 报出来的？

我的理解，使用 webpack externals 功能，将 echarts 包拆分出来，并且全局注册成功的前提下，不应该影响到 vue-echarts 使用。

使用 webapck CommonsChunkPlugin 功能拆分是没有问题的。

**Comment by Justineo** [comment]
说明 `echarts/lib/chart/bar` 没有加载。

**Comment by chping2125** [comment]
我是全量引入的 echarts 呀，应该引入 echarts/lib/chart/bar 了吧

webpack 相关配置
```

resolve: {
    extensions: ['.js', '.vue'],
    modules: [path.join(__dirname, '../node_modules')],
    alias: {
      ECharts: path.resolve(__dirname, '../node_modules/vue-echarts/components/ECharts'),
      Utils: path.resolve(__dirname, '../src/utils/')
    }
  }
...
{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueConfig
      },
      {
        test: /\.js$/,
        loader: 'babel-loader?cacheDirectory',
        exclude: /node_modules/
      },
...

externals: {
   echarts: 'echarts'
}
....

```

## app.js 中引入
```js
import Vue from 'vue';
import 'echarts';
import ECharts from 'ECharts';

...
Vue.component('chart', ECharts);
```

## 使用
```html
  <chart :options="selfOptions"></chart>
```

**Comment by Justineo** [comment]
如果你要引入打包后的全量版本，引入 Vue-ECharts 即可，不要再引入 ECharts 了。（其实所谓「全量」并不全，只是多数常用功能的集合。）

```js
import ECharts from 'vue-echarts'
```

因为 ECharts 已经打包在 Vue-ECharts 里了，你的依赖里面不应该再有单独的 ECharts 了。你把 `vue-echarts` 加到 `externals` 里去应该就行了。

**Comment by chping2125** [comment]
你的意思是，我既然要引入 echarts 的全量版本，我直接引入 /dist/vue-echarts.js 即可，vue-ehacrts 打包后已经提供了全量版本的 echarts 了。

但是，我上面的配置中，引入的是 Echarts.vue 文件，然后自己引入的 echarts ,所以按这个思路想去对 echarts 做 externals ，然后报了这个错。而我引入的这个 echarts 是官方提供的全量版本的 echarts，里面不包含 echarts/lib/chart/bar  吗？


按照你说的方式，我对 vue-echarts 做 externals 后，vue 服务端渲染报错：
```js
ReferenceError: document is not defined
    at /Users/iyx/codes/bossFE/iyunxiao-dashboard/node_modules/vue-echarts/dist/vue-echarts.js:20:18204
    at /Users/iyx/codes/bossFE/iyunxiao-dashboard/node_modules/vue-echarts/dist/vue-echarts.js:20:18472
    at t (/Users/iyx/codes/bossFE/iyunxiao-dashboard/node_modules/vue-echarts/dist/vue-echarts.js:1:146)
    at Object.<anonymous> (/Users/iyx/codes/bossFE/iyunxiao-dashboard/node_modules/vue-echarts/dist/vue-echar
ts.js:1:242)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at r (/Users/iyx/codes/bossFE/iyunxiao-dashboard/node_modules/vue-server-renderer/build.js:7739:16)
    at Object.331 (webpack:/external "vue-echarts":1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 9c5dc06cd804ea749fb7:25:0)
    at Object.9 (server-bundle.js:6919:70)
    at __webpack_require__ (webpack:/webpack/bootstrap 9c5dc06cd804ea749fb7:25:0)

```
看这个报错信息，明显是 vue 服务端渲染过程失败。

**Comment by Justineo** [comment]
你如果用 `vue-echarts/components/ECharts`，那么它会引用 `echarts/lib/echarts`，而非 `echarts`。你自己引入 `echarts` 引入的是 `echarts` 打包好的版本，和 Vue-ECharts 引的不是同一个东西，是没有用的。

**Comment by chping2125** [comment]
恩恩，明白你的意思了。

但是用你的方法全量引入 /dist/vue-echarts.js 后 vue 服务端报错是正常现象吗？

**Comment by Justineo** [comment]
没仔细看，但是我现在是用 Rollup 打包的，注入默认 CSS 样式的时候可能会调用 DOM 接口。

**Comment by chping2125** [comment]
钻牛角尖了，见谅啊，对echarts 的理解可能没有这么深。

我引入的 `import 'echarts'`  是 `echarts` 打包后的版本，我看里面对外抛出的也是 `lib/echarts` 呀：

// /node_modules/echarts/index.js
```js
/**
 * Export echarts as CommonJS module
 */
module.exports = require('./lib/echarts');

// Import all charts and components
require('./lib/chart/line');
require('./lib/chart/bar');
require('./lib/chart/pie');
require('./lib/chart/scatter');
require('./lib/chart/radar');

.....

```

`ECharts.vue` 组件里面按需引入的也是 `lib/echarts` 呀，怎么就不一样了呢？（求不打死）

目前的我理解是：
       1. 我通过 wbpack 的 CommonsChunkPlugin 方式拆分 echarts，vue-echarts 的使用方式为我的第一个配置那样（引入Echarts.vue），服务端打包没有任何问题，而浏览器刷新页面后图表正常渲染，没有任何问题； 

       2. 通过 wbpack 的 externals  方式拆分 echarts，vue-echarts 的使用方式任然为我的第一个配置那样（引入Echarts.vue），服务端打包没有任何问题，而浏览器刷新页面后图表渲染失败，报错信息为`Component series.bar not exists. Load it first.` ； 

      对比 1、2 的结果，结合你的回答，我觉着应该是 `echarts` 提供的打包后的 `echarts.min.js` 和通过 CommonsChunkPlugin 拆分出来的 chunk 有不同之处导致的。

     但是有啥不同呢？目前个人能力分析出来可能还有点难度。

     不过通过  CommonsChunkPlugin 拆分的结果，现在我也是能接受的。


     
      感谢你们的付出，致敬 echarts 团队！

**Comment by Justineo** [comment]
恩，刚看了一下，似乎在 CommonJS/ESM 下，引入 `echarts` 应该不会和 `vue-echarts/components/ECharts` 产生冲突。如果不拆分时不报错的话应该不是这个问题。

**Comment by chping2125** [comment]
这就尴尬了，看来需要深入学习一下 echarts 了。

**Comment by Sapphire2k** [comment]
```
  import ECharts from 'vue-echarts/components/ECharts.vue'
  import 'echarts/lib/chart/bar.js'
```
👆这样引入也报了这个错误

```
  import ECharts from 'vue-echarts'
```
👆全部引入就没这个问题，最新的版本`vue-echarts@3.0.1`

@Justineo

**Comment by Sapphire2k** [comment]
回退旧版本正常

`vue-echarts@2.6.0`
`echarts@3.8.5`

**Comment by Justineo** [comment]
@Sapphire2k 很可能你项目下面装了两个版本的 ECharts。你开一个新项目试试能否复现呢？我这边复现不了。

**Comment by TianYouH** [comment]
"vue-echarts": "^3.0.3",
"echarts": "^4.0.2",
"vue": "^2.5.13",

`
import Chart from 'vue-echarts/components/ECharts.vue'
import 'echarts/lib/chart/bar'
import 'echarts/lib/component/title'
`
这样使用也是报同上错误。全部引用正常
![image](https://user-images.githubusercontent.com/15323122/36660523-603eba52-1b13-11e8-887a-29399e1e5f51.png)

**Comment by jaxQin** [comment]
Component series.pie not exists. Load it first.

我这也报这样的错误。webpack中已经按文档中写的改了
```
{
                test: /\.js$/,
                loader: 'babel-loader',
                // include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client')],
                include: [
                    resolve('src'),
                    resolve('test'),
                    resolve('node_modules/vue-echarts'),
                    resolve('node_modules/resize-detector'),
                ],
            },
```

**Comment by PlutoZX** [comment]
我试了下把ecahrts引进去就不报，这种not exists的错了

**Comment by ApolloRoad** [comment]
@adwerrd  淘宝出的也有chart工具，不会搞事情把

**Comment by yjq8023** [comment]
我有跟 Sapphire2k 一模一样的问题，回退版本后正常

**Comment by Justineo** [comment]
@yjq8023 https://github.com/ecomfe/vue-echarts/issues/181#issuecomment-364657948

**Comment by smecnarowski** [comment]
Problem seems to exists in 4.2.0-rc.2, after downgrade to 4.1.0 problem disappeared.

**Comment by hfc1994** [comment]
@Justineo 你好!
我这边使用vue-echarts引入echarts-wordcloud时，报了下面这个错误
```Component series.wordCloud not exists. Load it first.```

package.json
```
{
	"echarts-wordcloud": "^1.1.3",
	"echarts": "^4.1.0",
	"vue-echarts": "^3.1.3"
}
```

文件引入写法如下
```
import ECharts from 'vue-echarts/components/ECharts';     
import 'echarts-wordcloud';
```

我分析了下，发现echarts-wordcloud使用的是echarts而vue-echarts使用的是它自己包内的node_modules/echarts
那么它俩用的不是同一个东西
之后我把项目里的echarts@4.1.0给卸载了，只剩下vue-echarts@3.1.3和echarts-wordcloud@1.1.3
```
import ECharts from 'vue-echarts';    
import 'echarts-wordcloud';
```
但是再一次运行的话就直接是报编译不通过，找不到wordcloud依赖的echarts了
然后我打开wordcloud.js看到第一行就是```var echarts = require('echarts/lib/echarts');```
那么wordcloud还是要依赖到echarts的

最后我尝试吧echarts-wordcloud/src下面的4个文件复制到vue-echarts/node_modules/lib/chart里面，然后再运行项目，词云就能正常显示了。

以上是我的一些尝试，然后我想请教下作者：我看你在echarts-wordcloud项目的issues里面表示vue-echarts和echarts-wordcloud是可以结合使用的，那么要怎么引用才行？是想办法使vue-echarts不去引用它node_modelus里面的echarts嘛？

**Comment by Justineo** [comment]
用 `vue-echarts/components/ECharts` 试试（记得配转译）。

**Comment by hfc1994** [comment]
问题解决了，但是解决的过程比较奇怪
首先是我看到 @chping2125 在webpack.base.conf.js里面增加了别名，受到这个思路的启发，我在这个文件中增加了一个别名。
```javascript
resolve: {
    ...
    alias:{
        ...
        'echarts/lib': path.resolve(__dirname, '../node_modules/echarts/lib')
    }
}
```
通过增加上面那个配置，这样的话不管是vue-echarts还是echarts-wordcloud在通过`var echarts = require('echarts/lib/echarts')`来引入echarts时，都只会使用echarts本身了，是同一个，因而也就不会被vue-echarts中的node_modules所影响，然后实际测试也如预期。
为了验证这个方法没毛病，我又重新init了一个vue项目，然后install了vue-echarts，echarts，echarts-wordcloud。我没有直接修改webpack.base.conf.js，准备先复现问题`Component series.wordCloud not exists. Load it first.`这个错误之后再修改。但是我运行之后发现这个错误没出现，而且词云图也正常显示了...
经过检查之后发现刚刚install的vue-echarts下面没有node_modules文件夹了...
我检查了下我周五新建的项目和今天早上9点新建的项目，其vue_echarts下面都有node-modules这个文件夹，唯独刚刚创建的这个没有，然后我换了一台机器再一次创建，结果vue_echarts下面依旧没有node_modules这个文件夹...

出问题时的vue-echarts目录结构：
vue-echarts
---component
---dist
---node_modules
------echarts
------zrender

最新install的vue-echarts目录结构：
vue-echarts
---component
---dist

**Comment by sashangli** [comment]
我也遇到这个问题，然后我注意到vue-echarts@3.1.2版本中依赖的echarts版本是4.1.0，然后我把echarts从4.2.0-rc.2,降到4.1.0，和vue-echarts保持了一致，就解决了

**Comment by Justineo** [comment]
我后面发个大版本吧，把 `echarts` 写到`peerDependencies` 里。

**Comment by pengliheng** [comment]
![image](https://user-images.githubusercontent.com/14355994/49505968-d8837e80-f8b7-11e8-99c1-400abd39b6ce.png)
下载文件的时候没有勾选bar，所以找不到bar啊

**Comment by phouri** [comment]
Please add echarts as peer dependency - super important for using other extensions as well.

**Comment by Justineo** [comment]
@phouri You care right. It's now in `dependencies` which leads to a lot of confusion. I'll move it to `peerDependencies` ASAP and release a new major version.

**Comment by Justineo** [comment]
Oops, closed by mistake.

**Comment by Justineo** [comment]
`4.0.0-beta.1` is now released. Please try out and any feedback will be appreciated.

Check out the latest README file for usage updates. (In short: you have to install `echarts` by yourself now.)

---

Changes since v3:

#### 4.0.0-beta.1

* Fix autoresize.

#### 4.0.0-beta.0

* Move `echarts` into `peerDependencies`. **BREAKING**
* Rename `auto-resize` to `autoresize`. **BREAKING**
* Point `module` entry to the source version. **BREAKING**
* Swith to Vue CLI 3 for demo.

**Comment by 2hz4917** [comment]
Vue CLI 3创建的项目，使用仪表盘时报错
demo地址：https://jsfiddle.net/Toco/c35qsmaL/5/
![image](https://user-images.githubusercontent.com/15519966/51425353-d1b98c80-1c15-11e9-95bc-d2d648126842.png)

**Comment by magicdawn** [comment]
这种问题太多, 主要是 vue-echarts dep 的 echarts 可能与项目使用的 echarts 版本不一样导致的
就是你听了官方的话, 要引入 `echarts` 或者 `echarts/lib/xxx`
使用 cnpm 已经各厂定制的 xnpm 都会使用软链接, 可以看下版本

```
node_modules/echarts
node_modules/vue-echarts/node_modules/echarts
```

这俩版本不一样, 就会出问题.
解决办法:

webpack
```
resolve.alias = {
      // use same version
      // project echarts &
      // vue-echarts dep
      echarts: path.dirname(require.resolve('echarts/package.json')),
    }
```

建议 vue-echarts 将 echarts 改为 peer dependency
并且版本指定为大版本兼容就行... 比如 "^4"
这个仓库的 echarts 版本太新, 各种 rc 版本都上了 ... 

或者, 直接不将 echarts 写在任何 dep 里...
在 README 说明一下就好, 就是这俩必须同时安装就行

**Comment by Justineo** [comment]
@magicdawn 已经是 peer dependency 了。

**Comment by HXY-0227** [comment]
我只是在jsp页面引入了echarts。然后在另一个js文件中用了line组件，报下面这个错，none是什么啊。
Component series.none not exists. Load it first

**Comment by huyansheng3** [comment]
external 模式加上这一行 ，所有地方 ``import VChart from 'vue-echarts/components/ECharts'

```
 config.externals({
      'echarts/lib/echarts': 'echarts',
    })
```

**Comment by wuxiaobin1995** [comment]
![image](https://user-images.githubusercontent.com/36044379/88778543-3bc3d200-d1bb-11ea-8dfd-9f5cac0d5c3e.png)

我的：
![image](https://user-images.githubusercontent.com/36044379/88778640-572edd00-d1bb-11ea-93e6-3014ae85dfe0.png)
