### ISSUE TITLE
全局引入情况下如何引入下载的样式js

### ISSUE THREAD

**Issue by xiaoqi-rimix** [ecomfe/vue-echarts#183]
如题，`main.js`中引入了`import ECharts from 'vue-echarts';`
想要通过引入不同主题来实现切换，在对应的模板中improt 样式js
`<chart :options="Options" auto-resize  :theme="'macarons'"></chart>`无效。。。
求指导~

**Comment by Justineo** [comment]
全局情况下用 JS 模式做不了，因为引入的不是同一个 ECharts 实例，只能用 JSON 数据自行注册。这也是不建议全局引入的原因之一。
