### ISSUE TITLE
pie饼图点击扇形不显示数据，只有效果，已经设置了 trigger

### ISSUE THREAD

**Issue by taishan802** [ecomfe/vue-echarts#184]
pie饼图点击扇形不显示数据，只有效果，已经设置了 trigger
let chartData = {
        tooltip: { // 点击提示name占比和对应value
          trigger: 'item',
          formatter: '{b} : {c} ({d}%)'
        },
        color: ['#b1e0f8', '#63d29d', '#63c9d2', '#6085ff'],
        series: [{
          type: 'pie',
          radius: '80%',
          center: ['50%', '50%'],
          data: [{value: 46, name: '皇太后'}, {value: 54, name: '怀仁堂'}],
          itemStyle: {
            normal: {
              borderWidth: list.length === 1 ? 0 : 3,
              borderColor: '#fff'
            }
          }
        }]
      }

**Comment by Justineo** [comment]
先确认仅用 ECharts 时是否能复现，谢谢。

**Comment by taishan802** [comment]
是自己本地依赖包缓存问题，没清干净
