### ISSUE TITLE
upgrade to echarts 4.0.2

### ISSUE THREAD

**Issue by xeric** [ecomfe/vue-echarts#186]
echarts 4.0.2 fixed some issues such as sunburst chart tooltip supports, could you please upgrade this new version?
https://github.com/ecomfe/echarts/issues/7691

**Comment by Justineo** [comment]
If you import `vue-echarts/components/ECharts` instead of `vue-echarts` you can specify the version of `echarts` as you like. The bundled version may fall behind a little bit.

**Comment by Justineo** [comment]
`+vue-echarts@3.0.2`
