### ISSUE TITLE
echart在某些情况下不会被重新渲染

### ISSUE THREAD

**Issue by ObservedObserver** [ecomfe/vue-echarts#188]
## The type of this issue / Issue 类型

- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
2.6.0

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

```js
<template lang="html">
  <div>
    <chart :options="option" id="riskInTime"/>
  </div>
</template>

<script>
# 引入折线图的配置项
import {initOption as op} from './riskInTime.js'
export default {
  name: 'riskintime',
  data () {
    return {}
  },
  props: {
    data: {
      type: Array,
      default () {
        var len = 6
        var arr = []
        for (let i = 0; i < len; i++) {
          arr.push(parseInt(Math.random() * 100))
        }
        return arr
      }
    }
  },
  computed: {
    option () {
      // 修改x轴信息与数据信息
      op.xAxis.data = this.$store.getters.timeLine
      op.series[0].data = this.$props.data
      // 这里可以看到属性被重新计算，所以我认为，图表也会被重新渲染，但事实上图表并未被重新渲染
      console.log(op.xAxis.data, op.series[0].data)
      return op
    }
  }
}
</script>

<style lang="css">
#riskInTime{
  width: 100%;
  height: 16rem;
}
</style>
```

这种不会重新渲染图标的情况发生在options对应的对象是否是import来的。若是import获取的，则不会被渲染。

**Comment by Justineo** [comment]
你的 `op` 数据本来就不在 Vue 的变化检测范围内，当然不会触发变化了。你需要把引入的数据放到 Vue 实例的 `data` 里。
