### ISSUE TITLE
Laggy Auto-Resize-Down When Displaying Multiple Charts

### ISSUE THREAD

**Issue by febiyan-tba** [ecomfe/vue-echarts#189]
## The type of this issue / Issue 类型
- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。
- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
Hi devs,

I've been trying to use vue-echarts with Vuetify. The integration works fine in general and I think you've been doing a great job with it. However I've been noticing this strange behavior: **when there are more than 1 chart with auto-resize property, when resizing down the browser window, the charts resize really slowly**

It doesn't happen the same way when I resized up the browser window. I'm not quite sure if that's a bug to be honest, it could be my CSS code that caused it. 

But it could be. See the following gif:

![Alt Text](https://media.giphy.com/media/RHKrJCd05cBSSjBc2p/giphy.gif)

Strangely your demo works fine and in my code the resize-up works fine too.

It has been 5 years since the last time I did web development so please bear with me.

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.2

## Reproduction link / 复现链接
https://codesandbox.io/s/pmoxjm272q
https://pmoxjm272q.codesandbox.io/

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by febiyan-tba** [comment]
I agree. This could be an integration problem which may not be applicable for any of the projects. I would love to see some suggestions how I can modify things but feel free to reject or close this issue.

**Comment by febiyan-tba** [comment]
It seems like the `width: 99.9%` css property was the culprit that made things slow. The animation javascript library could not calculate the target width fast enough for it the element to animate smoothly. I changed it so that it looks like this:
`
figure {
  width: 90%;
}

figure .echarts {
  width: 100%;
}
`

If I put figure { width: 100% } somehow the layout would break. However with 90% it seems like the animation can be smoother. However, I'm happy with what I see here https://codesandbox.io/s/m5lw9v878p

It's not vue-echarts issue after all, but this can be a good reference for people hitting the same issues in the future.

**Comment by Justineo** [comment]
Thanks. Maybe I'll look into the true reason for this later.
