### ISSUE TITLE
设置auto-resize之后，响应theme变化会出错

### ISSUE THREAD

**Issue by ScorpioX** [ecomfe/vue-echarts#190]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
ECharts.vue中的destroy方法中的这段代码与在每次修改theme之后会执行
```
if (this.autoResize) {
    removeListener(this.$el, this.__resizeHandler)
}
```
但只有第二次修改之后，才会调用resize-detector中的elem.removeChild(elem.__resize_triggers__.triggers)，而此时__resize_triggers__为null，会报错导致theme切换失败。我试着把这句话注释上，theme切换就没问题了。但根源可能还是在ECharts.vue的处理逻辑里

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

3.0.2 + ECharts 4.0.2

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

https://codesandbox.io/s/n71n64x07p
很简单的例子，按钮Y和Z仅仅是切换ECharts的theme。按Y没问题，再按Z就会在Console看见报错

**Comment by Justineo** [comment]
`3.0.3` 应该已经修复了：https://codesandbox.io/s/5wkmq854lx
