### ISSUE TITLE
Not able to display JSON data in Scatter Chart

### ISSUE THREAD

**Issue by coenhallie** [ecomfe/vue-echarts#192]
Hello,

I am trying to fetch a local JSON file (maybe external later) and to display it in a scatter chart, however I just can't seem to get it working. I do get the data (check console log), however it isn't displaying.

To display the scatters on the right position, I have two parameters I want to use. The object 'Position_x' and 'Position_y'. Other information like 'goal' etc, I will use in the tooltip.

I have created a Codesandbox url:

https://codesandbox.io/s/k2z3v0vx43

I would be super thankful if someone can take a look, I am working on it for several days, but I just can't seem to get it working.

Many thanks!!

,Coen Hallie

## Reproduction link / 复现链接

https://codesandbox.io/s/k2z3v0vx43

**Comment by Justineo** [comment]
I don't think it's an issue related to this project. First you need to import data correctly, I'm not sure if `fetch` will work as expected in CodeSandbox. And it seems that you've forgotten to import modules for scatter plot.

**Comment by coenhallie** [comment]
Hi Justineo,

Thanks for your response( and making it compatible with Vue)  I got it working in the end. I had to use '.self' in the fetching method, and '.this' in the computed propery to target the data due to lexical scope. 

Just finished it, if you want to see how I did it, here is a repo:

https://github.com/coenhallie/Scisports-app

Cheers,

Coen
