### ISSUE TITLE
IE11 上無法顯示 echarts

### ISSUE THREAD

**Issue by vggo** [ecomfe/vue-echarts#195]
在 chrome 顯示 bar, polar 皆正常，但在 IE11 出現錯誤，如下：
  [vue-router] Failed to resolve async component default: SyntaxError: 必須要有 ')'
  [vue-router] uncaught error during route navigation:
  [object Error]{description: "必須要有 ')'", message: "必須要有 ')'", name: "SyntaxError", number: -2146827282, stack: "SyntaxError..."}

版本：
Quasar CLI v0.6.5
 App running on Quasar v0.14.9
vue-echarts@3.0.3
echarts@4.0.4

**Comment by Justineo** [comment]
请按 issue 模板填写，谢谢。不按模板填写的问题将被直接关闭。
