### ISSUE TITLE
Options With Dataset Not Working in Version 3.0.3

### ISSUE THREAD

**Issue by febiyan-tba** [ecomfe/vue-echarts#196]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

Hi, I'm trying to use Dataset property / feature with version 3.0.3 (which I assume uses echarts 4). But whenever I use `dataset` property, it doesn't work like [this documentation](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Dataset) shows. Am I doing this right or the feature isn't supported yet?

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.3

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

Here is the codesandbox link: [https://codesandbox.io/s/5zl7x6v6nx](https://codesandbox.io/s/5zl7x6v6nx)

**Comment by taishan802** [comment]
问下bug模板如何勾选

**Comment by Justineo** [comment]
@taishan802 

```
- [x] 已选项
```

**Comment by febiyan-tba** [comment]
Is there anything more that needs to be clarified?

**Comment by Justineo** [comment]
@febiyan-tba Thanks for reporting. I'm currently investigating this :)

**Comment by Justineo** [comment]
@febiyan-tba 

It turns out that `dataset` is exposed as a component in ECharts 4. You need to load it like this:

```js
import 'echarts/lib/component/dataset'
```

**Comment by 100pah** [comment]
Now that `dataset` is a primary component in echarts,  it has been modified to a built-in component in ecomfe/echarts@632b5140fda033808e50c20d635f993d0bac0c3c, so that no need to import it manually since echarts 4.1.0 (coming soon).
