### ISSUE TITLE
datazoom手势可以在图形区域内放大缩小

### ISSUE THREAD

**Issue by wuyuliyu** [ecomfe/vue-echarts#198]
Vue中使用echarts ，datazoom
在平板电脑中。手势在图形区域内，和页面没有区分
echart官网 案例没问题，手势可以在图形区域内放大缩小，
感觉是图形区域和页面不区分，就是那个datazoom。问题

**Comment by Justineo** [comment]
请按 issue 模板填写，不按模板填写的暂不处理，谢谢了。
