### ISSUE TITLE
加datazoom

### ISSUE THREAD

**Issue by wuyuliyu** [ecomfe/vue-echarts#199]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 

请在https://github.com/ecomfe/vue-echarts/blob/master/demo/Demo.vue。加datazoom.测试一下手势可以在图形区域内放大缩小.

**Comment by Justineo** [comment]
模板原封不动，在里面没有提供任何有意义的内容……

我感觉是你没有引入 `datazoom` 的模块吧。

```js
import 'echarts/lib/component/dataZoom'
```
