### ISSUE TITLE
t.__resize_mutation_observer__.unobserve is not a function

### ISSUE THREAD

**Issue by taishan802** [ecomfe/vue-echarts#200]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身 
Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.3

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

在移动端使用Vux组件库，如下引入vue-echarts ：

```js
import theme from './myLineChart.json'
  const Chart = () => import(/* webpackChunkName: "ECharts" */ 'vue-echarts').then(ECharts => {
    ECharts.registerTheme('lineChart', theme)
    status.isLoaded = true
    return ECharts
  })
  export default {
    components: {
      Cell,
      Group,
      Flexbox,
      FlexboxItem,
      Chart,
      ComponentTable
    }
```

在当前页面没问题，当回退上一个页面是控制台报错：
![image](https://user-images.githubusercontent.com/21050631/37192306-c1ecedfc-239f-11e8-9596-8ff8d9c5c2e2.png)

**Comment by Justineo** [comment]
在 `v3.0.4` 修复了一波，可以看下是否还有问题。

**Comment by taishan802** [comment]
更新后，控制台不再报错了，但同样的操作在sentry上依旧报错：t.__resize_mutation_observer__.unobserve is not a function

**Comment by Justineo** [comment]
你那边 Sentry 上收到的信息能确认来自新版本吗？之前的版本写错了，`MutationObserver` 没有这个方法，新版本应该已经删掉了。

**Comment by taishan802** [comment]
感谢，我再次检查一遍~

**Comment by taishan802** [comment]
更新后，没问题了，再次感谢~
