### ISSUE TITLE
渐变色设置

### ISSUE THREAD

**Issue by OneWafer** [ecomfe/vue-echarts#202]
请问一下图表的渐变色怎么设置，比如echarts官网中有echarts.graphic.LinearGradient()的部分。
我目前的做法是引入了echarts，有没有不要另外引入的方法？

**Comment by Justineo** [comment]
请看 [demo](https://github.com/ecomfe/vue-echarts/blob/88456004445657f45538ae8ddf08e99b3ecd326b/demo/data/scatter.js#L320)。

提交 issue 请勿无视模板内容，并认真填写，否则以后将直接关闭。

**Comment by rebitco** [comment]
现在已经放到util里面了；
`import { LinearGradient } from "echarts/lib/util/graphic.js";`
