### ISSUE TITLE
chrome 66.0.3355.4(64位) 设置动画时长无效.火狐等其它浏览器正常

### ISSUE THREAD

**Issue by meihangbo** [ecomfe/vue-echarts#203]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

** **

# chrome 66.0.3355.4(64位) ,设置动画时长无效.版本64以上也是无效的,火狐等其它浏览器正常
>代码地址: https://github.com/meihangbo/vue-echarts_demo
>可访问地址:https://meihangbo.github.io/vue-echarts_demo/dist/

**Comment by Justineo** [comment]
Fixed in `v3.0.5`.
