### ISSUE TITLE
请问,我把柱状图作为组件后,props传入data,页面调用多个组件,但是后面的值把前面所有图表值覆盖了

### ISSUE THREAD

**Issue by xjccc** [ecomfe/vue-echarts#206]
<chart options="bar" ref="bar"></chart>作为组件props传入data
在home页面调用多个<bar :data="list"></bar>的时候,发现后面传入的list值,把前面的全部覆盖了
应该如何重新实例化Echarts呢?

**Comment by Justineo** [comment]
不按模板填写的 issue 将被直接关闭，谢谢。
