### ISSUE TITLE
import进来的vue-echarts作为组件的时候，如何重新实例化

### ISSUE THREAD

**Issue by xjccc** [ecomfe/vue-echarts#207]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

"vue-echarts": "^3.0.4"

`<chart options="bar" ref="bar"></chart>`
作为组件props传入data
在home页面调用多个`<bar :data="list"></bar>`的时候,发现后面传入的list值,把前面的全部覆盖了
应该如何重新实例化Echarts呢?

**Comment by Justineo** [comment]
这个和 Vue-ECharts 没有关系，请自行保证不要将同一个对象绑定到多个组件实例。同时，请不要随便删除 issue 模板内容并提供可复现的场景。

**Comment by Justineo** [comment]
你提供的复现代码跑不起来呀。

**Comment by xjccc** [comment]
谢谢。。已经解决了。。我之前在组件中引入了js的options文件。所以导致公用一个配置文件
