### ISSUE TITLE
[Bug report]在IE裡面有語法兼容性問題

### ISSUE THREAD

**Issue by zzzgit** [ecomfe/vue-echarts#208]
![image](https://user-images.githubusercontent.com/1060733/37640438-88f71d9c-2c50-11e8-93fa-0fdf55f1546a.png)

`vue-echarts`依賴了`resize-detector`，而`resize-detector`的`package.json`配置了`module`字段

其後果是，在用打包`vue-echarts`時，`rollup`會直接使用`ES6`版本的模塊，而不是使用編譯後的

最終，導致`vue-echarts`沒法在`IE`中使用

**Comment by Justineo** [comment]
请按 issue 模板进行填写，删除模板内容的 issue 将被直接关闭。

打包时会调用 buble 进行转译，应该是可以在 IE 下使用的。
