### ISSUE TITLE
undefined is not an object (evaluating 'this.el.style')

### ISSUE THREAD

**Issue by taishan802** [ecomfe/vue-echarts#209]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.5

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**
当前页面没报错，当回退到上一个页面sentry会报错，如下：

undefined is not an object (evaluating 'this.el.style')
![image](https://user-images.githubusercontent.com/21050631/37698701-f69e1eda-2d1e-11e8-966c-d2c9b0ac305f.png)

该错误是偶现，更新到3.0.5版本后出现了三次

**Comment by Justineo** [comment]
如何确认不是 ECharts 本身的问题的？我看报错的代码在 ECharts 内部。

**Comment by Justineo** [comment]
无法复现，暂时无法定位问题。有可复现的步骤后再来研究吧。
