### ISSUE TITLE
error with jest

### ISSUE THREAD

**Issue by constantank** [ecomfe/vue-echarts#210]
hi, there's a problem i hit when i try to run my test files with Jest,

/home/link/satiVersion2/dataexa-sati-workbench/node_modules/_vue-echarts@3.0.5@vue-echarts/components/ECharts.vue:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){<template>
                                                                                             ^
    
    SyntaxError: Unexpected token <

that's how i import them,
      11 |   import ECharts from 'vue-echarts/components/ECharts.vue'
    > 12 |   import 'echarts/lib/chart/bar'

i don't understand , i think it's transpiled file that i imported, please help me?

**Comment by constantank** [comment]
sorry ,, it's  untranspiled, i change my jest config like this:
transformIgnorePatterns: [
    "<rootDir>/node_modules/(?!vue-echarts|echarts)"
  ],

but i still doesn't work ,

**Comment by Justineo** [comment]
Please follow the issue template. Thanks.
