### ISSUE TITLE
how to know which series is selected in legend?

### ISSUE THREAD

**Issue by t0n1zz** [ecomfe/vue-echarts#212]
hi, so i have a table that have a lot of data series and i use legend option to give user flexibility which data series want to be shown, and it works great. Now i want to extend those features and i wondering how do i get or listen to which data series that been selected?

so for example i have this kind of data series
```
series: [
 { name: 'Aset', data: [], type: 'bar',},
 { name: 'Income', data: [], type: 'bar',},
 { name: 'Cost', data: [], type: 'bar',},
 { name: 'BEP', data: [], type: 'bar',},
]
```

and i need a way to know when user click `Aset` legend then it will somehow broadcast that series with name `Aset` has been selected, so i can to something about it in more advanced way like say do some sorting or others... but first i need to know which one user click

**Comment by Justineo** [comment]
We only deal with issues that are specific to Vue-ECharts, not issues about the usage of ECharts itself. And please follow the issue template, otherwise the issue will be closed directly. Thanks.

**Comment by t0n1zz** [comment]
well i don;t know how to expose the action legend event from echart with vue js type the documentation about echart is only an example with vanila javascript

```
dispatchAction({
    type: 'legendSelect',
    // legend name
    name: string
})
```

**Comment by Justineo** [comment]
All ECharts instance methods are exposed on the component instance. Just use `ref` to identify a component instance and call `dispatchAction` on it. It's covered in the demo:

https://github.com/ecomfe/vue-echarts/blob/9c8bcab5d3454079562abc3b98cc64ba290b1cd4/demo/Demo.vue#L314-L318
