### ISSUE TITLE
 Component series.bar3D not exists. Load it first.   

### ISSUE THREAD

**Issue by jahnli** [ecomfe/vue-echarts#214]
我今天使用vue-echarts 时用到bar3D  但是在页面中就出现报错
`Error in callback for watcher "options": "Error: Component series.bar3D not exists. Load it first."

found in

---> <Chart>
       <Layout> at src\components\hierarchys\layout.vue
         <ElTabPane>
           <ElTabs>
             <Hierarchy> at src\components\hierarchy.vue
               <ElMain>
                 <ElContainer>
                   <Home> at src\page\home.vue
                     <App> at src\App.vue
                       <Root>`

**Comment by Justineo** [comment]
不按模板填写的 issue 将被直接关闭，谢谢。另外，请仔细阅读 README。
