### ISSUE TITLE
"vue-echarts": "^3.0.5", 官方demo，在ie11下白屏，不能工作

### ISSUE THREAD

**Issue by Nosnickers** [ecomfe/vue-echarts#223]
我的新项目中用到echarts4.0中的dataset，没法降级vue-echarts。
错误提示如下
![image](https://user-images.githubusercontent.com/8192906/38717592-66d7d990-3f1a-11e8-9730-d73e9b83e960.png)

**Comment by lerit** [comment]
我也一样，一点点排除，发现是vue-echarts升级到v3以后导致，我将语法改为：
源：
import ECharts from 'vue-echarts/components/ECharts.vue'
新：
import ECharts from 'vue-echarts'
就可以了，你试试看？

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将被直接关闭，谢谢配合。
