### ISSUE TITLE
echarts這個模塊是否需要被install？

### ISSUE THREAD

**Issue by zzzgit** [ecomfe/vue-echarts#226]
echarts這個模塊是否需要被引入package.json？
如果不引用，documentation中的`import 'echarts/lib/chart/bar'`肯定會報錯
如果需要引用，為什麼不在documentation中說明一下

我現在在package.json中加入了echarts，然後運行程序時遇到報錯：

![image](https://user-images.githubusercontent.com/1060733/38926461-5a465a5c-4335-11e8-9057-14281f4c002e.png)

**Comment by Justineo** [comment]
请根据 issue 模板填写，谢谢。未按模板填写的 issue 将被直接关闭。

`echarts` 已经在 `dependencies` 中了。
