### ISSUE TITLE
[bug]Uncaught Error: Cannot find module "echarts/lib/chart/bar"

### ISSUE THREAD

**Issue by zzzgit** [ecomfe/vue-echarts#227]
- [ Bug report]

## Not introduced by ECharts

- [yes] I've checked it's not a problem of ECharts itself.

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ no] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [yes ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
the last version

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

1. `npm i vue-echarts`
2. `import 'echarts/lib/chart/bar'`
3. 
![image](https://user-images.githubusercontent.com/1060733/38966034-b75f8c7c-43b2-11e8-8483-bd04b80f67e4.png)

yes, `echarts` is a dependecy of `vue-echarts`, but it's placed inside this folder:

![image](https://user-images.githubusercontent.com/1060733/38966068-df946cb2-43b2-11e8-8837-60ef9d5525d1.png)

so, we can't import it from 'echarts/lib/chart/bar'

**Comment by Justineo** [comment]
你用的是什么版本的 npm 呢？
