### ISSUE TITLE
click事件监听不到

### ISSUE THREAD

**Issue by zhuhuanchang** [ecomfe/vue-echarts#228]
<chart ref='chartLine'  :options="chartLineOption" theme="my-theme"></chart>

this.$refs['chartLine'].chart.on('click',function(){alert(1)})

然后点击图表，触发不到alert(1)

**Comment by zhuhuanchang** [comment]
<chart ref='chartLine' :options="chartLineOption" theme="my-theme" @click='alert(1)'></chart>

**Comment by kamo9527** [comment]
请问你是如何在饼图绑定点击扇形的回调函数？

**Comment by kamo9527** [comment]
![image](https://user-images.githubusercontent.com/38599425/45200519-c63b7980-b2a3-11e8-8037-2afb627b331c.png)

**Comment by kamo9527** [comment]
pieAction函数无法调用
