### ISSUE TITLE
[bug] IE下出现语法错误

### ISSUE THREAD

**Issue by OckhamRazor** [ecomfe/vue-echarts#232]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
V3.0.7

## Reproduction link / 复现链接
https://ecomfe.github.io/vue-echarts/demo/

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

IE11 打开github pages demo。可以在调试台看到提示语法错误，均为es6语法问题。
确认由resize-detector中 pkg.module引起.
esm/index.js 应当由es5语法编写

相关issue: #208 
相关package module说明：https://github.com/nodejs/node-eps/blob/master/002-es-modules.md

**Comment by OckhamRazor** [comment]
是的。我确定在babel-loader include中设置了vue-echarts以及resize-detector

**Comment by Justineo** [comment]
更新了 demo，只是因为 demo 代码里使用了 `Array.prototype.fill`，去掉以后已经可以在 IE11 运行了，你可以再检查一下。

**Comment by Justineo** [comment]
https://github.com/OckhamRazor/temp-vue-echarts-demo/blob/master/webpack.config.js#L31

把这行去掉呢？

**Comment by OckhamRazor** [comment]
没有任何改变。并且这个操作是不合理的。
按个人理解，moudle它的作用应该是在支持es6 模块规范的环境中以es6的方式引入，但是仍旧需要遵循es5的语法

**Comment by OckhamRazor** [comment]
抱歉。我在几分钟后明白了你的意思，我想最直接的原因是resize-detector未被babel正确编译。我尝试从此开始排除

**Comment by Justineo** [comment]
我已经把你的 repo clone 到本地试过了，把 `exclude` 删掉就能正常编译啊。

```
➜  temp-vue-echarts-demo git:(master) ✗ npm run build

> vue-echarts-bug@1.0.0 build /Users/justice/dev/temp-vue-echarts-demo
> cross-env NODE_ENV=production webpack --progress --hide-modules

Hash: 29a0cc56047cd7d0f91f
Version: webpack 3.11.0
Time: 9069ms
       Asset     Size  Chunks                    Chunk Names
    build.js   410 kB       0  [emitted]  [big]  main
build.js.map  3.44 MB       0  [emitted]         main
```

**Comment by OckhamRazor** [comment]
😊，thank you.我清除ie缓存后，发现问题已经得到解决。

**Comment by KJin9** [comment]
能问下最终解决方案吗？？这个问题怎么解决的哦？谢谢了

**Comment by KJin9** [comment]
vue-cli构建

使用本插件版本V3.0.7
webpack版本V3.6.0

配置
{
    test: /\.js$/,
    loader: 'babel-loader',
    include: [
      resolve('src'),
      resolve('test'),
      resolve('node_modules/webpack-dev-server/client'),
      resolve('node_modules/vue-echarts'),
      resolve('node_modules/resize-detector')
    ]
},
引入方式
 import ECharts from 'vue-echarts/components/ECharts'
  import 'echarts/lib/chart/line'
  import 'echarts/lib/chart/bar'
  import 'echarts/lib/component/tooltip'
  import 'echarts/lib/component/toolbox'
  import 'echarts/lib/component/legend'
  import 'echarts/lib/component/dataZoom'
  import 'echarts/lib/component/visualMap'


报错IE11
 "./node_modules/_normalize-wheel@1.0.1@normalize-wheel/src/normalizeWheel.js":
/***/ (function(module, exports, __webpack_require__) {

SCRIPT1006: 缺少 ')'

**Comment by Justineo** [comment]
@KJin9 报错的地方明显和本项目无关吧……

**Comment by KJin9** [comment]
@Justineo https://github.com/ecomfe/vue-echarts/issues/235
我的报错和这个位置一样，那个copy错了
![1](https://user-images.githubusercontent.com/19336909/40409103-4d8973b2-5e9c-11e8-879f-00f80faadee6.png)

但是引入方式是上面的配置参考官方那种方式的引入

**Comment by KJin9** [comment]
已解决！方式参考https://github.com/ecomfe/vue-echarts/issues/235

最终结果【我的项目中采用如下引入方式就可以】
使用 import ECharts from 'vue-echarts' 方式导入包

如果没有显示请清空IE缓存再试一试！

@Justineo 谢谢了！ thank you
