### ISSUE TITLE
IE 11 下报错 SCRIPT1006: 缺少 ')'

### ISSUE THREAD

**Issue by zhangxiaoshang** [ecomfe/vue-echarts#235]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
"version": "3.0.7"

## Reproduction link / 复现链接
我在一个vue-cli webpack建立的项目中使用了vue-echarts, chrome下运行正常，但是在ie 11 上报错： `SCRIPT1006: 缺少 ')'

然后我把vue-echarts项目克隆至本地，依次执行：

```bash
git clone https://github.com/ecomfe/vue-echarts.git
cd vue-echarts
cnpm i
npm run dev
```

然后访问 http://localhost:8080 查看demo， chrome下正常， ie11依旧存在错误：`SCRIPT1006:  缺少 ')'`

请问这是什么原因导致的，应该如何修复！

**Comment by Justineo** [comment]
你用 npm 安装试试。

**Comment by zhangxiaoshang** [comment]
我用npm安装试了，在ie11上demo可以运行了！

回到项目中，通过npm的方式安装，问题依旧存在。

后来发现问题出在使用方式上，

方式一：`import ECharts from 'vue-echarts/components/ECharts'` ie11不兼容
方式二：`import ECharts from 'vue-echarts'` ie11兼容

我的解决方式：

1. 使用npm代替cnpm安装依赖包（这个貌似不是关键）
2. 使用 `import ECharts from 'vue-echarts'` 方式导入包

问题解决！

这里有demo复现这个问题   [Github repo](https://github.com/zhangxiaoshang/debug-vue-echarts)

**Comment by Justineo** [comment]
使用方式是没问题的，是我 cnpm 的问题。

**Comment by Justineo** [comment]
直接引 vue-echarts 和引 .vue 组件是两种不同的用法，请仔细阅读 README。

**Comment by dai875939260** [comment]
这个确实有问题，按官方下面的写法
```
  transpileDependencies: [
    /\/node_modules\/vue-echarts\//,
    /\/node_modules\/resize-detector\//,
  ],
```
osx下面是没有问题，但是windows构建es6的代码就转换出来有问题了。下面的写法是可以的 @Justineo 
```
  transpileDependencies: [
    'vue-echarts',
    'resize-detector',
  ],
```
windows这样编译出来就可以了

**Comment by Justineo** [comment]
@seawind8888 他的改动并没有解决问题，而是把打包在一起的 ECharts 一起发布出去了。当然，你要是不在乎增加的体积可以用他的方法。

**Comment by seawind8888** [comment]
@Justineo 包确实大了 但确实没有解决方案了 我用npm重装了依赖 还是会出现此问题 只有这样才能彻底解决

**Comment by seawind8888** [comment]
@Justineo 包确实大了一倍多 用npm重装了还是不行 后来发现重启下服务好了

**Comment by itxuye** [comment]
@Justineo 那么这个问题怎么解决呢，在IE11上报这个错误

**Comment by Justineo** [comment]
@itxuye 正确配置你的编译环境，确保 `vue-echarts` 经过 Babel 编译。

**Comment by hehebiaobiao** [comment]
import ECharts from 'vue-echarts'引入

**Comment by gityingjianglin** [comment]
之前用的cnpm  ie浏览器会报错，
使用npm就解决了，目前ie不会报错
使用import ECharts from 'vue-echarts'这种方式打包以后，verdor文件增加了1.5倍

**Comment by caijess** [comment]
transpileDependencies: [
      /[\/\\]node_modules[\/\\]vue-echarts[\/\\]/,
      /[\/\\]node_modules[\/\\]resize-detector[\/\\]/,
    ]
修改正则如上，可兼容wins osx

**Comment by Hello-Huxu** [comment]
我也碰见了这个问题，然后按步骤用npm重装了，ie也刷了缓存，但是无效，于是又刷npm缓存，还是无效，引入的样式也排查过了，注释echarts样式的引入依旧报缺少 ')'
babel-polyfill有装，但是不确定编译到了echarts, 我其他代码都是使用es6语法,确定编译有效，但是echarts无法确定是否编译成功，但讲道理应该是一样的，也编译到了，很奇怪很奇怪，难不成重启试试？
"vue-echarts": "^4.0.3",
"echarts": "^4.2.1",

**Comment by Hello-Huxu** [comment]
> 我也碰见了这个问题，然后按步骤用npm重装了，ie也刷了缓存，但是无效，于是又刷npm缓存，还是无效，引入的样式也排查过了，注释echarts样式的引入依旧报缺少 ')'
> babel-polyfill有装，但是不确定编译到了echarts, 我其他代码都是使用es6语法,确定编译有效，但是echarts无法确定是否编译成功，但讲道理应该是一样的，也编译到了，很奇怪很奇怪，难不成重启试试？
> "vue-echarts": "^4.0.3",
> "echarts": "^4.2.1",
> ![image](https://user-images.githubusercontent.com/31545252/60259725-6e413280-990a-11e9-923e-c145f39f8f30.png)
> ![image](https://user-images.githubusercontent.com/31545252/60259730-713c2300-990a-11e9-94eb-5b7dc9ba6155.png)

该问题已解决，解决方法是将package.lock文件删除  然后npm重新下载, 
导致该问题的应该是npm下载时并没有替换到原先的cnpm下载的包

**Comment by ningstudy** [comment]
npm下载进度一直不动怎么办。。

**Comment by liuxsen** [comment]
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vuex'),
          resolve('node_modules/webpack-dev-server/client')
        ]
      },
可能是 vuex 使用了 es6 以上解决了

**Comment by zl7261** [comment]
resize-detector这个导致的问题

@vue/cli 4.1.1

在vue.config.js中配置了,
```json
 transpileDependencies: [
    'resize-detector',
'vue-charts'
  ]
```
但通过ie11的控制台,还是可以看到
resize-detector/ems/index.js未被polyfill


这个项目整个来说,也就是一个echarts文件,我是通过把这个echarts文件复制到本地组件,
再配置就没有在ie控制台中有显示过这个esm/index.js了
```json
 transpileDependencies: [
    'resize-detector'
  ]
```
