### ISSUE TITLE
一个页面显示多个折线图，遍历vue通过options.series[0].data.push值，结果值都一样，怎么按照每个vue push不同的data

### ISSUE THREAD

**Issue by child110** [ecomfe/vue-echarts#236]
<div class="chart-group" v-for="(cate,index) in indexs">
      <figure>
        <chart :id="cate.id"
          :options="line"
          :init-options="initOptions"
          ref="line"
          auto-resize
        />
      </figure>
        </div>

 let line = _this.$refs.line
 let _this = this
  let line = _this.$refs.line
  line.forEach((lineIndex,index)=>{
                       	var charId = lineIndex.chart._dom.id
                  _this.chartData[charId].forEach((item,index)=>{
                   lineIndex.options.series[0].data.push(item.duration);
                       });
                   lineIndex.options.xAxis.data =_this.indexData[charId].xaxis;
                      })

这样插入的数据是每个line都是同样的数据，并没有按照cate.id插入，请问怎么处理？

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将被直接关闭。谢谢配合。

**Comment by child110** [comment]
## The type of this issue / Issue 类型

## Not introduced by ECharts / 非 ECharts 本身问题

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
<div class="chart-group" v-for="(cate,index) in indexs">
      <figure>
        <chart :id="cate.id"
          :options="line"
          :init-options="initOptions"
          ref="line"
          auto-resize
        />
      </figure>
        </div>

 let line = _this.$refs.line
 let _this = this
  let line = _this.$refs.line
  line.forEach((lineIndex,index)=>{
                       	var charId = lineIndex.chart._dom.id
                  _this.chartData[charId].forEach((item,index)=>{
                   lineIndex.options.series[0].data.push(item.duration);
                       });
                   lineIndex.options.xAxis.data =_this.indexData[charId].xaxis;
                      })

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)
import echarts from 'echarts/lib/echarts'
### The version of Vue-ECharts you are using / Vue-ECharts 的版本
这样插入的数据是每个line都是同样的数据，并没有按照cate.id插入，请问怎么处理？

**Comment by Justineo** [comment]
请填写完整信息并提供完整的可重现的代码。这里只接受新功能需求和 bug 报告。

**Comment by wjhcc2018** [comment]
我也遇到了这个问题
