### ISSUE TITLE
官方文档上的实例报错

### ISSUE THREAD

**Issue by jsonwu5** [ecomfe/vue-echarts#238]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

按照官方文档上实例运行，控制台报错：Error in mounted hook: "TypeError: Cannot read property 'findAxisModel' of undefined"

found in

**Comment by Justineo** [comment]
> 按照官方文档上实例运行

确定吗？贴一下代码？

**Comment by jsonwu5** [comment]
就是官方文档上的例子：

`import 'echarts/lib/chart/line'

  export default {
    data: function () {
      let data = []

      for (let i = 0; i <= 360; i++) {
        let t = i / 180 * Math.PI
        let r = Math.sin(2 * t) * Math.cos(2 * t)
        data.push([r, i])
      }

      return {
        polar: {
          title: {
            text: '极坐标双数值轴'
          },
          legend: {
            data: ['line']
          },
          polar: {
            center: ['50%', '54%']
          },
          tooltip: {
            trigger: 'axis',
            axisPointer: {
              type: 'cross'
            }
          },
          angleAxis: {
            type: 'value',
            startAngle: 0
          },
          radiusAxis: {
            min: 0
          },
          series: [
            {
              coordinateSystem: 'polar',
              name: 'line',
              type: 'line',
              showSymbol: false,
              data: data
            }
          ],
          animationDuration: 2000
        }
      }
    }
  }`

**Comment by jsonwu5** [comment]
浏览器窗口里空白，控制台里提示报错信息：Error in mounted hook: "TypeError: Cannot read property 'findAxisModel' of undefined"

**Comment by Justineo** [comment]
ECharts 的组件要自己引入的。文档里只是一个例子，具体要哪些要看你的图表数据。你可以看我 demo 目录下的例子。

**Comment by jsonwu5** [comment]
@Justineo 好的我明白了，问题已解决，谢谢！
