### ISSUE TITLE
using dataset component

### ISSUE THREAD

**Issue by dormadekhin-denis** [ecomfe/vue-echarts#240]
## The type of this issue / Issue 类型
- [ ] Bug report / Bug

## Details 

If you use the dataset component for an array of data, an error appears in the browser console:
```
chart-page.js:16825 [Vue warn]: Error in mounted hook: "TypeError: t.count is not a function"

found in

---> <Chart>
       <Root>
warn @ chart-page.js:16825

chart-page.js:17973 TypeError: t.count is not a function
    at $v.Kv.initData (chart-page.js:47335)
    at Ob (chart-page.js:47335)
    at i.getInitialData (chart-page.js:47335)
    at init (chart-page.js:47335)
    at i.<anonymous> (chart-page.js:47335)
    at Array.forEach (<anonymous>)
    at r (chart-page.js:47335)
    at i.<anonymous> (chart-page.js:47335)
    at Function.t.topologicalTravel (chart-page.js:47335)
    at i.mergeOption (chart-page.js:47335)
```

### How are you importing Vue-ECharts?

- [ ] Bundled version/(`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using
3.0.7

**Comment by Justineo** [comment]
You are not providing a valid reproduction here. There's not much we can help here.

**Comment by cbarlow1993** [comment]
Did you work out what you were doing wrong? I've got the same error. 

I'm trying to get the count on the Y axis with dates on the X. 

```
              <e-chart 
                :path-option="[
                  ['dataset.dimensions', [{name: 'count'} , 'count', {name:'count', type: 'number'}]],
                  ['dataset.source', data],
                  ['legend.show', true],
                  ['xAxis.axisLabel.show', true],
                  ['yAxis.axisLabel.show', true],
                  ['grid.left', '2%'],
                  ['grid.bottom', '5%'],
                  ['grid.right', '3%']
                ]"
                height="400px"
                width="100%"
                >
                </e-chart> 
```
My data structure is:

```

[
  {
    "date": "25-10-2018",
    "count": 1,
    "first": "2018-10-25T15:24:02.075Z",
    "last": "2018-10-25T15:24:02.075Z"
  },
  {
    "date": "26-10-2018",
    "count": 1,
    "first": "2018-10-26T15:23:55.678Z",
    "last": "2018-10-26T15:23:55.678Z"
  },
  {
    "date": "27-10-2018",
    "count": 0,
    "first": null,
    "last": null
  },
  {
    "date": "28-10-2018",
    "count": 0,
    "first": null,
    "last": null
  }
]


```

**Comment by hantmac** [comment]
> I encountered this issue as well, the workaround I found is to create a dataset source with a count key [{'count':0}]. Without a count key, I get an error like above.

Hi, I encountered this issue as well, can you provide your dataset example?

**Comment by EricaAbreu** [comment]
> > I encountered this issue as well, the workaround I found is to create a dataset source with a count key [{'count':0}]. Without a count key, I get an error like above.
> 
> Hi, I encountered this issue as well, can you provide your dataset example?

hi, did you get it solved?
I am having the same problem.

**Comment by cratosm** [comment]
> ## The type of this issue / Issue 类型
> * [ ]  Bug report / Bug
> 
> ## Details
> If you use the dataset component for an array of data, an error appears in the browser console:
> 
> ```
> chart-page.js:16825 [Vue warn]: Error in mounted hook: "TypeError: t.count is not a function"
> 
> found in
> 
> ---> <Chart>
>        <Root>
> warn @ chart-page.js:16825
> 
> chart-page.js:17973 TypeError: t.count is not a function
>     at $v.Kv.initData (chart-page.js:47335)
>     at Ob (chart-page.js:47335)
>     at i.getInitialData (chart-page.js:47335)
>     at init (chart-page.js:47335)
>     at i.<anonymous> (chart-page.js:47335)
>     at Array.forEach (<anonymous>)
>     at r (chart-page.js:47335)
>     at i.<anonymous> (chart-page.js:47335)
>     at Function.t.topologicalTravel (chart-page.js:47335)
>     at i.mergeOption (chart-page.js:47335)
> ```
> 
> ### How are you importing Vue-ECharts?
> * [ ]  Bundled version/(`import ECharts from 'vue-echarts'`)
> 
> ### The version of Vue-ECharts you are using
> 3.0.7

Hi, do you have an update, I am having the same problem.

**Comment by unknown1337** [comment]
did you load import 'echarts/lib/component/dataset';?
