### ISSUE TITLE
Feature Request: 触发rendered和finished事件

### ISSUE THREAD

**Issue by jeange1003** [ecomfe/vue-echarts#241]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

希望组件能够触发[rendered](http://echarts.baidu.com/api.html#events.rendered)和[finished](http://echarts.baidu.com/api.html#events.finished)事件

**Comment by Justineo** [comment]
新版本已经支持。谢谢建议。
