### ISSUE TITLE
在低版本chrome种无法打开demo

### ISSUE THREAD

**Issue by 404157386** [ecomfe/vue-echarts#242]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

demo用不支持es6的浏览器打开，无法运行，打包的时候会把resize-detector es6语法打包进去

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.7

**Comment by Justineo** [comment]
你确定吗：https://ecomfe.github.io/vue-echarts/demo/static/js/vendor.cf174a0eb42f40dc4815.js

明明在 IE 下都能运行啊……

**Comment by 404157386** [comment]
我这边npm run demo 会报错
你的resize-detector是es6写法 打包不了
![image](https://user-images.githubusercontent.com/16297662/40606813-31cf6464-6299-11e8-94a2-cfdd3512d405.png)

**Comment by Justineo** [comment]
你用的是不是 cnpm？

**Comment by 404157386** [comment]
对啊 不能用吗

**Comment by Justineo** [comment]
cnpm 自己做了一些特殊的处理以后，和很多工具都不能正常配合使用。建议你直接使用 npm 或者 Yarn，如果怕速度慢可以把 registry 设置为淘宝的源：https://registry.npm.taobao.org。

**Comment by Justineo** [comment]
我们只能保证在 npm/Yarn 下正常使用，谢谢了。

**Comment by 404157386** [comment]
我多问一句 你知道为什么在vue里面import es6写的npm包 babel不能编译吗？
我研究了一下午 都找不到怎么解决
但是写在*.vue上面的es6却可以被编译
是vue-loader的问题 还是babel-loader的问题呢？
