### ISSUE TITLE
在nuxt框架下通过plugin引用，在Webkit浏览器正常显示，在IE9-IE11下无显示。控制台报错

### ISSUE THREAD

**Issue by ringgoyao** [ecomfe/vue-echarts#244]
## The type of this issue / Issue 类型

Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接
无

**Comment by Justineo** [comment]
没有重现步骤，没有报错信息，你觉得别人要怎么帮你？

**Comment by ringgoyao** [comment]
不好意思，是我的错，Vue-echart我用在客户端上确实很方便，也没有什么问题，
这个问题研究了太久，有点心力交瘁。
我在码云上这个demo请你看一下：[Demo下载](https://gitee.com/ringgo/testSSR.git) 
`npm i`
`npm run dev`
我看了nuxt官网下的example ，它的一个关于chart.js的例子在IE下倒是正常。
[chartjs](https://github.com/nuxt/nuxt.js/tree/dev/examples/vue-chartjs)

**Comment by Justineo** [comment]
https://gitee.com/ringgo/testSSR/blob/master/nuxt.config.js#L38

**Comment by ringgoyao** [comment]
上传的时候，代码没有提取干净，
我把代码按照说明修改成这样：
`config.module.rules.push(
          {
            test: /\.js$/,
            loader: 'babel-loader',
            include: [
              resolve('src'),
              resolve('test'),
              resolve('node_modules/vue-echarts'),
              resolve('node_modules/resize-detector')
            ]
          }
        )` 
可是还是老问题呢

**Comment by Justineo** [comment]
@ringgoyao 看一下新加的这段说明：

https://github.com/ecomfe/vue-echarts/blob/master/README.zh_CN.md#%E5%9C%A8-nuxtjs-%E4%B8%AD%E4%BD%BF%E7%94%A8

**Comment by Justineo** [comment]
先关闭了，如有疑问欢迎继续反馈。

**Comment by Justineo** [comment]
@muzi131313 你使用的 Nuxt.js 的版本是？

**Comment by muzi131313** [comment]
2.2.0

**Comment by Justineo** [comment]
https://nuxtjs.org/api/configuration-build#transpile

直接配置：

```js
{
  build: {
    transpile: ['resize-detector']
  }
}
```

**Comment by muzi131313** [comment]
感谢，解决了。之前尝试在extend中加babel转换，一直不行
