### ISSUE TITLE
在手机端使用dataZoom缩放时卡顿

### ISSUE THREAD

**Issue by roy-yi** [ecomfe/vue-echarts#246]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
在**手机上**使用dataZoom缩放的时候，非常卡顿。直接引用echarts则没有此问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

```
import ECharts from "vue-echarts/components/ECharts";
import "echarts";

Vue.component("chart", ECharts);

```
或者
```
import ECharts from 'vue-echarts';
import "echarts";

Vue.component("chart", ECharts);
```
- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
`"vue-echarts": "^3.0.7"`

## Reproduction link / 复现链接
https://nnq9o6lqz4.codesandbox.io/

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：https://codesandbox.io/s/nnq9o6lqz4

**Comment by Justineo** [comment]
手机上打开上面的链接似乎没有 dataZoom？

**Comment by roy-yi** [comment]
@Justineo 我这边用手机打开上面的链接可以缩放的

**Comment by roy-yi** [comment]
@Justineo 哈喽，这个问题有解决方案吗？

**Comment by mzy2240** [comment]
你有没有试过用原生的echarts？

**Comment by guizhichao** [comment]
wonderful

**Comment by Justineo** [comment]
We stopped maintaining Vue ECharts version < 6. If there are still similar problems in v6, please open a new issue with runnable repro. Thank you.
