### ISSUE TITLE
i want to use gird

### ISSUE THREAD

**Issue by 7ben** [ecomfe/vue-echarts#247]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
i want to use gird [x, x2, y, y2] or [top, left, bottom, right] 
how can i use to it 
help me plz
### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

"vue-echarts": "^3.0.5",

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
Please refer to ECharts' documentation and the README. Issues are for bug reports and feature requests only, as the issue template suggested.

In general you just need to import corresponding components/charts from `echarts` and it should work.

**Comment by 7ben** [comment]
![1za](https://user-images.githubusercontent.com/40053285/41392861-157e93be-6fde-11e8-8925-8f8753e973fc.png)

my soruce is
 option: {
          backgroundColor: '#FFFFFF',
          legend: {
            x: 'center',
            padding: [5, 0, 10, 0]
          },
          grid: [
            {
              x: 0,
              y: 0,
              x2: 0,
              y2: 0
            }
          ],
.....
}
i fefer to echarts' documentation 
https://ecomfe.github.io/echarts-doc/public/en/option.html#grid
but vue-ehcarts don't used grid, like insert image
i want to be fulled, no empty 
plz help me

**Comment by Justineo** [comment]
We only deal with those issues that you can get something work in ECharts but cannot get it work in Vue-ECharts. After you made it work in ECharts but not Vue-ECharts, you can come back and open a new issue.
