### ISSUE TITLE
如何根据动态数据无刷新更新echart

### ISSUE THREAD

**Issue by RikaLuo** [ecomfe/vue-echarts#249]
## Issue 类型

- [x] 如何根据动态数据无刷新更新echart

##   ECharts 本身问题

我检查了下 不太确定这个是否是echart本身的问题

### 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

###Vue-ECharts 的版本 
"vue-echart": "^1.0.5"

## Reproduction link / 复现链接
如图所示，需要根据筛选条件变更而实时更新echart图形。目前是数据获取到了 但echart未更新，需刷新页面后才会更新echart
![image](https://user-images.githubusercontent.com/19562162/41325149-4befb886-6eeb-11e8-94bf-d9b556a3d816.png)

**Comment by Justineo** [comment]
直接修改绑定到组件的 `options` 属性即可。

**Comment by pangguobo** [comment]
你好,这个问题如何解决的??
