### ISSUE TITLE
Can vue-echarts support CSP rules?

### ISSUE THREAD

**Issue by Fuji-sunny** [ecomfe/vue-echarts#250]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

When using CSP meta in HTML file like this: 
<meta http-equiv="Content-Security-Policy" content="default-src 'self';"> 

Here comes an console error says that:
Refused to execute inline style because it violates the following Content Security Policy directive: "default-src 'self'".

Though the Chrome devtool would found that some <style> tag was inserted into DOM like:
.resize-triggers { ... }

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

3.0.7

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
It’s related to `resize-detector`, not the current project. And as I understand the injected `<style>` is essential currently.

**Comment by Fuji-sunny** [comment]
@Justineo Can these css in resize-detector import separately in vue-echarts ? Then we can use tools like webpack to extract these css in to a single file. That may avoid errors cause by CSP rules.

**Comment by Justineo** [comment]
They are included [using `require`](https://github.com/Justineo/resize-detector/blob/eee0d19a61e9a7dba958594ae87559f553406b98/src/index.js#L9) so they should be extractable.

**Comment by Justineo** [comment]
@Fuji-sunny Hi, have you solved the problem?

**Comment by Justineo** [comment]
Closing this until more feedback.

**Comment by Gagydzer** [comment]
x-vue-echarts{display:block;width:100%;height:100%}

this style inlines into page and doesn't respect CSP.

**Comment by Qolzam** [comment]
Hi @Justineo 👋, 
Do we have a solution for what @Gagydzer mentioned about `x-vue-echarts{display:block;width:100%;height:100%}`?
<img width="553" alt="image" src="https://user-images.githubusercontent.com/8446573/170400682-86a79eaf-7070-4afc-be68-0c0d754bc715.png">

Thank you!

**Comment by MichalKrakow** [comment]
Same, here. So vue-echarts are not csp complient... :/ that should be in specs like first thing

**Comment by jet4419** [comment]
It's 2025, yet still the same problem :/

**Comment by Justineo** [comment]
> It's 2025, yet still the same problem :/

What version are you using and have you read the readme?

**Comment by jet4419** [comment]
I'm using v7.0.3

**Comment by Justineo** [comment]
> have you read the readme?

**Comment by jet4419** [comment]
> > have you read the readme?

yup

**Comment by jet4419** [comment]
I imported VChart using vue-echarts/csp and imported the vue-echarts/csp/style.css in the main.ts

**Comment by Justineo** [comment]
What issue are you experiencing? Can you create a new issue and describe the issue more clearly?

**Comment by jet4419** [comment]
New issue opened — really appreciate the fast reply, @Justineo !
