### ISSUE TITLE
Throw som errors message if some packages is not imported

### ISSUE THREAD

**Issue by arixse** [ecomfe/vue-echarts#253]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求

## Details / 详情

I suggest that vue-echarts will throw a corresponding error if the corresponding component was not be imported,such as dataZoom,legend....

```javascript
throw new Error('dataZoom was not be importd,please import it first!')
```

**Comment by Justineo** [comment]
This cannot be detected because we would only know you want to use something `dataZoom` **after** you importing the corresponding components/charts.
