### ISSUE TITLE
echarts-gl 地球添加地图时，无效

### ISSUE THREAD

**Issue by esioncao** [ecomfe/vue-echarts#255]
echarts-gl 地球添加地图时，无效
通过this.mapChart = echarts.init(document.createElement('canvas'), option, {width: 2048, height: 1024}
创建地图时通过mergeOptions设置属性时，无效，
直接在属性上设置时 报错Error in mounted hook: "TypeError: Cannot read property 'getZr' of undefined
 target.mergeOptions({layers: [{
                        type: 'overlay',
                        show: true,
                        texture: this.mapChart,
                        distance: 0
                        // type:'blend'
            }]});

**Comment by Justineo** [comment]
不按模板填写的 issue 将被直接关闭，谢谢。
