### ISSUE TITLE
设置坐标轴文本标旋转角度rotate的问题

### ISSUE THREAD

**Issue by 969723815** [ecomfe/vue-echarts#256]
真机里面跑偏啦

![tim 20180702162535](https://user-images.githubusercontent.com/34827395/42153137-cb724582-7e14-11e8-8562-6dca6d97106f.png)

设置坐标轴文本标旋转角度在真机有问题，跑偏啦
axisLabel:{
rotate:45
}

**Comment by Justineo** [comment]
不按 issue 模板填写将被直接关闭，谢谢。
