### ISSUE TITLE
Trigger datazoom event inside a custom button

### ISSUE THREAD

**Issue by daniilc-magnumwm** [ecomfe/vue-echarts#259]
## The type of this issue / Issue 类型

- [ ] Feature request 

## Details / 详情

I need to create a series of range buttons, that can trigger datazoom event. 
Such as last month, last week, 3 month, etc.

![2018-07-13_12-43-06](https://user-images.githubusercontent.com/40162628/42673219-d0edaf84-869c-11e8-867c-f82fbfe9e113.png)

As far as I get there is no available interface for this kind a task. 
The solution might could be to create a number of buttons outside echarts module and trigger action using` dispatchAction`
Is there are any other convenient methods to solve this problem? 

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
v3

**Comment by Justineo** [comment]
Even if `dispatchAction` is not enough for your case, this feature request should be filed in ECharts itself, not Vue-ECharts.

**Comment by daniilc-magnumwm** [comment]
Agree, but I thought that inside vue-echarts there might be an interface for creating trigger events between standard component and echart.

**Comment by daniilc-magnumwm** [comment]
Not sure I need to create a new issue, but I have a problem with graph scaling after sending an event to echarts

The code
https://codesandbox.io/s/woqlnzyznl

Snippets:
```
<template>
  <figure>
    <v-btn v-on:click="today">Today</v-btn>
    <v-btn v-on:click="last_week">Last week</v-btn>
    <v-btn v-on:click="last_month">Last month</v-btn>
    <v-btn>3 month</v-btn>
    <chart
        :options="candlestick"
        ref="candlestick"
        auto-resize
    />
  </figure>
</template>
```

And the corresponding methods

```
    methods: {
      today: function () {
        console.log("Today clicked")
        this.changeDataZoom()
      },

      last_week: function () {
        console.log("Last week clicked")
        this.changeDataZoom()
      },

      last_month: function () {
        console.log("Last month clicked")
        this.changeDataZoom()
      },

      changeDataZoom: function () {
        let candlestick = this.$refs.candlestick
        console.log('mounted')
        candlestick.dispatchAction(
          {
            type: 'dataZoom',
            start: 20,
            end: 50
          })
      }

```

Before `dispatchAction` scaling works fine, but after this action it's crashes

**Comment by Justineo** [comment]
> https://codesandbox.io/s/woqlnzyznl

It's not working.

You may need to import `dataZoom` component before you use that feature.

If your app is not that size-sensitive, you can just import the whole `vue-echarts` package like this:

```js
import ECharts from 'vue-echarts'
```

That will include most commonly used charts and components.

**Comment by daniilc-magnumwm** [comment]
Thanks, I solve it.
