### ISSUE TITLE
Server-client communication in vue-echarts

### ISSUE THREAD

**Issue by daniilc-magnumwm** [ecomfe/vue-echarts#260]
## The type of this issue / Issue 类型

-  Question / 题

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

I'm a bit confused about the proper using vue-echarts when I have to wait the data come from the server. 
I found that this problem doesn't covered well in the demo project, so that question might be interested for other users as well.

I'll describe the case based on the demo project. I have a bar chart, I need to initialize it when I receive the data from the server.  Before I get the data, the bar should be render, but without any data

I have specified the `props` in my child `bar component`, and handle the data in `watcher`.

```
export default {
  name: "bar",
  props: {
    data_from_server: {
       type: Array
   },

  data () {
    let options = qs.parse(location.search, { ignoreQueryPrefix: true })
    return {
      options,
      bar: getBar(data_from_server),
      initOptions: {
        renderer: options.renderer || 'canvas'
      },
    }
  },

  watch: {
      data_from_server: function (newData) {
        if (!data_from_server){
          this.renderData(newData)
        }
      }
    },

  methods: {
    renderData: function(data) {
        console.log("Data recieved")
        let bar = this.$refs.bar
        candlestick.mergeOptions(getBar(data))
      },
  }
```
Where `getData (data_from_server)` is following

```
export default function getData (data_from_server) {
  return {
    legend: {},
    tooltip: {},
    dataset: {
      // Provide data.
      source: data_from_serve
    },
    // Declare X axis, which is a category axis, mapping
    // to the first column by default.
    xAxis: { type: 'category' },
    // Declare Y axis, which is a value axis.
    yAxis: {},
    // Declare several series, each of them mapped to a
    // column of the dataset by default.
    series: [{ type: 'bar' }, { type: 'bar' }, { type: 'bar' }]
  }
}
```

Before I receive a response from the sever my app will crash, as there is no data to render the bar.
I thought of making a global variable, that is initially is empty or use `initOptions` in that case, but I think that there should be a common solution for such kind of problems

I would appreciate if you help me how to do a proper vue-echarts - server bundle.

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
v3

**Comment by Justineo** [comment]
The demo has already included the case for rendering async data. I don't see there is anything we should provide for the case of remote data. You just update the local data binded to `options` on new data arrival (in this case `bar`), that's all.

**Comment by daniilc-magnumwm** [comment]
So does it mean that I don't need to call `bar.mergeOptions(getBar(data))` when I want to update?

**Comment by daniilc-magnumwm** [comment]
What should I call to update the `xAxis` with a new data?

**Comment by daniilc-magnumwm** [comment]
I tried to use flag `v-if=is_rendered` in my parent div block in order to prevent rendering the echart object before the data comes from the server, but the echart object keeps initiating, eventhough I expect it to it when I turn the `is_rendered = true`
@Justineo
