### ISSUE TITLE
如果data数据是在created时候异步获取的，chart中的data无法获取到数据

### ISSUE THREAD

**Issue by xusongfu** [ecomfe/vue-echarts#261]
//vue初始化时候的变量
data(){
             return{
                 incomeListX:[],
                 incomeListY:[],
                 chartOption:{
                    tooltip: {
                        trigger: 'axis',
                        axisPointer : {          
                            type : 'shadow'
                        }
                    },
                    xAxis: {
                        name:'月份',
                        data:this.incomeListX
                    },
                    yAxis: {
                        name:'营业额(元)'
                    },
                    series: [{
                        name: '营业额',
                        type: 'bar',
                        data: this.incomeListY
                    }]
                 }
             }
//created时候调用下面的函数
created(){
            let that=this;
            that.getMonthIncome(7);
        },
//该函数用来异步获取data数据
getMonthIncome(months){
                let that=this;
                let tokens=localStorage.getItem('staffTokens');
                that.tokens=tokens;
                that.$axios.get(that.$URL+'/admin/revenue/monthly?months='+months,{headers:{'Authorization':'Bearer '+that.tokens}}).then(res=>{
                    if(res.data.status===200){
                        that.incomeListX=res.data.statistics.map(elem=>{
                            return elem.date
                        })
                        that.incomeListY=res.data.statistics.map(elem=>{
                            return elem.real_income/100
                        })
                    }
                    else{
                        that.$message({
                            message:res.data.message,
                            type:'error',
                            duration:1000
                        })
                    }
                })
            },

**Comment by Justineo** [comment]
不按模板填写的 issue 将被直接关闭，谢谢。
