### ISSUE TITLE
How to handle the events in vue-echarts?

### ISSUE THREAD

**Issue by shabai517** [ecomfe/vue-echarts#263]
I find in the documents that vue-charts support lots of events from Echarts. But how can I handle these events?

From my point, if there is one prop like "events", it will be much clear and easy. For example:
~~~~
<template>
     <chart :options="options" :auto-resize="true" :events="events"></chart>
</template>
<script>
    export default {
        data:function(){
             return{
                  options:{},
                  events: {
                        click: this.test
                   }
             }
        },
        methods:{
           test(e){
             console.log(e);
           }
        },
    }
</script>
~~~~

But anyway, may I know how to handle the events in the current vue-charts framework?

Thanks a lot!

**Comment by Justineo** [comment]
Just the same way as normal Vue components: https://vuejs.org/v2/guide/events.html.

**Comment by shabai517** [comment]
Thanks! Already find it in: https://github.com/ecomfe/vue-echarts/issues/64
