### ISSUE TITLE
Horizontal Stacked Bar Chart does not stay in container

### ISSUE THREAD

**Issue by zherman91** [ecomfe/vue-echarts#264]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
Version: 3.0.9

## Reproduction link / 复现链接
![image](https://user-images.githubusercontent.com/15216104/43467655-2b1d2bd0-94b0-11e8-8eee-39d4af67419d.png)

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

The only time I have experienced this issue is when I create a horizontal stacked bar chart. In the screenshot above, you'll notice that the two stacked bar charts are not staying within their container. I have attempted to adjust the sizes of the container but I still get the same result. I also changed the orientation to vertical and the issue goes away. Any help you can provide is greatly appreciated. Thanks.

**Comment by Justineo** [comment]
Hi, please provide a runnable reproduction so that we can look into this.

**Comment by zherman91** [comment]
Hi @Justineo 
Thanks for getting back to me. I just finished a CodeSandbox demonstrating the issue at this link: https://codesandbox.io/s/pym2ynyr4j?module=%2Fsrc%2Fcomponents%2FHelloWorld.vue

Let me know what you find out. Thanks again for the help. 

Zac

**Comment by zherman91** [comment]
@Justineo - Any luck with this? Did my CodeSandbox work as expected? Let me know when you can. I really appreciate your time. 

Thanks. 
Zac

**Comment by Justineo** [comment]
Haven't got time to dig into this. But as I understand Vue ECharts itself has no way to make ECharts draw outside its canvas.

**Comment by zherman91** [comment]
I understand you are busy. Based on your comment above, are you saying you think this may be related to something other than Vue-ECharts?

**Comment by Justineo** [comment]
> Based on your comment above, are you saying you think this may be related to something other than Vue-ECharts?

I switched to using ECharts itself directly and the problem still exists. So it looks like there's not much we can do on Vue-Echarts' side. I'll report this to team ECharts later.

https://codesandbox.io/s/vqlz88opm0
