### ISSUE TITLE
Radar Chart SVG

### ISSUE THREAD

**Issue by BrockReece** [ecomfe/vue-echarts#266]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
I have followed your readme and demo but I am unable to render a SVG Radar chart. It is always rendered onto a canvas despite changing the `renderer` init-option to `svg`

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.9

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

I have experienced this issue on both Nuxt and the following codesandbox.
https://codesandbox.io/s/3098woloqm

**Comment by rang-ali** [comment]
Add this import: `import 'zrender/lib/svg/svg';`

**Comment by BrockReece** [comment]
Awesome, thank you so much.
Would it be worth adding this to the readme, happy to do it for you?
