### ISSUE TITLE
咨询个vue组件change事件刷新echart表格的问题

### ISSUE THREAD

**Issue by linzhi** [ecomfe/vue-echarts#267]
html部分是

![image](https://user-images.githubusercontent.com/450938/43820166-05279618-9b18-11e8-826a-f11ecc915900.png)

然后绘图部分是
![image](https://user-images.githubusercontent.com/450938/43820120-df0435c2-9b17-11e8-8bcb-6374618e94cf.png)

但是下拉框选择后 触发事件就报错，这一行this.chart = echarts.init(document.getElementById(id));

**Comment by Justineo** [comment]
不按模板填写的 issue 将被直接关闭，谢谢。

**Comment by linzhi** [comment]
额。。。好 不过我知道为啥了 供其他人参考
    this.chart = echarts.init(document.getElementById()) 
是初始化 执行一次就行，后面的change事件只要设置option就可以

**Comment by pangguobo** [comment]
> 额...好不过我知道为啥了供其他人参考
> this.chart = echarts.init（document.getElementById（））
> 是初始化执行一次就行，后面的改变事件只要设置选项就可以



> 额...好不过我知道为啥了供其他人参考
> this.chart = echarts.init（document.getElementById（））
> 是初始化执行一次就行，后面的改变事件只要设置选项就可
成功解决了我的问题
