### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispatchAction' of undefined

### ISSUE THREAD

**Issue by linzhi** [ecomfe/vue-echarts#268]
## The type of this issue / Issue 类型

 Bug 报告

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

  import echarts from 'echarts'

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
echart是4.1.0

## Reproduction link / 复现链接
   var index = 0; //播放所在下标
          var mTime = setInterval(function() {
            this.chart.dispatchAction({
              type: 'showTip',
              seriesIndex: 0,
              dataIndex: index
            });
            index++;
            if(index > data.length) {
              index = 0;
            }
          }, 1000);

异常是：
Uncaught TypeError: Cannot read property 'dispatchAction' of undefined

类似这个问题 https://github.com/apache/incubator-echarts/issues/7757

**Comment by Justineo** [comment]
@linzhi 你是说你自己调用 `this.chart.dispatchAction.call(this.chart, ...)` 了？

**Comment by linzhi** [comment]
@Justineo  不是的，我把上面的代码改成了

              var index = 0;
              var _this = this
              setInterval(function() {
                _this.chart.dispatchAction({
                  type: 'showTip',
                  seriesIndex: 0,
                  dataIndex: index
                });
                index++;
                if(index > res.data.data.timeline.length) {
                  index = 0;
                }
              }, 1000);

原来的代码的this.chart.dispatchAction的this指针不是我初始化的表格      this.chart = echarts.init(document.getElementById('managerBaseFeatureChart'), {renderer:'svg'});
