### ISSUE TITLE
使用webpack打包的时候报错了

### ISSUE THREAD

**Issue by jimpier** [ecomfe/vue-echarts#269]
项目中引用了vue-echarts，开发的时候正常，但是webpack打包的时候就报错
.vue
import Vue from 'vue'
import ECharts from 'vue-echarts/components/ECharts.vue'
import 'echarts/lib/chart/pie'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/legend'
import 'echarts/lib/component/title'
Vue.component('echart', ECharts)

package.json
"babel-loader": "^7.1.2",
"vue": "^2.5.16",
"webpack": "^3.8.1",
"vue-echarts": "^3.0.9"

webpack.prod.js
{
  test: /\.js$/,
  // exclude: /node_modules(?![\\/]vue-echarts[\\/])/,
  loader: 'babel-loader',
  include: [resolve('src'), resolve('test'), resolve('node_modules/vue-echarts'), 
  resolve('node_modules/resize-detector')]
}
.babelrc
{
	"presets": [
		["env", {
			"modules": false
		}],"stage-2" 
	],
	"plugins": [
		[
			"transform-runtime", {
				"helpers": false,
				"polyfill": false,
				"regenerator": true,
				"moduleName": "babel-runtime"
			}
		],
		[
			"component", 
			[{
				"libraryName": "element-ui",
				"styleLibraryName": "theme-chalk"
			}]
		], "syntax-dynamic-import"
	]
}
错误
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SAMPLE@1.0.0 build: `webpack --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SAMPLE@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

我下载了你们的代码，但是发现npm run build也报错
我简化了自己的代码，地址是：https://github.com/jimpier/echart-test.git
npm run dev正常使用
npm run build就报错

**Comment by winki** [comment]
同样遇到这个问题，题主解决了吗

**Comment by jkwchui** [comment]
同样遇到这个问题, 解决打包报错: absolute path

import ECharts from '../../node_modules/vue-echarts/components/ECharts.vue'
import '../../node_modules/echarts/lib/chart/pie'
import '../../node_modules/echarts/lib/component/tooltip'
import '../../node_modules/echarts/lib/component/legend'
import '../../node_modules/echarts/lib/component/title'
