### ISSUE TITLE
如何更新到vue-cli 3.0

### ISSUE THREAD

**Issue by GitHdu** [ecomfe/vue-echarts#270]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

你好，请问vue-cli3.0的webpack改如何配置来实现按需引入

```
const path = require('path')

function resolve(dir) {
  return path.join(__dirname, './', dir)
}
module.exports = {
  chainWebpack: config => {
    config.module
      .rule('compile')
      .test(/\.js$/)
      .include.add(resolve('node_modules/vue-echarts'))
      .add(resolve('node_modules/resize-detector'))
      .end()
      .use('babel')
      .loader('babel-loader')
      .end()
  }
}
```

我在vue.config.js文件下加入以上代码，报错

`
export 'default' (imported as 'echarts') was not found in 'echarts/lib/echarts
`

**Comment by Justineo** [comment]
https://github.com/vuejs/vue-cli/tree/dev/packages/%40vue/cli-plugin-babel#configuration

尝试一下按这里的方式配置呢？

**Comment by GitHdu** [comment]
@Justineo 
加了这个
```
module.exports = {
  transpileDependencies: [
    // can be string or regex
    'vue-echarts',
    'resize-detector'
  ],
}
```

结果报错

```
Error: webpack-internal:///./node_modules/_@babel_runtime@7.0.0-beta.47@@babel/runtime/node_modules/core-js/modules/_is-object.
  js:5
  module.exports = function (it) {
                 ^
  TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

  - _is-object.js:5 Module.eval
    [.]/[runtime]/[core-js]/modules/_is-object.js:5:16

  - _is-object.js:8 eval
    [.]/[runtime]/[core-js]/modules/_is-object.js:8:30

  - index.html:1046 Module../node_modules/_@babel_runtime@7.0.0-beta.47@@babel/runtime/node_modules/core-js/modules/_is-object.js    /Users/yangchao/vue-echarts/public/index.html:1046:1

  - index.html:684 __webpack_require__
    /Users/yangchao/vue-echarts/public/index.html:684:30

  - index.html:61 fn
    /Users/yangchao/vue-echarts/public/index.html:61:20

  - _inherit-if-required.js:1 eval
    [.]/[runtime]/[core-js]/modules/_inherit-if-required.js:1:16

  - index.html:1011 Object../node_modules/_@babel_runtime@7.0.0-beta.47@@babel/runtime/node_modules/core-js/modules/_inherit-if-r    equired.js
    /Users/yangchao/vue-echarts/public/index.html:1011:1

  - index.html:684 __webpack_require__
    /Users/yangchao/vue-echarts/public/index.html:684:30

  - index.html:61 fn
    /Users/yangchao/vue-echarts/public/index.html:61:20

  - es6.regexp.constructor.js:3 eval
    [.]/[runtime]/[core-js]/modules/es6.regexp.constructor.js:3:25
```

**Comment by Justineo** [comment]
@GitHdu 可能可以尝试一下用正则：`/\bvue-echarts\b/`

**Comment by GitHdu** [comment]
@Justineo 正则好像要这样才可以：`/node_modules\/vue-echarts/`

**Comment by liuzhibin123** [comment]
@GitHdu  我按照你上面的配置了但是在EDGE里面还是报缺少“：”错误，怎么解决？

**Comment by GitHdu** [comment]
@liuzhibin123 chrome是可以的吗？正则或字符的两种方式都可以试一试

**Comment by Justineo** [comment]
@GitHdu 你确定你没有把正则传到 `resolve` 函数里了么？

**Comment by GitHdu** [comment]
@Justineo 没有啊
```
transpileDependencies: [/\bvue-echarts\b/, /\bresize-detector\b/],
```

**Comment by Justineo** [comment]
@GitHdu 我自己测试过是没有问题的……

**Comment by Justineo** [comment]
```js
// vue.config.js
module.exports = {
  transpileDependencies: [
    /\bvue-echarts\b/,
    /\bresize-detector\b/
  ]
}
```

**Comment by GitHdu** [comment]
@Justineo 按照你的配置，我这边报这个错误
```
Error: webpack-internal:///./node_modules/core-js/modules/_is-object.js:5
  module.exports = function (it) {
                 ^
  TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
  - _is-object.js:5 Module.eval
    [.]/[core-js]/modules/_is-object.js:5:16

  - _is-object.js:8 eval
    [.]/[core-js]/modules/_is-object.js:8:30
```

**Comment by mitcns** [comment]
是有问题的，按照 git 文档的 vue-cli3 的配置，报错：
 Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by mitcns** [comment]
@GitHdu 
![image](https://user-images.githubusercontent.com/13047599/45082564-34f5c700-b12c-11e8-8846-632f6eced04f.png)

**Comment by rugged-service** [comment]
Had the same issue, wasn't able to render in IE 11 or Edge. Copy and pasted the responses from @GitHdu  and @Justineo with no luck. The read me file inside the vue node modules folder worked perfectly though. Looks exaclty the same:

`transpileDependencies: [
    /\bvue-echarts\b/,
    /\bresize-detector\b/
  ]`

**Comment by GitHdu** [comment]
@ghost
npm cache may cause it.You can try as follows:
```
1.rm -rf node_modules
2.npm cache clear --force
3.npm install
```
