### ISSUE TITLE
Chart options wouldn't be watched deeply no more in new version 3.1.0?

### ISSUE THREAD

**Issue by lqs469** [ecomfe/vue-echarts#274]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告
- [x] Maybe new feature?

## Not introduced by ECharts / 非 ECharts 本身问题

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
v3.1.0

## Reproduction link / 复现链接
https://codesandbox.io/s/nrk3298xz4
```
// Set `series[index].data` wouldn't be watched no more.
this.pie.series[0].data = data;
    
// Need to assign new object to provoke update
this.pie = Object.assign({}, this.pie);
```
Is this new feature? Or bug?

**Comment by Justineo** [comment]
Thanks. It's a bug and now fixed in `v3.1.1`.
