### ISSUE TITLE
为啥源码的 notMerge 默认设为 true

### ISSUE THREAD

**Issue by Yowi** [ecomfe/vue-echarts#277]
chart.setOption(this.manualOptions || this.options || {}, true)
or 
this.chart.setOption(this.options, true)

每次更新其它（即不是图表的）数据都会重新渲染图表，应该设为一个变量让用户自己设置，如

`<chart :notMerge="true" :lazyUpdate="true" :options="options" style="height: 800px;" />`

**Comment by Justineo** [comment]
不按模板填写的 issue 将被直接关闭，谢谢。
