### ISSUE TITLE
mergeOptions错误

### ISSUE THREAD

**Issue by owengaozhen** [ecomfe/vue-echarts#281]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

    "vue-echarts": "3.1.2",

## Reproduction link / 复现链接

```
 <chart ref="echart" auto-resize :options="chart" :style="{width:echartsStyle.width,height:echartsStyle.height}" />

```
```
//代码
//this.refs.echart为何是一个数组
    this.$refs.echart.mergeOptions(option)
```
![image](https://user-images.githubusercontent.com/8510542/45463748-1735ec80-b740-11e8-892b-82fb8edebad0.png)

```
//错误
vue.esm.js?22f2:591 [Vue warn]: Error in event handler for "click": "TypeError: this.obj.$refs.echart.mergeOptions is not a function"
```

**Comment by Justineo** [comment]
见 Vue.js [官方文档](https://cn.vuejs.org/v2/guide/components-edge-cases.html#%E8%AE%BF%E9%97%AE%E5%AD%90%E7%BB%84%E4%BB%B6%E5%AE%9E%E4%BE%8B%E6%88%96%E5%AD%90%E5%85%83%E7%B4%A0)：

> 当 `ref` 和 `v-for` 一起使用的时候，你得到的引用将会是一个包含了对应数据源的这些子组件的数组。
