### ISSUE TITLE
使用vue-cli 3.0 build 出现 css错误问题

### ISSUE THREAD

**Issue by rzp1** [ecomfe/vue-echarts#282]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

##### vue.config.js
`transpileDependencies: [
    /\bvue-echarts\b/,
    /\bresize-detector\b/
  ]`
##### components

![image](https://user-images.githubusercontent.com/43344910/45691318-f5e35f00-bb8a-11e8-9cf0-4f37d8006372.png)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

![image](https://user-images.githubusercontent.com/43344910/45691444-3cd15480-bb8b-11e8-8458-e9e5f337b785.png)

![image](https://user-images.githubusercontent.com/43344910/45691457-48248000-bb8b-11e8-9baa-4b8f1270089a.png)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
请提供最小重现的步骤，谢谢。

**Comment by rzp1** [comment]
就是引入 mom run build 就会出现这种问题

**Comment by Justineo** [comment]
不可以，你需要提供的是，从 @vue/cli 创建项目以后，仅引入 vue-echarts 时打包错误的步骤。

**Comment by rzp1** [comment]
是cli 3.0的问题  https://github.com/vuejs/vue-cli/issues/2488

**Comment by Justineo** [comment]
这是一个已经被修复了的问题，你升级 @vue/cli 应该就好了。

**Comment by rzp1** [comment]
谢谢
