### ISSUE TITLE
希望tooltip中可以支持展示Vue组件

### ISSUE THREAD

**Issue by qiangbro** [ecomfe/vue-echarts#283]
目前tooltip中仅支持基本的html，希望可以通过某种方式来展示含vue组件的tooltip，例如：tooltip展示另一个echart图表。

## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.1.2

**Comment by Justineo** [comment]
http://echarts.baidu.com/api.html#echartsInstance.convertToPixel

可以使用这个接口获取部件定位，自行实现。
