### ISSUE TITLE
"media" option isn't working

### ISSUE THREAD

**Issue by hemulin** [ecomfe/vue-echarts#284]
I've been using `vue-echarts` for several months now and I can't be happier. Really great work!

Currently experiencing display overlap issues on small screens, I'm trying to follow [this post](https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Responsive%20Mobile-End) on how to use media queries inside the options.

Sadly, `media` doesn't seem to be a valid key. Whenever I try to include a `media` key in options, the console shows this error:
```
Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at we (vue-echarts.js:1)
    at cartesian2d (vue-echarts.js:1)
    at getCoordSysDefineBySeries (vue-echarts.js:1)
    at Xy (vue-echarts.js:1)
    at i.getInitialData (vue-echarts.js:1)
    at init (vue-echarts.js:1)
    at i.<anonymous> (vue-echarts.js:1)
    at Array.forEach (<anonymous>)
    at a (vue-echarts.js:1)
    at i.<anonymous> (vue-echarts.js:1)
```

And of course, nothing is being rendered.

Example `media` to play with:
```
media: [{
        query: {
            maxWidth: 1500 // when container width is smaller than 1500
        },
        option: {
            legend: {
                orient: 'horizontal'
            }
        }
    },
    {
        query: {
            minWidth: 1501 // when container width is larger than 1501
        },
        option: {
            legend: {
                orient: 'vertical' // vertical layout
            }
        }
    }
]
```

**Comment by Justineo** [comment]
Please follow the issue template and provide a valid reproduction, thanks.

**Comment by hemulin** [comment]
@Justineo 
Could you please make your previous codesandbox operational so I can build on top of it and demonstrate the issue?
https://codesandbox.io/s/93lw3197m4

Thanks in advance.

**Comment by angelsunshuli** [comment]
Has the problem been solved？I had the same problem。
