### ISSUE TITLE
Is there contextmenu event 

### ISSUE THREAD

**Issue by salomezhang** [ecomfe/vue-echarts#285]
Feature request / 新特性需求
I find contextmenu exists from echarts doc,but not in vue-echarts

**Comment by Justineo** [comment]
> contextmenu exists from echarts doc

Where is it?

**Comment by Justineo** [comment]
And you can use [native event handlers](https://vuejs.org/v2/guide/components-custom-events.html#Binding-Native-Events-to-Components) to listen to `contextmenu` events.

**Comment by Justineo** [comment]
Never mind. I've added the missing `contextmenu` and `mousemove` event in `vue-echarts@3.1.3`. The documentation of ECharts had missed these two.

**Comment by akashpandey2193** [comment]
Can we have a example of how to actually use it I am able to trigger the event but want some practical example of how the context menu actually works?
