### ISSUE TITLE
webpack 4 npm run build 失败 UglifyJs，已经按文档改了babel-loader的配置

### ISSUE THREAD

**Issue by panhezeng** [ecomfe/vue-echarts#296]
生产配置
  optimization: {
    runtimeChunk: 'single',
    splitChunks: {
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all'
        }
      }
    },
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          compress: {
            warnings: false,
            drop_debugger: true,
            drop_console: true
          }
        },
        sourceMap: config.build.productionSourceMap,
        parallel: true
      }),
      new OptimizeCssAssetsPlugin({
        cssProcessorOptions: config.build.productionSourceMap
          ? {parser: safe, map: {inline: false}}
          : {parser: safe}
      }),
    ]
  }

ERROR in static/js/vendors.927ec459b81f0c63873d.js from UglifyJs
Unexpected token: name (raf) [static/js/vendors.927ec459b81f0c63873d.js:278737,4]

  Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cms@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cms@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
