### ISSUE TITLE
webpack 4 npm run build 失败 UglifyJs，已经按文档改了babel-loader的配置

### ISSUE THREAD

**Issue by panhezeng** [ecomfe/vue-echarts#298]
## The type of this issue / Issue 类型

- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

"version": "3.1.3",

## Reproduction link / 复现链接
codesandbox没法弄的生产配置编译bug，npm run build

现在项目仓库demo还是老版本webpack的，如果你升级到webpack 4应该就会出现这个问题。

生产配置
```
optimization: {
runtimeChunk: 'single',
splitChunks: {
cacheGroups: {
vendor: {
test: /[\/]node_modules[\/]/,
name: 'vendors',
chunks: 'all'
}
}
},
minimizer: [
new UglifyJsPlugin({
uglifyOptions: {
compress: {
warnings: false,
drop_debugger: true,
drop_console: true
}
},
sourceMap: config.build.productionSourceMap,
parallel: true
}),
new OptimizeCssAssetsPlugin({
cssProcessorOptions: config.build.productionSourceMap
? {parser: safe, map: {inline: false}}
: {parser: safe}
}),
]
}
```

报错信息
```
ERROR in static/js/vendors.927ec459b81f0c63873d.js from UglifyJs
Unexpected token: name (raf) [static/js/vendors.927ec459b81f0c63873d.js:278737,4]

Build failed with errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cms@1.0.0 build: node build/build.js
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cms@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Justineo** [comment]
这个问题是因为你 babel-loader 没有配置对，你贴的这些看不出问题的。

**Comment by panhezeng** [comment]
有什么不对，我用的就是readme的文档里面配置啊。
webpack 4模板用的是https://github.com/vuejs-templates/webpack/pull/1369

For **Vue CLI 2** with the `webpack` template, modify `build/webpack.base.conf.js` like this:

```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vue-echarts'),
          resolve('node_modules/resize-detector')
        ]
      }
```

**Comment by Justineo** [comment]
Vue CLI 2 的 webpack template 用的

**Comment by panhezeng** [comment]
Pulling 2.x Templates (Legacy)
Vue CLI 3 uses the same vue binary, so it overwrites Vue CLI 2 (vue-cli). If you still need the legacy vue init functionality, you can install a global bridge:
```
npm install -g @vue/cli-init
# vue init now works exactly the same as vue-cli@2.x
vue init noamkfir/webpack#webpack-4 project
```
vue cli 3也支持vue init webpack template方式创建项目啊
而且vue cli 和webpack模板使用webpack版本也没关系啊
现在的问题时，就算我不用vue cli，我自己用webpack 4和vue loader搭建一个vue项目，按需引用的方式使用vue-echarts就无法通过生成编译啊，但是dev编译是没有问题，你确认不是组件某部分代码的写法，无法通过webpack 4官方集成的UglifyJsPlugin的压缩？

**Comment by Justineo** [comment]
Vue CLI 3 的 init 命令只是到 2.x 版本的一个兼容，调用的就是老版本的功能。

**Comment by Justineo** [comment]
VueECharts 源码版本是未经 Babel 编译的，如果 build 时有问题，那就是对应文件没有过 babel-loader。dev 没问题是因为没有过 Uglify，你浏览器里直接跑的时候ESNext 代码。

**Comment by panhezeng** [comment]
用官方vue cli 3创建的项目可以按需使用，也不知自己直接用webpack4配置的那个地方有问题，哎，算了关闭吧。明明已经加了
```
{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vue-echarts'),
          resolve('node_modules/resize-detector')
        ]
 }
```
不知为何babel-loader没有转换，但是用element ui什么都是好的。
