### ISSUE TITLE
 图例的颜色在IE11中切换 The color of the chart legend is switched at IE11 

### ISSUE THREAD

**Issue by euledge** [ecomfe/vue-echarts#300]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
在IE 11上顯示vue-echarts的演示頁面並多次單擊屏幕上的刷新按鈕會導致圖表圖例的顏色被交換

Displaying the demo page of vue-echarts on IE 11 and clicking on the refresh button on the screen multiple times causes the color of the chart legend to be exchanged.

- 打开演示页后立即显示图像  
Image immediately after opening the demo page
![This image is initial demo page](https://gist.githubusercontent.com/euledge/64dac434440cf5437d3b3a372b17044d/raw/09046ac5723a80412359f21ed46189832e680785/Vue-ECharts-IE11-Initial.png)

- 单击刷新按钮几次后的图像  
Image after clicking the refresh button several times
![This image is ](https://gist.githubusercontent.com/euledge/64dac434440cf5437d3b3a372b17044d/raw/09046ac5723a80412359f21ed46189832e680785/Vue-ECharts-IE11-NG.png)
### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

3.1.3

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Ivorzk** [comment]
ie11 一片空白

**Comment by Justineo** [comment]
We stopped maintaining Vue ECharts version < 6. If there are still similar problems in v6, please open a new issue with runnable repro. Thank you.
