### ISSUE TITLE
Organization chart

### ISSUE THREAD

**Issue by verilog15** [ecomfe/vue-echarts#301]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
I was wondering if its possible to create an organization chart with this project?
Something similir to the following chart:
![image](https://user-images.githubusercontent.com/35470921/48478876-40412f00-e80e-11e8-95fb-197bd349782d.png)

If the answer is yes, where can I see an example or a demo?
Thank you

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

3.1.3

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
You can check out all supported chart types [here](https://ecomfe.github.io/echarts-examples/public/index.html). If the chart type you want is not supported, you can make a feature request to [ECharts](https://github.com/apache/incubator-echarts) itself.
