### ISSUE TITLE
添加事件注册服务

### ISSUE THREAD

**Issue by fallowu** [ecomfe/vue-echarts#302]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.9

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**
http://gallery.echartsjs.com/editor.html?c=xHyqn_rQ6g

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**
Echarts有georoam事件，vue-echarts没有提供，也没有注册事件接口，是否可以考虑添加事件注册接口?

**Comment by Justineo** [comment]
可以先使用组件实例上的 `chart` 对象（是一个 `echartsInstance`）来绑定未暴露的事件。目前 Vue-ECharts 只开放官方文档上公开的事件，暂时不会修改。

**Comment by zhubl** [comment]
您好 ， 请问是否能给个demo ……

**Comment by zhubl** [comment]
本不想做伸手党！ 我需要updateAxisPointer这个事件的支持。 我试着通过refs拿到chart对象，但是注册事件上去不起作用。。。对vue不熟，求大神指教。

**Comment by Justineo** [comment]
你可能需要用 `$refs.chart.chart` 来获取 ECharts 的实例（假设你模板里使用了 `ref="chart"`）。

**Comment by zhubl** [comment]
感谢您的回复，我确实是这样获取到chart实例的…… 我在eChart的父级组件的mounted()方法里这样写：
this.$refs.pandectGraphRef.chart.on('updateAxisPointer', this.fun) 但似乎起不到效果， 很奇怪的是， 因为我对vue不熟，所以不小心给this.$refs.pandectGraphRef.chart赋值成了undefined 。在这样的情况下 事件居然可以相应了，但是之前setOption配置的高度和宽度就失效了，而且让chart变成了undefined肯定也是不对的。。。 抱歉 完全前端新手 语言凌乱 给您添麻烦了。
