### ISSUE TITLE
请问Vue-echarts是否具有echarts的词云组件功能，如果有如何使用？

### ISSUE THREAD

**Issue by chaoranfeng** [ecomfe/vue-echarts#303]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.9

请问Vue-echarts是否具有echarts的词云组件功能，如果有如何使用？

**Comment by Justineo** [comment]
请仔细阅读 [README](https://github.com/ecomfe/vue-echarts/blob/master/README.zh_CN.md#%E7%94%A8-npm-%E4%B8%8E-vue-loader-%E5%9F%BA%E4%BA%8E-es-module-%E5%BC%95%E5%85%A5%E6%8E%A8%E8%8D%90%E7%94%A8%E6%B3%95)，谢谢。
