### ISSUE TITLE
style tags in example misleading

### ISSUE THREAD

**Issue by volkerjaenisch** [ecomfe/vue-echarts#311]
Please remove the inline <style> tags

<style>
.echarts {
  width: 100%;
  height: 100%;
}
</style>

in the example code.

If someone stupid like  me utilizes the code as a top level component he will see nothing since the top level component does not provide a defined width/heigth. The echart is there but not visible. 

Cheers,
Volker

**Comment by Justineo** [comment]
The percentage size is necessary for responsive charts. I added some comments to better describe this, and this should eliminate the confusing part. Thanks for the suggestion.
