### ISSUE TITLE
Chart title link with vue-router

### ISSUE THREAD

**Issue by tiagocoutinho** [ecomfe/vue-echarts#318]
## Chart title link with vue-router

This is more of a question than an issue.

I am using vue-echarts 4.0.1, echarts 4.1.0, vue-router 3.0.1.

I would like my chart title be a router link.
If I do this:

```Javascript
let options = {
  title: {
    text: 'My awesome vue-echarts demo',
    link: '/raw_data',
    target: 'self'
  }
}
```
The link works but it opens a new page instead of using the router.
It is possible to make the link use vue router instead?
Thanks in advance

**Comment by Justineo** [comment]
Please provide a reproduction link, thanks.

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.

--

PS. Please ensure the problem doesn't come from ECharts itself before submitting an issue here.
