### ISSUE TITLE
如何给tooltip formatter return dom节点绑定VUE事件

### ISSUE THREAD

**Issue by 531431988** [ecomfe/vue-echarts#320]
## The type of this issue / Issue 类型

-  Feature request / 新特性需求

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/52940125-bec6e300-33a0-11e9-95f2-2437574f4efd.png)
求指点

**Comment by Justineo** [comment]
这个 Vue 做不了，你可以通过事件代理的方式来搞，给容器绑上点击事件，然后在 `formatter` 返回的 HTML 元素上写一些 `data-*` 属性来传参数。

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/52981974-338c3280-341e-11e9-9e71-b76b75deecaa.png)
大佬我就想在这里加个事件，做一些其他的事情

**Comment by 531431988** [comment]
求个例子
