### ISSUE TITLE
How can I use echarts.getInstanceById?

### ISSUE THREAD

**Issue by moderatas** [ecomfe/vue-echarts#322]
## The type of this issue / Issue 类型

- [X] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.0.1

I would like to get a list of all charts inside a given element, get their Ids and force them to resize (I am using html2canvas, hence the need to force a resize prior to printing). As it seems, I cannot use getInstanceById, which would be certainly useful in this case.

Is there a different approach I could use?

**Comment by Justineo** [comment]
Have you tried setting the `autoresize` prop?

**Comment by moderatas** [comment]
> Have you tried setting the `autoresize` prop?

Yes, the autoresize prop usually works, but for this html2canvas routine, the chart does not seem to detect the need to resize

**Comment by Justineo** [comment]
You can use `ref` to get VueECharts instances and directly call the `resize` method on them.

**Comment by moderatas** [comment]
> 
> 
> You can use `ref` to get VueECharts instances and directly call the `resize` method on them.

The point is the number or charts being unknown, I do not have their refs.

**Comment by Justineo** [comment]
Why is that? You can always add a ref when you create a chart component.

**Comment by moderatas** [comment]
> 
> 
> Why is that? You can always add a ref when you create a chart component.

That's true, I could create unique refs and iterate among them, but I thought there should be a cleaner way.

**Comment by Justineo** [comment]
You can set the same `ref` value on all of them, eg. `'chart'`, then `this.$refs.chart` will be an array containing all chart component instances.
