### ISSUE TITLE
在IE11下折线图的markArea没生效

### ISSUE THREAD

**Issue by kiccer** [ecomfe/vue-echarts#324]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
`"echarts": "^4.1.0",`

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

项目需求是在折线图上，将0点至6点时间段内的背景变为深色，这里我使用markArea来实现，在最新版chrome及其他主流浏览器下都正确显示，但是在IE11中，除了markArea以外的其他内容都正常显示了，希望可以帮忙排查一下。

**Comment by Justineo** [comment]
> * 我已检查过，这个问题非 ECharts 本身的问题。

你是如何确认的呢？

**Comment by kiccer** [comment]
![QQ截图20190314155250](https://user-images.githubusercontent.com/23536402/54339964-471f6780-4671-11e9-9c83-fe62d82f711e.png)

这是在chrome中的效果，
![QQ截图20190314155302](https://user-images.githubusercontent.com/23536402/54339971-4be41b80-4671-11e9-9295-2c4c3964efa0.png)

这是IE11的

**Comment by Justineo** [comment]
请理解让你确认的问题……是说你怎么确认这个问题不是 ECharts 本身的，而是 Vue ECharts 的？

**Comment by kiccer** [comment]
emmm，我可能问错地方了，抱歉= =

**Comment by Justineo** [comment]
&rarr; https://github.com/apache/incubator-echarts
