### ISSUE TITLE
怎么使用下钻图

### ISSUE THREAD

**Issue by qianzhangsheng** [ecomfe/vue-echarts#325]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

https://gallery.echartsjs.com/editor.html?c=x1oy4wvUph

**Comment by qianzhangsheng** [comment]
官方的下钻图应该怎么样使用vue-echarts
https://gallery.echartsjs.com/editor.html?c=x1oy4wvUph

**Comment by Justineo** [comment]
按 ECharts 的需要设置 `option` prop 即可。

**Comment by qianzhangsheng** [comment]
$.get()加载.json地图需要怎么解决呀？

**Comment by Justineo** [comment]
这个和本项目和 ECharts 都无关了，你可以用任意方式加载 JSON 数据的。

**Comment by qianzhangsheng** [comment]
![Image of Yaktocat](https://image-static.segmentfault.com/298/289/2982894372-5c93100ce5114_articlex)
作者大神，现在又遇到一个异步加载的问题，页面刷新时候不会加载地图，只有改动以后例如把下面的console.log注释以后地图才出来，有办法解决吗？
https://codesandbox.io/s/qk03z953z4
