### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by GodStream** [ecomfe/vue-echarts#328]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
引入type为bar类型图表时，会报下面的错误
```
TypeError: Cannot read property 'get' of undefined
    at isCategory (referHelper.js?8b7f:159)
    at cartesian2d (referHelper.js?8b7f:100)
    at getCoordSysDefineBySeries (referHelper.js?8b7f:87)
    at createListFromArray (createListFromArray.js?3301:85)
    at ExtendedClass.getInitialData (BaseBarSeries.js?3014:46)
    at ExtendedClass.init (Series.js?4f85:131)
    at ExtendedClass.eval (Global.js?7e63:238)
    at Array.forEach (<anonymous>)
    at each (util.js?6d8b:298)
    at ExtendedClass.visitComponent (Global.js?7e63:212)
```
### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
vue-echarts: 4.0.1

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**
https://codesandbox.io/s/00oqjwr6ml?fontsize=14

**Comment by Justineo** [comment]
> 我已检查过，这个问题非 ECharts 本身的问题。

你明明没有检查过，直接使用 ECharts 会直接报同样的错误。

**Comment by GodStream** [comment]
确实没检查，我的失误。类型bar，必须声明`yAxis`，不然就会报错。

**Comment by FarkasAndras93** [comment]
In my case, I forgot to add yAxis value to my chart options.

**Comment by zhedream** [comment]
我也遇到了 echarts  'get' of undefined 的问题
检查发现是初始化 option 的错误
option = []; //  用数组是错误的
option = {}; // 应该用空对象

I also encountered the problem of ecarts' get 'of undefined
The check found an error initializing option
Option = []; / / it is wrong to use an array
Option = {}; / / an empty object should be used
