### ISSUE TITLE
关系图graph无法正确显示

### ISSUE THREAD

**Issue by ier005** [ecomfe/vue-echarts#330]
你好，
我想仿照[echarts官方示例](https://echarts.baidu.com/examples/editor.html?c=graph)，使用vue-charts在项目中展示关系图，但代码没有运行成功，报错显示：

```
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property '__focusNodeAdjacency' of undefined"


found in


---> <VChart> at ECharts.vue

       <App> at /src/App.vue

         <Root>
```

这是报错的[示例代码](https://codesandbox.io/s/4w6qmr2239)。
请问问题出在哪里，该如何才能够按照预期显示关系图表？

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
