### ISSUE TITLE
graph无法正常显示

### ISSUE THREAD

**Issue by ier005** [ecomfe/vue-echarts#331]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.0.1

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

你好，
我想仿照[echarts官方示例](https://echarts.baidu.com/examples/editor.html?c=graph)，使用vue-charts在项目中展示关系图，但代码没有运行成功，报错显示：

```
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property '__focusNodeAdjacency' of undefined"


found in


---> <VChart> at ECharts.vue

       <App> at /src/App.vue

         <Root>
```

直接引入echarts则能够正常运行，而使用vue-charts封装则无法正常显示，这是报错的[示例代码](https://codesandbox.io/s/4w6qmr2239)。
请问问题出在哪里，该如何才能够按照预期显示关系图表？

**Comment by Justineo** [comment]
你的 option 在 ECharts 里根本跑不起来……

> 我已检查过，这个问题非 ECharts 本身的问题。

没有试过请不要乱打勾。

**Comment by gold3bear** [comment]
遇到同样的问题，放弃治疗

**Comment by gold3bear** [comment]
调试了一下，引用官方库也会有同样的问题，需要把layout的值改成force。

> ## The type of this issue / Issue 类型
> * [ ]  Feature request / 新特性需求
> * [x]  Bug report / Bug 报告
> 
> ## Not introduced by ECharts / 非 ECharts 本身问题
> Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。
> 
> * [x]  I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。
> 
> ## Details / 详情
> ### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？
> * [x]  Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
> * [ ]  The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)
> 
> ### The version of Vue-ECharts you are using / Vue-ECharts 的版本
> 4.0.1
> 
> ## Reproduction link / 复现链接
> **For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**
> 
> **对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**
> 
> 你好，
> 我想仿照[echarts官方示例](https://echarts.baidu.com/examples/editor.html?c=graph)，使用vue-charts在项目中展示关系图，但代码没有运行成功，报错显示：
> 
> ```
> [Vue warn]: Error in mounted hook: "TypeError: Cannot read property '__focusNodeAdjacency' of undefined"
> 
> 
> found in
> 
> 
> ---> <VChart> at ECharts.vue
> 
>        <App> at /src/App.vue
> 
>          <Root>
> ```
> 
> 直接引入echarts则能够正常运行，而使用vue-charts封装则无法正常显示，这是报错的[示例代码](https://codesandbox.io/s/4w6qmr2239)。
> 请问问题出在哪里，该如何才能够按照预期显示关系图表？
