### ISSUE TITLE
请问是否考虑支持typescript?

### ISSUE THREAD

**Issue by SmileAjh** [ecomfe/vue-echarts#333]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by sashangli** [comment]
自己写个声明文件不就可以了，也就几行代码

**Comment by bluelovers** [comment]
不一樣 你說的大概只是讓 ts 不報錯
但這樣弄出來的聲明文件根本無法讓 ts 支援 判斷 api 那些

**Comment by ositowang** [comment]
这个库现在还在维护嘛

**Comment by bluelovers** [comment]
@ositowang https://github.com/ecomfe/vue-echarts/commits/master

**Comment by qianfangyuan** [comment]
这个问题现在fix了吗？

**Comment by Justineo** [comment]
`vue-echarts@6` is recently released. It's built upon ECharts 5 with full TypeScript support. Supports both Vue 2 and 3.
