### ISSUE TITLE
动态加载地图数据，然后注册地图，提示Cannot read property 'svg' of undefined

### ISSUE THREAD

**Issue by shimangdian** [ecomfe/vue-echarts#335]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

```
mapClick (obj) {
      let url = `/static/lib/map/json/${mapJson[obj.name]}`
      axios({
        url: url
      }).then(res => {
        this.ECharts.registerMap(obj.name, res.data)
      })
}

mapDataStorage.js?d0c3:66 Uncaught (in promise) TypeError: Cannot read property 'svg' of undefined
    at Object.registerMap (mapDataStorage.js?d0c3:66)
    at Object.registerMap (echarts.js?21c7:2158)
    at Object.registerMap (ECharts.vue?fe53:277)
    at eval (real-time-status-2.vue?cfc6:161)
```

**Comment by Justineo** [comment]
> **对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 CodeSandbox 上 demo 的链接：**

**Comment by LiPinghai** [comment]
@shimangdian 请问最后解决了吗？我也遇到同样问题

**Comment by guohuihot** [comment]
```
import('echarts/map/js/province/hubei')
                    .then((res) => {
                        this.province = '湖北'
                    })
```
```
 mapType: this.province || 'china', // 自定义扩展图表类型
```

**Comment by guohuihot** [comment]
有没有办法拿到已注册的map?
