### ISSUE TITLE
xy轴label过多时,其中一个不显示

### ISSUE THREAD

**Issue by pettything** [ecomfe/vue-echarts#336]
想让xy轴显示所有轴标签的内容,如果轴内容数量过长就会出现有一个不显示的情况.
图片如下:
![1](https://user-images.githubusercontent.com/41041117/55931657-fcd1dc00-5c58-11e9-9692-3461b6bf33ae.jpg)

代码如下:
`html
<template>
    <div class="testEchartsLine">
        <div id="myChartDiv"
             :style="myChartStyle"> </div>
    </div>
</template>

<script>
var echarts = require('echarts');
import shine from 'echarts/theme/shine.js';
var myChart;//echarts的定义变量
var myOption;//echarts的参数
var myOption = {
    yAxis: {
        type: 'category',
        axisLabel: {
            interval: 0,
            showMinLabel: true,
            showMaxLabel: true,
        },
        data: ["A50", "A49", "A48", "A47", "A46", "A45", "A44", "A43", "A42", "A41", "A40", "A39", "A38", "A37", "A36", "A35", "A34", "A33", "A32", "A31", "A30", "A29", "A28", "A27", "A26", "A25", "A24", "A23", "A22", "A21", "A20", "A19", "A18", "A17", "A16", "A15", "A14", "A13", "A12", "A11", "A10", "A9", "A8", "A7", "A6", "A5", "A4", "A3", "A2", "A1"],
    },
    xAxis: {
        type: 'category',
    },
};
export default {
    name: 'TestEchartsLine',
    data () {
        return {
            myChartStyle: {
                width: 'auto',
                height: '500px',
            },
        }
    },
    mounted () {
        myChart = echarts.init(document.getElementById('myChartDiv'), shine);
        myChart.setOption(myOption);
    },
    methods: {
    },
    components: {
    }
}
</script>
`

非vue-echarts的时候,测试了html情况下,情况正常

图片:
![2](https://user-images.githubusercontent.com/41041117/55931985-48d15080-5c5a-11e9-9eab-49615a424964.jpg)

代码:
` html

<html>
  <head>
    <script src="http://echarts.baidu.com/gallery/vendors/echarts/echarts.min.js"></script>
  </head>
  <body>
    <div id="container" style="width: 100%;height: 500px"></div>
    <script>
      var myChart = echarts.init(document.getElementById('container'))
      var option = {
    yAxis: {
        type: 'category',
        axisLabel: {
            interval: 0,
            showMinLabel: true,
            showMaxLabel: true,
        },
        data: ["A50", "A49", "A48", "A47", "A46", "A45", "A44", "A43", "A42", "A41", "A40", "A39", "A38", "A37", "A36", "A35", "A34", "A33", "A32", "A31", "A30", "A29", "A28", "A27", "A26", "A25", "A24", "A23", "A22", "A21", "A20", "A19", "A18", "A17", "A16", "A15", "A14", "A13", "A12", "A11", "A10", "A9", "A8", "A7", "A6", "A5", "A4", "A3", "A2", "A1"],
    },
    xAxis: {
        type: 'category',
    },
 
      }
      if (option && typeof option === 'object') {
        myChart.setOption(option, true)
      }
    </script>
  </body>
</html>
`

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
