### ISSUE TITLE
关于series设置color回调函数的问题

### ISSUE THREAD

**Issue by renmu123** [ecomfe/vue-echarts#337]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

[复现链接](https://codesandbox.io/s/vue)

## 代码
```
option = {
        legend: {},
        tooltip: {},
        trueData: [
          ["循环任务1", 20, 5, 20, 15, 25],
          ["循环任务2", 5, 20, 20, 5],
          ["循环任务3", 5, 25],
          ["循环任务4", 10, 20, 5, 25, 10]
        ],
        dataset: {
          source: [
            ["循环任务1", 1, 1, 1, 1, 1],
            ["循环任务2", 1, 1, 1, 1],
            ["循环任务3", 1, 1],
            ["循环任务4", 1, 1, 1, 1, 1]
          ]
        },
        xAxis: {},
        yAxis: { type: "category" },
        // Declare several bar series, each will be mapped
        // to a column of dataset.source by default.
        series: [
          {
            type: "bar",
            stack: "总量",
            color: function(params) {
              //   console.log(params);
              console.log(this.option.trueData);
              return 4 >= 3 ? "green" : "red";
            }
          },
          { type: "bar", stack: "总量" },
          { type: "bar", stack: "总量" },
          { type: "bar", stack: "总量" },
          { type: "bar", stack: "总量" }
        ]
};
```

## 我的
[echarts编辑器链接](https://www.echartsjs.com/gallery/editor.html)
将上述代码输入到上诉编辑器中，控制台正常展示信息。
而在`vue`环境中，控制台报错。`[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'trueData' of undefined"`
**也有可能因为我是前端菜鸟，对 `Vue` 理解不深，敬请指教**

**Comment by Justineo** [comment]
`console.log(this.option.trueData);`

`option` 不存在吧。

**Comment by renmu123** [comment]
复现链接好像错了。。。。补一个：https://codesandbox.io/embed/245p3535jp
在`HelloWord.vue`可以看一下

**Comment by Justineo** [comment]
```js
            color: function(params) {
              //   console.log(params);
              console.log(this.aa);
              console.log(this.option.trueData);
              return 4 >= 3 ? "green" : "red";
            }
```

这个 `this` 不是组件实例，具体可以了解一下 `this` 的绑定规则。

**Comment by renmu123** [comment]
感谢你的帮助，我使用箭头函数解决了
