### ISSUE TITLE
一些 Echarts wrapper 问题

### ISSUE THREAD

**Issue by kazehaiya** [ecomfe/vue-echarts#338]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### 1. create 方法中的对 options 的 watch 方法（第 226 行）
假如最开始时 manualUpdate 为 true，那么之后手动改后就无法触发 options 的监听了，因为不会再触发一次 create 方法

### 2. 关于 notMerge 的问题（第 238 行）
!== 无法深度比较对象的不同，这里的 val !== oldVal 一直会被设定为 true，也就是说，其实这并不能动态支持 notMerge 动态改变

>  （ReadMe）如果直接修改 options 绑定的数据而对象引用保持不变，setOption 方法调用时将带有参数 notMerge: false。否则，如果为 options 绑定一个新的对象，setOption 方法调用时则将带有参数 notMerge: true。

例如，如果有如下模板：

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

希望官方能够维护

**Comment by Justineo** [comment]
1. 可以算是一个 bug，但是我要考虑一下是否需要动态切换 `manual-update`。
2. Object 的内容变化时 `val` 和 `oldVal` 是相同的。注释里的例子已经写了。
