### ISSUE TITLE
关于series中markLine不显示，需要echarts/map/js/world组件

### ISSUE THREAD

**Issue by zwtgit** [ecomfe/vue-echarts#339]
## 版本4.0.1最新版配置markLine不显示
![image](https://user-images.githubusercontent.com/22927679/56857884-256e0b80-69a5-11e9-9e4f-8e40d18c55c1.png)
## 组件引入齐全
![image](https://user-images.githubusercontent.com/22927679/56857908-564e4080-69a5-11e9-92cb-d73d864f4337.png)
![image](https://user-images.githubusercontent.com/22927679/56857897-46cef780-69a5-11e9-9978-bde249701ba2.png)
## 引入world组件（world不是世界地图组件吗）
![image](https://user-images.githubusercontent.com/22927679/56857916-6a923d80-69a5-11e9-98a2-108c32728f35.png)
![image](https://user-images.githubusercontent.com/22927679/56857925-7da50d80-69a5-11e9-975e-0007bdcccb70.png)

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [✔ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ✔] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。

---

请提供可运行的复现，并且确认你的配置在仅使用 ECharts 本身时没有此问题。

**Comment by hcen1997** [comment]
import ECharts from 'vue-echarts' 
import 'echarts/map/js/world'
Vue.component('v-chart', ECharts)


"echarts": "^4.3.0","echarts-stat": "^1.1.1","vue-echarts": "^4.0.4",

也是必须引用一下world才能显示
