### ISSUE TITLE
tree图表开启expandAndCollapse点击时，旧的分支图没有擦除

### ISSUE THREAD

**Issue by CatWithWings** [ecomfe/vue-echarts#341]
## The type of this issue / Issue 类型
- [ ] Bug report / Bug 报告

## Details / 详情
tree图表开启expandAndCollapse的时候，点击节点显示隐藏分支，以前渲染的分支图没有
被擦除，导致画布上出现新老分支同时存在，但是echarts本身并没此类问题。

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。

--

请不要把必要信息的模板删除。如果 ECharts 本身没有问题，最好在 [ECharts Gallery](https://gallery.echartsjs.com/editor.html) 上新建一个相同配置的 demo。
