### ISSUE TITLE
Adding datazoom destroys graph

### ISSUE THREAD

**Issue by focussing** [ecomfe/vue-echarts#343]
I created a little test:
<img width="789" alt="Schermafbeelding 2019-05-16 om 14 47 50" src="https://user-images.githubusercontent.com/26736152/57855150-4bd7d780-77ea-11e9-9c00-a2e3b980c331.png">

When I press "Add data" button the following is shown:
<img width="829" alt="Schermafbeelding 2019-05-16 om 14 48 00" src="https://user-images.githubusercontent.com/26736152/57855188-5c884d80-77ea-11e9-8d4c-dfcfc6daa4f0.png">

Then I press "Add zoom" button, nothing happens.
When I press "Add data" again this is shown:
<img width="825" alt="Schermafbeelding 2019-05-16 om 14 48 11" src="https://user-images.githubusercontent.com/26736152/57855247-7cb80c80-77ea-11e9-8831-092a45416f5b.png">

So basically the datazoom is added, but the graph is gone....

This is how I use the chart in the html part of the template.
`<v-chart :options="chartOptionsLine"/>`

```
chartOptionsLine: {
	xAxis: {
		data: []
	},
	yAxis: {
		type: 'value'
	},
	series: [
		{
			type: 'line',
			data: [1, 2, 5, 4, 5]
		}
	],
	title: {
		text: 'demo',
		x: 'center',
		textStyle: {
			fontSize: 24
		}
	},
	color: ['#127ac2'],
},
```
```
addZoom: function(e) {
	// add zoom
	this.chartOptionsLine.dataZoom = [
		{
			type: 'slider',
			xAxisIndex: 0,
			start: 10,
			end: 60
		},
		{
			type: 'inside',
			xAxisIndex: 0,
			start: 10,
			end: 60
		},
		{
			type: 'slider',
			yAxisIndex: 0,
			start: 30,
			end: 80
		},
		{
			type: 'inside',
			yAxisIndex: 0,
			start: 30,
			end: 80
		}
	];
},
```

What am I doing wrong?

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.

**Comment by Justineo** [comment]
PS. It seems that you need to read this: https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by focussing** [comment]
That has nothing to do with it.
```
				xAxis: {
					type: 'category'
				},
```
In combination with an xAxis data array does the job.

<img width="812" alt="Schermafbeelding 2019-05-16 om 16 16 24" src="https://user-images.githubusercontent.com/26736152/57860915-fbff0d80-77f5-11e9-95c7-8e2057d81420.png">


The only issue right now is how to remove the datazoom. Tried different options...
```
		removeZoom: function(e) {
			// remove zoom
			this.chartOptionsLine.dataZoom = null; // or undefined
		}
```

**Comment by Justineo** [comment]
If you are reporting a bug, please do provide a valid reprodction. Thanks.
