### ISSUE TITLE
3.x版本属性是auto-size，4.x版本变成了autoresize。中间的小横跨去掉了，为什么要这样子做呢？

### ISSUE THREAD

**Issue by nqdy666** [ecomfe/vue-echarts#347]
## Not introduced by ECharts / 非 ECharts 本身问题

是

## Details / 详情

3.x版本属性是auto-size，4.x版本变成了autoresize。中间的小横跨去掉了。这样导致3升级到4无法顺滑升级，为什么要这样子做呢？

## Reproduction link / 复现链接

https://github.com/ecomfe/vue-echarts/commit/d466b792731bd7db60ae62013958c83c5fdb5998

**Comment by Justineo** [comment]
就是因为有 breaking change，才升主版本号的。请注意大版本号的语义就是不能确保无缝升级。

---

`auto-` 前缀的英文单词应该是一个词，不需要 `-` 连接，所以 `auto-resize` 的写法不准确。

**Comment by nqdy666** [comment]
这样子，不过感觉四个break change 中这个点影响最大了。其他三个breack change脚手架改一下就好，这个就要直接改现有业务代码了。如果能做兼容就好了，如果不能也建议把readme强调说明一下autoresize。用户很容易在升级的时候而忽视了autoresize属性的修改。

**Comment by nqdy666** [comment]
![image](https://user-images.githubusercontent.com/5211893/58247372-14d66880-7d8c-11e9-87a5-f30240289dc4.png)

**Comment by Justineo** [comment]
cSpell 不会也没办法提前把合成词都加入词库。你可以设置：

```js
{
  "cSpell.allowCompoundWords": true
}
```

**Comment by nqdy666** [comment]
好的
