### ISSUE TITLE
Uncaught ReferenceError: vue is not defined

### ISSUE THREAD

**Issue by havefive** [ecomfe/vue-echarts#352]
## 
- [ ] Bug report / Bug 报告
Vue-cli 3.8.0使用cdn引入
Include echarts and vue-echarts in your HTML file like this:

<script src="https://cdn.jsdelivr.net/npm/echarts@4.1.0/dist/echarts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-echarts@4.0.2"></script>
npm run build 之后，打开页面报错

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
