### ISSUE TITLE
[Bug report]缩放窗口后legend选项被重置

### ISSUE THREAD

**Issue by liwenda122** [ecomfe/vue-echarts#353]
## The type of this issue / Issue 类型
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题
- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
1.使用柱状图或者折线图，并启用legend选型
2.点击legend色块，并去掉若干items
3.缩小窗口大小（使legend出现换行）
4.缩放窗口后legend选项被重置，本来已经被禁用的items又重新被选中了
### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.0.7

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
请提供可以运行的复现，谢谢。

**Comment by superchangme** [comment]
确实是这样的，我们简单的给echart加一个display:none样式后，再去掉该样式，就会发现组件自作聪明的重新赋值了options，legend自选的效果已丢失

**Comment by superchangme** [comment]
// 修改vue-charts内部计算元素大小方法，避免离开页面进入重置属性逻辑
ECharts.methods.getArea = () => {
  return 1
}
作者可能比较忙，楼主我已解决，请参考！

**Comment by Justineo** [comment]
从隐藏状态展现后默认先渲染一次，是为了让图表有初始的尺寸，否则初次渲染时整个图表内容尺寸会从 0 一直变化到容器尺寸，效果有点奇怪。这个逻辑只在图表从不可见变为可见时存在，仅仅普通响应外部容器尺寸变化时是没有的。

**Comment by superchangme** [comment]
> 从隐藏状态展现后默认先渲染一次，是为了让图表有初始的尺寸，否则初次渲染时整个图表内容尺寸会从 0 一直变化到容器尺寸，效果有点奇怪。这个逻辑只在图表从不可见变为可见时存在，仅仅普通响应外部容器尺寸变化时是没有的。
是的，主要是路由切换离开了页面，但页面是keep-alive，回来看到页面其他元素都是正常的，只有图表这个被重置了，而且我试了我的这个方案，不会看到你说的从0到容器尺寸变化过程，想必是echart的resize方法响应已经足够快了。

**Comment by Justineo** [comment]
开了动画会有的。

**Comment by superchangme** [comment]
我尝试升级了最新4.0.3版本，发现宽高设置都失效了，直接缩小成100px了，是什么原因呢？

**Comment by superchangme** [comment]
找到原因了，3.x版本自动适应属性autoResize，4.x改成autoresize小写了，这是故意的还是无意的呢？

**Comment by Justineo** [comment]
`auto-` 前缀的词应该是一个单词，所以修改了。（升级大版本请提前阅读 CHANGELOG，特别注意 breaking change）。

**Comment by superchangme** [comment]
> `auto-` 前缀的词应该是一个单词，所以修改了。（升级大版本请提前阅读 CHANGELOG，特别注意 breaking change）。

than you very much

**Comment by Justineo** [comment]
We are closing this, unless a runnable reproduction is provided.
