### ISSUE TITLE
Would you mind document better the config options?

### ISSUE THREAD

**Issue by dvago** [ecomfe/vue-echarts#354]
Reading through the documentation is not clear how to set up properly a chart, setting up the renderer or even define the width/height.

I've discovered via the formatted version of your bundled examples that in order to set up the renderer to be SVG I just need to add:
```
initOptions {
    renderer: 'svg'
}
```

Would it be possible to review your documentation of the options and give to the users an understandable list of options available to set up and customise a chart please?

## The type of this issue / Issue 类型

- [X] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [X] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.0.3

**Comment by elevenkey** [comment]
@dvago please check https://echarts.apache.org/zh/api.html#echarts

**Comment by dvago** [comment]
> @dvago please check https://echarts.apache.org/zh/api.html#echarts

thanks for this
