### ISSUE TITLE
Responsive SVG rendered charts 

### ISSUE THREAD

**Issue by dvago** [ecomfe/vue-echarts#355]
Given the charts generated as SVG, could it be possible to clean up the rendered html?

In order to render the chart in a responsive way the generated `DIV` which wraps the `SVG` tag could be completely removed and the SVG tag could have the `width` and `height` attributes replaced by the `viewBox`
 
Eg. given width and height from the initOptions instead of printing out:
width="250" height="70" the output could be viewBox="0 0 250 70" so the developer/user could define via CSS the wanted sizing

ref.
<img width="902" alt="Screenshot 2019-06-24 at 13 41 11" src="https://user-images.githubusercontent.com/5074033/60019519-f6fb6c80-9685-11e9-87a2-764e7135e92c.png">

## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.0.3

**Comment by Justineo** [comment]
The rendering process is done entirely inside ECharts itself so this Vue.js wrapper component can't do anything about it. Please open an issue at [apache/incubator-echarts](https://github.com/apache/incubator-echarts).
