### ISSUE TITLE
当x轴只有一个标签时，标签不显示

### ISSUE THREAD

**Issue by AlvinNiu** [ecomfe/vue-echarts#356]
## The type of this issue / Issue 类型
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题
- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。
- 同一个option放在echarts官网是有显示的

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
- 4.0.3

## Reproduction link / 复现链接

链接如下：
[点击跳转，在页面最下方](https://datahub.ipreon.com/viewer/2010017415/?year=2018&period=FY)

配置如下：
option ={
  "dataset": [
    {
      "sourceHeader": false,
      "dimensions": [
        "time",
        "id",
        "total_rev",
        "gross_profit",
        "ebit",
        "net_profit_in"
      ],
      "source": [
        [
          "LTM",
          "",
          514932358.09,
          280613074.95,
          142959719.41,
          96829517.51
        ]
      ],
      "company_id": ""
    }
  ],
  "xAxis": {
    "type": "category",
    "axisLabel": {
      "show": true,
      "color": "#2a2b2b"
    },
    "data": [
      "LTM"
    ]
  },
  "yAxis": [
    {
      "id": "million",
      "type": "value",
      "nameTextStyle": {
        "color": "#bbb"
      },
      "scale": false,
      "offset": 0,
      "axisLabel": {},
      "splitLine": {
        "show": true
      }
    }
  ],
  "series": [
    {
      "type": "bar",
      "name": "total_rev-",
      "yAxisIndex": 0,
      "datasetIndex": 0,
      "barGap": 0,
      "encode": {
        "y": "total_rev"
      },
      "emphasis": {
        "itemStyle": {
          "borderWidth": 10
        }
      },
      "label": {
        "show": false
      }
    },
    {
      "type": "bar",
      "name": "gross_profit-",
      "yAxisIndex": 0,
      "datasetIndex": 0,
      "barGap": 0,
      "encode": {
        "y": "gross_profit"
      },
      "emphasis": {
        "itemStyle": {
          "borderWidth": 10
        }
      },
      "label": {
        "show": false
      }
    },
    {
      "type": "bar",
      "name": "ebit-",
      "yAxisIndex": 0,
      "datasetIndex": 0,
      "barGap": 0,
      "encode": {
        "y": "ebit"
      },
      "emphasis": {
        "itemStyle": {
          "borderWidth": 10
        }
      },
      "label": {
        "show": false
      }
    },
    {
      "type": "bar",
      "name": "net_profit_in-",
      "yAxisIndex": 0,
      "datasetIndex": 0,
      "barGap": 0,
      "encode": {
        "y": "net_profit_in"
      },
      "emphasis": {
        "itemStyle": {
          "borderWidth": 10
        }
      },
      "label": {
        "show": false
      }
    }
  ],
  "grid": {
    "top": 40,
    "bottom": 60,
    "left": 94,
    "right": 35
  }
}

**Comment by Justineo** [comment]
请给出最小化的复现而非完整的产品页面，谢谢。

**Comment by AlvinNiu** [comment]
找到问题所在了：因为在初始化是对主题做了更改其中有个配置如下
```
axisLabel: {
        // color: 'rgba(0,0,0,.65)',
        showMinLabel: true,
        showMaxLabel: true,
    },
```
在最大标签与最小标签同时设置时，x轴只有一个时，会不显示标签。

我当时只是把我的options复制到echarts上面发现没有问题，以为是组件的问题，非常抱歉！！！
感谢您的回复！！！非常感谢
