### ISSUE TITLE
How to set display specific value as: 00:00, 01:00, 02:00, etc in x axis?

### ISSUE THREAD

**Issue by CuongStf** [ecomfe/vue-echarts#360]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

Link example: [https://echarts.apache.org/examples/en/editor.html?c=bar-large](url)
Link image: 
<img width="1138" alt="Screen Shot 2019-07-10 at 11 20 45 AM" src="https://user-images.githubusercontent.com/33604446/60951434-5367b880-a323-11e9-87b4-50a6bb8ce795.png">

How to config specific number in xAxis: 00:00, 01:00,..etc?

**Comment by Justineo** [comment]
This project is only a Vue.js wrapper for ECharts. For feature requests of ECharts itself, please go to https://github.com/apache/incubator-echarts. Thanks.
