### ISSUE TITLE
Candlestick chart disappear after reloading the page.

### ISSUE THREAD

**Issue by theshashiverma** [ecomfe/vue-echarts#361]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [yes] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ yes] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
"vue-echarts": "^4.0.3"

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

I added the candlestick vue- echarts from this link https://github.com/xlsdg/vue-echarts-v3/issues/28

When I first start the project by hitting the root path and I go the page where I have candlestick chart, It will show the chart but if I reload this page where I have the candlestick chart, the chart disappears. I don't know how this is happening. When I check the source code the automaticaly generated canvas tag gets disappear.

**Comment by Justineo** [comment]
Please provide a runnable reproduction. The link you provided belongs to another project...

**Comment by theshashiverma** [comment]
I did not get any reference of candlestick chart from this https://ecomfe.github.io/vue-echarts/demo/ so found that candlestick chart on google and used it, It works fine in my few vuejs project but not this time.
Please let me know how can I add candlestick chart using your library and what is wrong with the code which I am using now?

**Comment by theshashiverma** [comment]
Ok, can you tell me how to add candlestick chart with this library?

**Comment by Justineo** [comment]
See option reference of ECharts: https://echarts.apache.org/option.html

**Comment by theshashiverma** [comment]
@Justineo I added candlestick chart with your library too, but it still disappears after hard reload, any solution please.
