### ISSUE TITLE
关于dataZoom在数据更新后被初始化位置的问题

### ISSUE THREAD

**Issue by PULIFAN** [ecomfe/vue-echarts#364]
## 期望
dataZoom在数据更新后位置不初始化，依然能够停留在刷新前的位置。

## 尝试
用过inside设置 取消slider没啥用。
dataZoom中的start和end没变。好像直接设置没得用
 this.chart.getOption('start')这个方法好像没得 所以不知道能不能这样获取到真实的dataZoom位置数据之后通过mergeOptions方法写入之类的

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
