### ISSUE TITLE
关于刷新数据后dataZoom位置不会停留在当前位置的问题

### ISSUE THREAD

**Issue by PULIFAN** [ecomfe/vue-echarts#365]
## Not introduced by ECharts / 非 ECharts 本身问题
- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
用过inside设置 取消slider没啥用。
dataZoom中的start和end没变。好像直接设置没得用
 this.chart.getOption('start')这个方法好像没得 所以不知道能不能这样获取到真实的dataZoom位置数据之后通过mergeOptions方法写入之类的

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？
通过npm install 后import引入

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
vue-echarts版本3.07

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**
链接：
https://codesandbox.io/embed/vue-template-dxy92

**Comment by Justineo** [comment]
> https://codesandbox.io/embed/vue-template-dxy92

里面好像数据量太大了导致浏览器直接卡死了。请你精简一下代码，给出最小的复现。另外，最好在 ECharts 的 gallery 给出一个示例，来证明这个问题不是 ECharts 本身的问题。

**Comment by PULIFAN** [comment]
我的问题对api不太熟悉，通过使用mergeOptions传需要改变的参数来解决了问题 ，耽误你时间了谢谢回复  你的建议很有参考性 以后提issues我会参考你的建议的   :P
