### ISSUE TITLE
想问一下在调用事件得时候，如何放入echart的一些参数

### ISSUE THREAD

**Issue by supercrow** [ecomfe/vue-echarts#369]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ yes] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

就是例如echart的click(params),使用vue-echarts不知道这个params该写什么值，或者我可以如何获得echart实例去绑定事件？

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

4.0.3

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by supercrow** [comment]
就是例如echart的click(params),使用vue-echarts不知道这个params该写什么值，或者我可以如何获得echart实例去绑定事件？

**Comment by Justineo** [comment]
使用方法和普通事件是一样的。`params` 是 ECharts 给回调函数传的参数。

https://echarts.baidu.com/api.html#events
