### ISSUE TITLE
热力图heatmap的yAxis使用splitLine无效，但是xAxis使用splitLine是有效的

### ISSUE THREAD

**Issue by YoYoLady** [ecomfe/vue-echarts#371]
`xAxis: {
        type: 'category',
        position: 'top', // X轴固定在顶部
        data: ['大学1', '大学2', '大学3'],
        splitArea: {
            show: true,
            areaStyle: {
                color: '#fff'
            }
        },
        axisLabel:{
            marginBottom:10,
            textStyle:{
                color:'#171819',
                fontSize:13,
            }
        },
        axisLine:{
            lineStyle:{
                color:'#fff',
                width:1,//这里是为了突出显示加上的
            }
        },
        splitLine: {
            show: true,
            lineStyle: {
                // 使用深浅的间隔色
                color: '#E5E5E5',
                width: 1
            }
        },
        axisTick:{
            length:0,
        }
    },
    yAxis: {
        type: 'category',
        inverse:true, // Y轴反向        
        axisLabel:{
            marginRight:10,
            textStyle:{
                color:'#171819',
                fontSize:14,
            },
        },
        splitLine:{
            show: true,
            lineStyle:{
                color: '#E5E5E5',
                width: 1
            }
        },
        axisLine:{
            lineStyle:{
                color:'#fff',
                width:1,//这里是为了突出显示加上的
            }
        },
        data: ['人才1', '人才2', '人才3'],
        splitArea: {
            show: true,
            areaStyle: {
                color: '#fff'
            }
        },
        axisTick:{
            length:0
        }
    },
    visualMap: {
        min: 0,
        max: 10,
        show: false,
        calculable: false,
        orient: 'horizontal',
        left: 'center',
        bottom: '0',
        inRange: {
            // color: ['#c9d7ff', '#96B3FE', '#5884FD'] // #c9d7ff ecf0ff
            color: ['#3B65D8', '#E8F0FF']
        }
    },`

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
