### ISSUE TITLE
How do I know if I need a certain imports?

### ISSUE THREAD

**Issue by jippy89** [ecomfe/vue-echarts#372]
Could you please elaborate this in the documentation? I know how to import usual chart like Line and Bar, however I had no idea how to import some other things that I need. Like for example, what components do I need for a Stack Bar Chart? Of course a Bar, then what?

Any reference would be nice. Thank you.

## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.2.1

**Comment by jippy89** [comment]
Nevermind, I've found out how to use stackbar, I just did it the wrong way. But I still want to know the answer for this tho', thank you.

**Comment by Justineo** [comment]
Maybe the best way is to let ECharts team find a better way to help users identify which modules are needed.
