### ISSUE TITLE
How to setup English language as default?

### ISSUE THREAD

**Issue by jippy89** [ecomfe/vue-echarts#373]
## The type of this issue / Issue 类型
I want to use Echart and English as its default language. I've seen that people already make it on [this issue](https://github.com/apache/incubator-echarts/issues/2321), I tried tweaking the code, but it seems that I had struggle using it, are there anyway to to this on `vue-echarts`? 

It seems that `echarts` already has some codes prepared for those inside `echarts/lib/` as well

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.2.1

**Comment by Justineo** [comment]
I don't think you should make such feature request to this repo. This is only a Vue component wrapper for ECharts and `echarts` is marked as a peer dependency. And I also didn't quite get your point, which part of ECharts is now in Chinese?

**Comment by jippy89** [comment]
@Justineo 
> And I also didn't quite get your point, which part of ECharts is now in Chinese?

The toolbox, especially in 'Data View',
![data view](https://i.stack.imgur.com/KfEf7.png)

Sorry, if I was wrong by issuing this here, I just see that `echarts` seems to be available in English, if I checked their source code both in `echarts/dist` as `echarts-en.*.js` and `echarts/lib` as `langEN.js`(?)

I just thought that maybe you could give an example on how to use that version instead of the default one `echarts/lib/echarts`. But if this is issue is wrong then it's fine. Thank you for your great work. :)

**Comment by keahie** [comment]
Yeah. It would be really helpful if you can give an example @jippy89

**Comment by keahie** [comment]
@WitgamWogar I found a workaround. You can set the title for the toolbox items manual. Here an example:
```
toolbox: {
  show: true,
  feature: {
      mark: { show: true },
      magicType: { show: true, type: ["line", "bar"], title: {
        line: "Line",
        bar: "Bar",
      }
    },
    restore: { show: true, title: "Reset" },
    saveAsImage: { show: true, title: "Save as Image" }
  }
}
```

**Comment by mlt** [comment]
You can mess with require's cache to force English into *lang* module export.
```js
require("echarts/lib/lang");
require.cache[require.resolve('echarts/lib/lang')].exports = require("echarts/lib/langEN");
echarts = require('echarts');
...
```

**Comment by juicycool92** [comment]
> @WitgamWogar I found a workaround. You can set the title for the toolbox items manual. Here an example:
> 
> ```
> toolbox: {
>   show: true,
>   feature: {
>       mark: { show: true },
>       magicType: { show: true, type: ["line", "bar"], title: {
>         line: "Line",
>         bar: "Bar",
>       }
>     },
>     restore: { show: true, title: "Reset" },
>     saveAsImage: { show: true, title: "Save as Image" }
>   }
> }
> ```

you save my day sir
