### ISSUE TITLE
CandleStick Chart is not rendering on reloading the page?

### ISSUE THREAD

**Issue by Sukhpall-Singh** [ecomfe/vue-echarts#374]
Hello , I am integrating the candle stick chart with this library in my vuejs project. First time, when I redirect to the page it works perfectly but when I reload the page it shows error and chart disappears. Please see the code in below codesandbox link. My project has implemented with Vue CLI-3. 

### These are the below versions in my project. 

Vue Version: 2.6.10
echarts: 4.2.1
vue-echarts: 4.0.3 

 **Demo Here**
Here is my code [CodeSandbox](https://codesandbox.io/s/vue-template-516m8?fontsize=14)

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.

**Comment by Sukhpall-Singh** [comment]
I have updated the issue. Please check now.
