### ISSUE TITLE
CandleStick Chart is not working on reloading the page?

### ISSUE THREAD

**Issue by Sukhpall-Singh** [ecomfe/vue-echarts#375]
Hello , I am integrating the candle stick chart with this library in my vuejs project. First time, when I redirect to the page it works perfectly but when I reload the page it shows error and chart disappears. Please see the code in below codesandbox link. My project has implemented with Vue CLI-3. 

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

vue-echarts: 4.0.3 

## Reproduction link / 复现链接

**Here is demo [CodeSandbox](https://codesandbox.io/s/vue-template-516m8?fontsize=14) **

**Comment by Justineo** [comment]
Add missing components and it will work:

https://codesandbox.io/s/vue-template-2bmdv

**Comment by Sukhpall-Singh** [comment]
Thanks a lot @Justineo its successfully works :) .
