### ISSUE TITLE
按照教程配置后依然无法工作在IE浏览器上

### ISSUE THREAD

**Issue by GEOHOTIOS** [ecomfe/vue-echarts#378]
在程序任何位置引用 import ECharts from 'vue-echarts/components/ECharts';
IE控制台就会爆 SCRIPT1006: 缺少 ')'；
程序已经 import 'babel-polyfill';

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ * ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ * ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ * ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
"vue-echarts": "^3.1.3",
 {
        test: /\.js$/,
        loader: 'babel-loader',
        // include: [
        // resolve('src'), resolve('test'),
        // resolve('node_modules/webpack-dev-server/client'),
        // resolve('node_modules/vue-echarts'),
        // resolve('node_modules/resize-detector')],
        include: [
          resolve('src'),
          resolve('test'),
          resolve('node_modules/vue-echarts'),
          resolve('node_modules/resize-detector')
        ]
      },

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
如果是在 Windows 下编译，请注意将路径分隔符从 `/` 调整到 `\\`。
