### ISSUE TITLE
Browser capability: getGradient not working on IE

### ISSUE THREAD

**Issue by wwwtony5488** [ecomfe/vue-echarts#379]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

Hi, I got a problem.
if `:option` in `<e-chart>` contains key like 
```
     itemStyle: {
        normal: {
           color: {
             type: 'linear',
             x: 0, y: 0, x2: 0, y2: 1,
             colorStops: [{ offset: 0, color: 'red' }, { offset: 1, color: 'blue' }],
           },
        },
      },
```
IE browser catch exception since `canvasGradient is undefined` in `function getGradient() {...}`
but if set `itemStyle` as ` { normal: { color: 'red' } }`, there will be no problem

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

"vue-echarts": "^4.0.3",

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
If this works in ECharts, it will work in VueECharts. 

> * [x]  I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

Can you describe how did you check this?

**Comment by wwwtony5488** [comment]
I went over some issues on ECharts, and those code contain  `colorStops: [{ offset: 0, color: '...' }, { offset: 1, color: '...' }] ` and work on IE11, but related to others bug.

as below
https://github.com/apache/incubator-echarts/issues/6069

**Comment by Justineo** [comment]
Please try at https://gallery.echartsjs.com/editor.html first to see if it works in ECharts and then provide a reproduction that shows it doesn't work in Vue-ECharts.

**Comment by wwwtony5488** [comment]
Hi, I figured out what happened. 
Because gradient cant be used with 'RGBa' on IE,
such as ``` colorStops: [{ offset: 0, color: '#FF00FF00' }, { offset: 1, color: 'rgba(255, 0, 0, 0.5)' }] ```

Thank you for answering
