### ISSUE TITLE
How to make data reactive, like getting dynamic data through props ?

### ISSUE THREAD

**Issue by ironshashi** [ecomfe/vue-echarts#381]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
I have created a basic bar chart and getting the data in chart through props but when I am changing the data from parents component and passing it into the child component as props but chart data is not being changed,? how I can make the chart data reactive?

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

"vue": "^2.6.10",   
"echarts": "^4.2.1",
"vue-echarts": "^4.0.3",

## Reproduction link / 复现链接

```
<template>
	<ECharts :options="bar" style="width:100%; height:300px"></ECharts>
</template>

<script>
import ECharts from "vue-echarts";
import "echarts/lib/chart/bar";
import "echarts/lib/component/title";
import 'echarts/lib/component/legend';

import { ChartConfig } from "../../constants/chart-config";
// window.bar.resize();
export default {
	props:['data'],
		components: {
			ECharts
	},
	data() {
		return {
			bar: {
				tooltip: {
					trigger: "axis"
				},
				color: ChartConfig.color.primary,
			xAxis: {
				type: 'value',
				boundaryGap: [0, 0.01]
			},
			yAxis: {
				type: 'category',
				data: ['a','b','c','d','e','f','g','h']
			},
			legend: {
				data: ["Series A"],
				show:false
			},
			series: [
				{
					name: "Series A",
					type: "bar",
					data: this.data,
					markPoint: {
						data: [{ type: "max", name: "max" }, { type: "min", name: "min" }]
					},
					markLine: {
						data: [{ type: "average", name: "average" }]
					}
				}
			]
			}
		};
	},
	mounted(){
		this.bar = setOption(this.options, true);
		console.log(this.bar)
	},
};
`</script>

```
And My parent component is 

```
<template>
	<div>
		<v-card>
			<v-card-title></v-card-title>
			<v-divider></v-divider>
			<v-card-text>
					<v-btn color="success" @click="changeData()">data 1</v-btn>
				<HorizontalBar :data="chartData" />
			</v-card-text>
		</v-card>
	</div>
</template>
<script>
	import HorizontalBar from "../Charts/HorizontalBar";
	export default{
		components: {
			HorizontalBar
		},
		data(){
			return{
				chartData: [10, 20, 10, 20, 10, 20, 10,20]
			}
		},
		methods: {
			changeData(){
				this.chartData = [15, 25, 15, 25, 45, 21, 16,22]
				// console.log(this.chartData)
			}
		}
	}
</script>
```

And one more thing how I can make it responsive, When I change the screen size chart does not get small I have hard reload the page to see the effect

**Comment by Justineo** [comment]
Please, do provide a runnable reproduction and keep it minimal to reflect your issue.

**Comment by ironshashi** [comment]
@Justineo https://codesandbox.io/s/vue-template-22v7e this is the running url

**Comment by Justineo** [comment]
You should make the `bar` field as a computed property.

https://codesandbox.io/s/vue-template-ep6of

**Comment by ironshashi** [comment]
thank you so much this works, please tell me one more thing why the chart is not getting responsive, I mean when I resize my browser window, chart's size does not reduce I have to hard reload the page then size reduces.

**Comment by Justineo** [comment]
You should add an `autoresize` prop to it.

**Comment by ironshashi** [comment]
Thank you so much, that also works.
