### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by hykilpikonna** [ecomfe/vue-echarts#383]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告
- [X] Question / 问题 (╯‵□′)╯︵┻━┻

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [X] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

4.0.4

### 问题

![](https://i.imgur.com/vOQGEsM.png)

### 用 `import ECharts from 'vue-echarts'` 导入的话:

![](https://user-images.githubusercontent.com/22280294/65824435-31514880-e237-11e9-9464-f1067a4bd15d.png)

Main.ts:

```ts
import Vue from 'vue';
import App from './components/app/app.vue';

// Import Element UI
import ElementUI from 'element-ui';
Vue.use(ElementUI, {locale: 'en-us'});

// Import Cookies
import VueCookies from 'vue-cookies';
Vue.use(VueCookies);

// 手动引入 ECharts 各模块来减小打包体积
import 'echarts/lib/chart/bar'
import 'echarts/lib/component/tooltip'

// Import ECharts
// 在 webpack 环境下指向 components/ECharts.vue
const ECharts = require('vue-echarts');
Vue.component('v-chart', ECharts);

// Config
Vue.config.productionTip = false;

// Init app
new Vue(
{
    render: (h) => h(App),
})
.$mount('#app');
```

**Comment by Justineo** [comment]
为什么要混用 import 和 require？

**Comment by hykilpikonna** [comment]
> 为什么要混用 import 和 require？

因为 TS import 会报错... (上面第二个截图那样)

**Comment by Justineo** [comment]
你先自己声明一下模块吧。目前我们没有提供类型声明。

require/import 混用是不能保证正常工作的。

**Comment by hykilpikonna** [comment]
> 你先自己声明一下模块吧。目前我们没有提供类型声明。
> 
> require/import 混用是不能保证正常工作的。

声明模块了也不行...

声明模块:

![image](https://user-images.githubusercontent.com/22280294/65835351-51265200-e2b3-11e9-8a78-d5f95f7ef3a7.png)

导入:

![image](https://user-images.githubusercontent.com/22280294/65835358-613e3180-e2b3-11e9-8662-d0cf6ff222b9.png)

报错:

![image](https://user-images.githubusercontent.com/22280294/65835363-6bf8c680-e2b3-11e9-8067-581e965da16c.png)

**Comment by Justineo** [comment]
按需引入时需要自己引入对应的图表模块。这个需要根据你实际使用来，Readme 里仅为示例代码。
