### ISSUE TITLE
无法正常显示比例尺和标题

### ISSUE THREAD

**Issue by maicWorkGithub** [ecomfe/vue-echarts#385]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts/components/ECharts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

```
    "echarts": "^4.4.0",
    "vue": "^2.6.10",
    "vue-echarts": "^4.0.4"
```

## Reproduction link / 复现链接

https://codesandbox.io/s/vue-template-4jzps?fontsize=14

**Comment by Justineo** [comment]
你需要进行按需引入。

见 https://codesandbox.io/s/vue-template-i50tc

**Comment by maicWorkGithub** [comment]
哇, 拆分的这么细. 谢谢
