### ISSUE TITLE
Missing file extension "vue" for "vue-echarts"eslint(import/extensions)

### ISSUE THREAD

**Issue by jllagerberg** [ecomfe/vue-echarts#386]
I have an issue with my linter saying `Missing file extension "vue" for "vue-echarts"eslint(import/extensions)`. What is the problem and how do I solve it?

![Untitled](https://user-images.githubusercontent.com/27690759/67095535-6e658680-f1b6-11e9-8450-074c0e0c8526.jpg)

**Comment by Justineo** [comment]
The warning is quite self-explanatory. See [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md).

**Comment by jllagerberg** [comment]
Not really. Should I import it as `'vue-echarts.vue'`? Because that won't work either.

And why do I get that warning for vue-echarts and not my other 20 libraries I have imported in my `main.js`?

**Comment by Justineo** [comment]
If you are using webpack, `vue-echarts` will be resolved to the single file component instead of the pre-compiled dist file. Not sure how you’ve configured ESLint in your project. Maybe you can change your ESLint config to explicitly allow omitting `.vue` extensions.

**Comment by aaroni34** [comment]
What was your solution to this? @Justineo answer? Thank you

**Comment by juliandreas** [comment]
> 
> 
> What was your solution to this? @Justineo answer? Thank you

I disabled eslint for that line
