### ISSUE TITLE
Treemap chart supporting

### ISSUE THREAD

**Issue by MrCapsLock** [ecomfe/vue-echarts#387]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
Is support this component for treemap charts?

**Comment by Vicellken** [comment]
Hi there,

I found this [blog](https://firsemisphere.blogspot.com/2019/03/javascript-vue-treemap-echartstreemap.html). 

It offers a solution, but the way it deals with data is not elegant. I am looking for a way to retrieve data under this structure, instead of crazy lines of 'data'.

**Comment by Justineo** [comment]
### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

**Comment by Justineo** [comment]
You can use all features available in ECharts with Vue-ECharts. Closing this as required information is not provided.
