### ISSUE TITLE
实例极坐标双数值轴 options 中 title属性失效

### ISSUE THREAD

**Issue by FannyFanFan** [ecomfe/vue-echarts#392]
## The type of this issue / Issue 类型

- title: { text: '极坐标双数值轴'  },属性失效

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [import ECharts from 'vue-echarts ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

- "vue-echarts": "^4.0.4",

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
你确定你用的是打包版本？

**Comment by FannyFanFan** [comment]
package.json 
"echarts": "^4.4.0",

**Comment by Justineo** [comment]
你应该不是引用的打包版本，加上 `import 'echarts/lib/component/title'` 试试。

**Comment by FannyFanFan** [comment]
代码页和你的示例一毛一样，只有package.json部分我自己搞的。。。
加上echarts/lib/component/title 会报错，而且node_modules包对应路径里的确没有title...

**Comment by Justineo** [comment]
应该不是 `vue-echarts` 的问题，请检查自己依赖的 `echarts` 版本。
