### ISSUE TITLE
是否能初始化时默认有点击了某一横坐标的效果 如图

### ISSUE THREAD

**Issue by ouaisheinie** [ecomfe/vue-echarts#393]
![image](https://user-images.githubusercontent.com/27536300/69402645-74113780-0d33-11ea-9c60-097f4c310330.png)
初始化的时候是这样的
我想达到如下效果  初始化后 默认选中了最后那一根线
![image](https://user-images.githubusercontent.com/27536300/69402671-85f2da80-0d33-11ea-9d87-7ea7e958df75.png)
竖线效果是tooltip这样配置的 没有要提示框组件  
![image](https://user-images.githubusercontent.com/27536300/69402716-a28f1280-0d33-11ea-9b2d-a4dc89afb549.png)
请问有什么方案呢？

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。

---

另外本项目仅负责 ECharts 的 Vue 封装版本直接相关的问题，不负责 ECharts 使用方法的问题。
