### ISSUE TITLE
Cannot read property 'linearMap' of undefined

### ISSUE THREAD

**Issue by liuquanzhang** [ecomfe/vue-echarts#396]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [1 ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
使用 Echarts.number.linearMap() 报错未定义!!!
 Cannot read property 'linearMap' of undefined
我现在根据官方示例编写日历图表 但是遇到了这个错误 请帮帮我
是因为为没有引入具体组件吗?

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？
    import Echarts from 'vue-echarts';
    import 'echarts/lib/chart/pie';
    import 'echarts/lib/chart/bar';
    import 'echarts/lib/chart/line';
    import 'echarts/lib/coord/calendar/Calendar';
    import 'echarts/lib/coord/calendar/prepareCustom';
    import 'echarts/lib/coord/calendar/CalendarModel';
    import 'echarts/lib/chart/custom';
    import 'echarts/lib/component/calendar';
    import 'echarts/lib/component/calendar/CalendarView';
    import 'echarts/lib/processor/dataFilter';
    import 'echarts/lib/chart/map';

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
     "vue": "^2.6.10",
    "vue-echarts": "^4.0.4",

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by liuquanzhang** [comment]
@firede

**Comment by Justineo** [comment]
```js
import numberUtil from 'echarts/lib/util/number'

numberUtil.linearMap(...)
```
