### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by q306038470** [ecomfe/vue-echarts#398]
![image](https://user-images.githubusercontent.com/30361914/70415818-7c3dd680-1a98-11ea-99f9-c110ffb4e8fa.png)

引入之后出现上面的问题。也不知道哪里引得不对了

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。

--

Ps. 请阅读 README。

**Comment by xiaohaiH** [comment]
你是按需引入的吧,  line 模块没有引入
