### ISSUE TITLE
热力图不支持吗？

### ISSUE THREAD

**Issue by zongyan86** [ecomfe/vue-echarts#399]
使用官方这个热力图，用vue-echarts会出不来。
https://www.echartsjs.com/examples/zh/editor.html?c=calendar-heatmap

导入方式
import 'echarts/lib/chart/heatmap';
import 'echarts/lib/component/visualMap';

脚本报错：
![image](https://user-images.githubusercontent.com/3397251/70492179-8a463280-1b3e-11ea-845b-9ca8e778040f.png)

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
