### ISSUE TITLE
请问怎样才能直接在html文件中使用vue-echarts呢？可否提供个demo

### ISSUE THREAD

**Issue by ganp1020** [ecomfe/vue-echarts#400]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [true ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [true ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

使用cdn引入

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
https://github.com/ecomfe/vue-echarts/blob/master/README.zh_CN.md#cdn
https://github.com/ecomfe/vue-echarts/blob/master/README.zh_CN.md#%E5%85%A8%E5%B1%80%E5%8F%98%E9%87%8F

**Comment by ganp1020** [comment]
我非常认同这个库，但是我还是不明白怎么使用，要是有个demo 就好了

**Comment by ganp1020** [comment]
我试着使用 requirejs 去引入这些库， 可是出现一大堆报错， 加上之前不熟悉 requirejs
