### ISSUE TITLE
Would be good to have some example of this library usage

### ISSUE THREAD

**Issue by dvago** [ecomfe/vue-echarts#401]
Good morning/afternoon.

I'm currently facing a bug when a Vue component includes multiple v-chart component tags.
These v-chart components for some reason are sharing the options even if the passed options (via :options prop) are different.

It seems to me something related to the instance, so I was wondering if putting in place manualUpdate flag and using ref + mergeOptions could solve the bug, but unfortunately there is no snippet example anywhere to have a look at. Your front page (the one that contains examples) has been built for production therefore cannot be inspected to understand the set up of each example.

Would you mind considering add somewhere a list of snippets to showcase the usage of every single "options" of your library please?

**Comment by Justineo** [comment]
- [The demo of the Vue component](https://github.com/ecomfe/vue-echarts/blob/master/src/demo/Demo.vue)
- [Option reference of ECharts](https://echarts.apache.org/en/option.html)

**Comment by dvago** [comment]
@Justineo thanks for the links but I can't find anything related to the mergeOptions one as mentioned on my first comment, do you have anything available somewhere?

Thanks in advance.

**Comment by Justineo** [comment]
Oh, `mergeOptions` is just a better semantically named `setOption`. The `options` param is the same with the one ECharts' `setOption` accepts.

**Comment by Justineo** [comment]
> These v-chart components for some reason are sharing the options even if the passed options (via :options prop) are different.

You need to make sure you don't pass a shared `options` object to multiple component instance yourself. eg. by cloning them before passing into the props of those component instances.

**Comment by dvago** [comment]
@Justineo thanks for helping out on this issue, I'm currently not passing the same options:
As you can see below the xAxis data is different, however both of the charts are showing the same points (starting both from FY17)

First option object:

```
{
  "animation": false,
  "tooltip": {
    "trigger": "item",
    "backgroundColor": "#fcfdfd",
    "borderColor": "#2d519a",
    "padding": 4,
    "textStyle": {
      "color": "#041c2c",
      "fontSize": 11
    },
    "extraCssText": "box-shadow: 0 2px 3px -2px rgba(4, 28, 44, 0.2);"
  },
  "grid": {
    "top": "16",
    "right": "-10",
    "bottom": "16",
    "left": "-10"
  },
  "title": {
    "text": ""
  },
  "yAxis": {
    "type": "value",
    "show": false,
    "offset": 0,
    "axisLabel": {
      "show": false
    }
  },
  "xAxis": {
    "type": "category",
    "offset": 0,
    "show": false,
    "data": [
      "FY17",
      "1Q18-LTM",
      "2Q18-LTM",
      "3Q18-LTM",
      "FY18",
      "1Q19-LTM",
      "2Q19-LTM",
      "3Q19-LTM"
    ]
  },
  "color": "#1e4294",
  "series": [
    {
      "type": "line",
      "smooth": true,
      "symbol": "circle",
      "itemStyle": {
        "normal": {
          "borderWidth": 0,
          "color": "#041c2c"
        }
      },
      "data": [
        9612,
        9411,
        9324,
        9231,
        9256,
        9265,
        9270,
        9342
      ]
    }
  ]
}
```


And Second option object:


```
{
  "animation": false,
  "tooltip": {
    "trigger": "item",
    "backgroundColor": "#fcfdfd",
    "borderColor": "#2d519a",
    "padding": 4,
    "textStyle": {
      "color": "#041c2c",
      "fontSize": 11
    },
    "extraCssText": "box-shadow: 0 2px 3px -2px rgba(4, 28, 44, 0.2);"
  },
  "grid": {
    "top": "16",
    "right": "-10",
    "bottom": "16",
    "left": "-10"
  },
  "title": {
    "text": ""
  },
  "yAxis": {
    "type": "value",
    "show": false,
    "offset": 0,
    "axisLabel": {
      "show": false
    }
  },
  "xAxis": {
    "type": "category",
    "offset": 0,
    "show": false,
    "data": [
      "1Q18-LTM",
      "2Q18-LTM",
      "3Q18-LTM",
      "FY18",
      "1Q19-LTM",
      "2Q19-LTM",
      "3Q19-LTM",
      "FY19"
    ]
  },
  "color": "#1e4294",
  "series": [
    {
      "type": "line",
      "smooth": true,
      "symbol": "circle",
      "itemStyle": {
        "normal": {
          "borderWidth": 0,
          "color": "#041c2c"
        }
      },
      "data": [
        1109,
        1028,
        1037,
        1037,
        1076,
        1185,
        1269,
        1029
      ]
    }
  ]
}
```

**Comment by Justineo** [comment]
If you want to report a bug, please follow the issue template and provide a runnable reproduction. Thanks.

**Comment by dvago** [comment]
That's ok, I will try to find some workaround for it. Just wanted to flag it but I don't actually have time to provide a sample and I can't share the whole code as per my company's policies.

Thanks again for your support.
