### ISSUE TITLE
How to install with quasar-cli ?

### ISSUE THREAD

**Issue by hl037** [ecomfe/vue-echarts#402]
## The type of this issue / Issue 类型

- [* ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [* ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

How to integrate it with quasar-cli ? I tried to add the same `transpileDependencies` option in the build property of quasar.conf.js as the one for vue-cli 3, but it does not work...

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

latest

**Comment by Justineo** [comment]
I’m sorry but I’m not familiar with Quasar. It seems that you should consult the Quasar side on how to make the `transpileDependencies` option work.

**Comment by Justineo** [comment]
`vue-echarts@6` is now released with ESM support and no longer needs transpiling. It should work with quasar-cli and other tooling naturally.
