### ISSUE TITLE
能否支持全局设置主题，而不是每个图表组件都要设置 “theme”  指定主题

### ISSUE THREAD

**Issue by ganp1020** [ecomfe/vue-echarts#403]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
考虑在下个版本支持用 provide/inject 传入一些全局的 `initOptions`。

**Comment by mirari** [comment]
我尝试使用inheritAttrs、$attrs、$listeners在外面包一层组件，实现默认自定义主题等配置。传值、事件监听都没有问题，但是想直接调用v-chart组件的方法就变得很麻烦了，refs得取好几层

**Comment by Justineo** [comment]
`vue-echarts@6` 现已支持通过上层 `provide` 指定包括 `theme` 在内的多个配置。可以尝试迁移到最新版本（基于 ECharts 5）。
