### ISSUE TITLE
title&legend都不显示

### ISSUE THREAD

**Issue by usherwong** [ecomfe/vue-echarts#404]
## title和legend显示问题

- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

4.1.0

## Reproduction link / 复现步骤

引入Echart组件后，通过options传递参数。传递参数中的title和legend无法渲染到canvas中，没有标题和说明图例。只会渲染饼图，柱状图。
用的官方的demo
https://github.com/ecomfe/vue-echarts/blob/master/src/demo/data/pie.js

**Comment by Justineo** [comment]
Duplicate of #295

**Comment by usherwong** [comment]
已经找到解决办法
`import 'echarts/lib/component/legend'`
`import 'echarts/lib/component/title'`
