### ISSUE TITLE
Can't use this.data or this.computed as data source for chart

### ISSUE THREAD

**Issue by Zireael** [ecomfe/vue-echarts#410]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

Hi, when I try to use chart data from vue component data() property or from computed property, the data is not correctly displayed. I think chart expects a 'pure' data array and not vue-reactive data object.

### Please see codepen for 4 examples:
https://codesandbox.io/s/vue-echarts-issue-hn7sf

> pure data array: **works**
> `const data = [[1,1], [2,2], [3,3]]`
>
> vue prop passed down to child component: **works**
> `<myechart :prop="mydata"></myechart>`
>
> array from component data property: **fail**
> ```
>   data() {
>     return {
>         mydata: [[1,1], [2,2], [3,3]]
>     } 
>   }
> ```
>
> data from vue computed property: **fail**
> ```
>    computed: {
>       compdata: function() {
>           return [[1,1], [2,2], [3,3]]
>       }
>    }
> ```

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.1.0

## Reproduction link / 复现链接
https://codesandbox.io/s/vue-echarts-issue-hn7sf

**Comment by humanismusic** [comment]
Also running into this issue - did you find a workaround @Zireael ?
