### ISSUE TITLE
饼状图生成canvas位置不对，强制canvas的top值无用

### ISSUE THREAD

**Issue by FannyFanFan** [ecomfe/vue-echarts#412]
## The type of this issue / Issue 类型

- Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

- 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

- 具体情况参见图片(https://user-images.githubusercontent.com/12137715/71977103-ee9a0600-3252-11ea-9a1d-03889d9acc72.png) 我试着强制canvas的top值但没用，缺失的部分一直无法渲染

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- import ECharts from 'vue-echarts';

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

- ^4.1.0

## Reproduction link / 复现链接

- 问题截图 (https://user-images.githubusercontent.com/12137715/72032021-2f346680-32c9-11ea-8009-be169d35a3cb.png)

- 代码如下

```
<template>
    <figure>
        <v-chart :options="options" :autoresize="true" style="margin: 0 auto;"/>
    </figure>
</template>
<style lang='scss'>
canvas {
    top: 50px!important;
    vertical-align: middle;
}
figure {
    display: inline-block;
    position: relative;
    margin: 2em auto;
    border: 1px solid rgba(0,0,0,.1);
    border-radius: 8px;
    box-shadow: 0 0 45px rgba(0,0,0,.2);
    padding: 1.5em 2em;
    min-width: calc(40vw + 4em);
}
figure .echarts {
    width: 100%;
    min-width: 400px;
    height: 300px;
}
</style>
```

**Comment by Justineo** [comment]
请给出完整的最小复现，你可以试一下在 [ECharts Gallery](https://gallery.echartsjs.com/) 中使用相同的 options 是否存在问题。

**Comment by FannyFanFan** [comment]
sorry 忘记回复。抱歉，是我自己写错配置项的问题。这个问题可以关了。
