### ISSUE TITLE
src/component/Echarts.vue 247行代码有问题

### ISSUE THREAD

**Issue by dolphinfine** [ecomfe/vue-echarts#413]
## The type of this issue / Issue 类型

- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
![image](https://user-images.githubusercontent.com/27426130/72423859-f95b1a80-37bf-11ea-9003-73cc3aa9bb7a.png)

这行代码val和oldVal都是对象，属于引用类型，直接比较没有意义。

**Comment by Justineo** [comment]
See [README](https://github.com/ecomfe/vue-echarts/blob/master/README.zh_CN.md#props-%E5%9D%87%E4%B8%BA%E5%93%8D%E5%BA%94%E5%BC%8F).

> * `options`
>
> ECharts 实例的数据。修改这个 prop 会触发 ECharts 实例的 `setOption` 方法。
>
> 如果直接修改 `options` 绑定的数据而对象引用保持不变，`setOption` 方法调用时将带有参数 `notMerge: false`。否则，如果为 `options` 绑定一个新的对象，`setOption` 方法调用时则将带有参数 `notMerge: true`。
>
> 例如，如果有如下模板：
>
> ```html
> <v-chart :options="data"/>
> ```
>
> 那么：
>
> ```
> this.data = newObject // setOption(this.options, true)
> this.data.title.text = 'Trends' // setOption(this.options, false)
> ```
