### ISSUE TITLE
add getMap function

### ISSUE THREAD

**Issue by caizirong** [ecomfe/vue-echarts#415]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
3.1.3

Can we add echart's function which name is `getMap` ?
I've tested in my local project, just add one line in a js file.
According to this path `/src/components/ECharts.vue`, insert before line 267:
```js
getMap(mapName) {
    return echarts.getMap(mapName)
}
```
This will be useful when someone need exact some place's geographic info such as longitude or  latitude by `registerMap` and then `getMap` from a .json file downloading from internet.
Thanks.

**Comment by Justineo** [comment]
> This will be useful when someone need exact some place's geographic info such as longitude or latitude by `registerMap` and then `getMap` from a .json file downloading from internet.

I think it's a legit use case. Would you like to make a pull request for this?

**Comment by caizirong** [comment]
yes
