### ISSUE TITLE
graphic config 没有得到支持

### ISSUE THREAD

**Issue by BennieMeng** [ecomfe/vue-echarts#418]
## The type of this issue / Issue 类型

- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接
[graphic 配置页面](https://www.echartsjs.com/zh/option.html#graphic)

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by BennieMeng** [comment]
为什么我按照官网配置了水印，但是看不到
![image](https://user-images.githubusercontent.com/37033797/74120490-80a08000-4bfe-11ea-877a-11805f911af8.png)

**Comment by BennieMeng** [comment]
@Justineo @caizirong 请求帮助看一下，比较急

**Comment by BennieMeng** [comment]
```json
"graphic": [
    {
      "type": "image",
      "id": "logo",
      "right": 20,
      "bottom": 20,
      "z": 200,
      "bounding": "raw",
      "origin": [
        75,
        75
      ],
      "style": {
        "image": "http://p4.qhimg.com/t0132d7007637f9fbfb.png",
        "width": 150,
        "height": 150,
        "opacity": .7
      }
    }
  ]
```

**Comment by Justineo** [comment]
```js
import "echarts/lib/component/graphic";
```
