### ISSUE TITLE
图表根据容器自适应

### ISSUE THREAD

**Issue by jonny-xhl** [ecomfe/vue-echarts#421]
> 请问图表如何根据容器自适应调整大小呢？

现在通过自定义width,height配合grid的x y来调整，但是这样没有自适应

**Comment by Justineo** [comment]
CSS 设置长宽 `100%`，加上 `autoresize` prop。

**Comment by jonny-xhl** [comment]
当我设置 ==autoresize:true,== 时反而没有按照父元素的容器来自适应。

倒是没有设置这个属性的时候直接设置内联样式 100%还可以。

请问是怎么回事？
