### ISSUE TITLE
pie series positioning not working

### ISSUE THREAD

**Issue by rconstantine** [ecomfe/vue-echarts#425]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

4.2.1

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

I'll try to do a sandbox if an answer doesn't jump out at you guys. I have a series of three pie charts, as below, but the left, right, top, and bottom layout keywords are ignored. My imports on my vue file are these:

import 'echarts/lib/chart/pie'
import 'echarts/lib/component/title'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/legend'

Perhaps I'm simply missing another import? None of them specifically jumped out at me. Below I'm using 'left', 'right', and 'center' for the 'left' values.

```javascript
series: [
          {
            name: 'pie',
            type: 'pie',
            data: this.allCountsPie[0],
            radius: '25%',
            center: ['50%', '50%'],
            itemStyle: {
              emphasis: {
                shadowBlur: 10,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
              }
            },
            label: {
              position: 'outer',
              alignTo: 'labelLine',
              bleedMargin: 5
            },
            left: 'left'
          },
          {
            name: 'pie',
            type: 'pie',
            data: this.allCountsPie[1],
            radius: '25%',
            center: ['50%', '50%'],
            itemStyle: {
              emphasis: {
                shadowBlur: 10,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
              }
            },
            label: {
              position: 'outer',
              alignTo: 'labelLine',
              bleedMargin: 5
            },
            left: 'center'
          },
          {
            name: 'pie',
            type: 'pie',
            data: this.allCountsPie[2],
            radius: '25%',
            center: ['50%', '50%'],
            itemStyle: {
              emphasis: {
                shadowBlur: 10,
                shadowOffsetX: 0,
                shadowColor: 'rgba(0, 0, 0, 0.5)'
              }
            },
            label: {
              position: 'outer',
              alignTo: 'edge',
              bleedMargin: 5
            },
            left: 'right'
          }
        ]
```

I also tried setting them all as per this example: https://echarts.apache.org/examples/en/editor.html?c=pie-alignTo

**Comment by Justineo** [comment]
We stopped maintaining Vue ECharts version < 6. If there are still similar problems in v6, please open a new issue with runnable repro. Thank you.
