### ISSUE TITLE
采用2D地图显示数据内容 本身显示的数据内容会显示为纬度 求大神给个解决思路 已生成复现链接

### ISSUE THREAD

**Issue by luorongjiangcuo** [ecomfe/vue-echarts#429]
## The type of this issue / Issue 类型

 采用geo 气泡模式 data里面的数据项是三个 经度，纬度，数值，视图上会显示数组里的第二项数纬度，不会显示数值

地图的省份名称给了 show: true,但是依然未显示省份名称
- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

https://3r6v4.csb.app/ 复现内容链接地址 
https://codesandbox.io/s/crazy-glade-3r6v4?fontsize=14&hidenavigation=1&theme=dark  代码地址

**Comment by Justineo** [comment]
这个感觉不是 Vue 组件的问题，请先确认仅使用 ECharts 的情况下能正确渲染吧。
