### ISSUE TITLE
Could not find a declaration file for module 'vue-echarts' error

### ISSUE THREAD

**Issue by sprklinginfo** [ecomfe/vue-echarts#432]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
"vue-echarts": "^5.0.0-beta.0",
"echarts": "^4.7.0",

## Reproduction link / 复现链接
In main.js the error reported with this line:
import ECharts from 'vue-echarts'

In other vue files, I tried some examples from echarts doc and doc here, no charts are displayed on the page.

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by sprklinginfo** [comment]
It turns out I have to import echarts modules manually. After that, it works. Sorry I didn't realize it earlier.

**Comment by yech1990** [comment]
@sprklinginfo  Could your please show more details? I have the same problem...
