### ISSUE TITLE
Can you please update to "echarts": "4.7.0"

### ISSUE THREAD

**Issue by rajwitt** [ecomfe/vue-echarts#434]
Can you please update to "echarts": "4.7.0"

**Comment by betconnections-dev** [comment]
yes please

**Comment by carlfarrington** [comment]
Does it not just pull the latest version ^4.6.0 then?

**Comment by ThePhoenixBird** [comment]
i would love to see the latest vesion 4.7.0 supported

**Comment by Mikilll94** [comment]
Any update on this?

**Comment by carlfarrington** [comment]
This is just a wrapper. echarts isn't part of the package.

package.json lists the dependencies as:
  "devDependencies": {
    "echarts": "^4.6.0"}
}

the caret means any minor version number change, so 4.*.*

so you grab and update echarts yourself with npm, yarn, etc.

Is there something else here that I'm missing? I am new to this stuff, so apologise if so.

**Comment by rajwitt** [comment]
I noticed we are also using our own import for usage and manage the versioning of it.

I was also new to the way this is linked but I guess the devDependencies still show the latest tested version from a compatibility standpoint; so if we increase our own it means we need to validate compatibility ourselves. That in itself is a more minor point though.
