### ISSUE TITLE
Need help with chart widths and resizing

### ISSUE THREAD

**Issue by devopsprosiva** [ecomfe/vue-echarts#435]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ X ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ X ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [ X ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
4.1.0

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

Hi @Justineo ,

I'm using `echarts 4.7.0` and `vue-echart 4.1.0` for my application built using electron, nuxt and tailwindcss. I was able to get some basic example charts working. However, I'm facing 2 issues:

1. I added an `echarts` css property in my page and set the width and height to 100%. However, the chart doesn't fill up to 100% of it's container div.
[https://github.com/devopsprosiva/electron-nuxt-echarts/blob/master/src/renderer/layouts/default.vue#L60](https://github.com/devopsprosiva/electron-nuxt-echarts/blob/master/src/renderer/layouts/default.vue#L60)
2. How can I make the charts responsive so that if I reduce the electron window size, the charts should resize? Is there any documentation regarding this?

Here's a link to my github repo with all the code: ** https://github.com/devopsprosiva/electron-nuxt-echarts **

- The components can be found under [https://github.com/devopsprosiva/electron-nuxt-echarts/tree/master/src/renderer/components](https://github.com/devopsprosiva/electron-nuxt-echarts/tree/master/src/renderer/components)
- The page which displays the charts can be found at [https://github.com/devopsprosiva/electron-nuxt-echarts/blob/master/src/renderer/layouts/default.vue](https://github.com/devopsprosiva/electron-nuxt-echarts/blob/master/src/renderer/layouts/default.vue)

I'd appreciate your help in resolving this issue. Thanks in advance.

**Comment by Justineo** [comment]
You need to use the `autoresize` prop on your Vue ECharts component.

**Comment by devopsprosiva** [comment]
@Justineo Thanks for the suggestion. I added `autoresize="true"` to all the chart components but I still see the previous behavior. Any suggestions?

**Comment by devopsprosiva** [comment]
I simplified the page and just added one chart. For some reasone, autoresize is not being applied. Any ideas how to get it working?

This is the latest page: https://github.com/devopsprosiva/electron-nuxt-echarts/blob/master/src/renderer/layouts/default.vue

**Comment by devopsprosiva** [comment]
![image](https://user-images.githubusercontent.com/6834501/79972054-f5bbeb80-84b2-11ea-95ee-157947dc34f7.png)

- Green is the container at full width.
- Gray is the echarts element. Even though autoresize is set and echarts css property set to use full width, it's not resizing to the full container width.

**Comment by Justineo** [comment]
Your width/height settings are probably overridden by the default style of Vue ECharts. Try setting styles like:

```css
div.echarts {
  width: 100%;
  height: 100%;
}
```

**Comment by devopsprosiva** [comment]
@Justineo Awesome!!! That worked.
