### ISSUE TITLE
How to get shared axispointer for charts in separate divs?

### ISSUE THREAD

**Issue by devopsprosiva** [ecomfe/vue-echarts#437]
Hi @Justineo,

I'm using vue-echarts in my SPA app built using nuxtjs, electron and tailwindcss.

Is there any way to display a shared axispointer across charts in a single page but each chart is in it's own div?

Thanks in advance.

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.

---

This is only a wrapper component for ECharts. Please make sure you have something works with ECharts itself first.
