### ISSUE TITLE
因為動畫造成圖表上多畫一條奇怪的線

### ISSUE THREAD

**Issue by augustine-lin** [ecomfe/vue-echarts#440]
## The type of this issue / Issue 类型

- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

我不清楚是不是EChart本身的問題，因為沒看到EChart有人發問。

## Details / 详情

[影片網址](https://streamable.com/cey1hv)

我使用datezoom, 再重新塞入data的時候
this.chartOptions.series.data = data
動畫會多畫一條奇怪的線
如果我關閉動畫，就不會再出現奇怪的線了。

`series: {
          type: 'line',
          data: [],
          animation: false
        }`

請問有沒有什麼方法可以解決問題
或是有沒有人遇過類似的問題？

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

"vue-echarts": "^4.1.0"

## Reproduction link / 复现链接

[影片網址](https://streamable.com/cey1hv)

**Comment by Justineo** [comment]
请使用 ECharts Gallery 把你使用的图表配置重现一下，如果仅在 Vue ECharts 中遇到问题，才能确认不是 ECharts 本身的问题。

**Comment by cfancc** [comment]
我也有类似的问题，关了动画好了

**Comment by Justineo** [comment]
这里仅解决 Vue 组件封装，如果是 ECharts 本身的问题，请去 ECharts 官方 repo 反馈，谢谢。
