### ISSUE TITLE
Can't get Markline & MarkPoint to show?

### ISSUE THREAD

**Issue by fogx** [ecomfe/vue-echarts#441]
## The type of this issue / Issue 类型
Demo not working in vue as expected.

- [ X ] Bug report / Bug 报告
- [ X ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

I am trying to use echarts with vue, and wanted to implement this example:
https://echarts.apache.org/examples/en/editor.html?c=bar1
![image](https://user-images.githubusercontent.com/10303647/81819137-34cbe280-952f-11ea-95fa-51b429084323.png)

I noticed, however, that (among other things) the markLine and markPoint elements do not show up in my graphic. It is unclear from the demo and the vue-echarts examples, which library (/libraries) i need to import to make this demo work as intended.
Please tell me how to fix these issues?

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [ X ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
        "echarts": "^4.7.0",
        "vue-echarts": "^5.0.0-beta.0",

## Reproduction link / 复现链接

https://codesandbox.io/s/async-surf-d3qb9?file=/src/App.vue

**Comment by fogx** [comment]
i've found the items in components:
import "echarts/lib/component/markLine";
import "echarts/lib/component/markPoint";

**Comment by chaiman2601** [comment]
greate, thanks
