### ISSUE TITLE
使用 echarts cdn 后，echarts 还是打包到了项目中

### ISSUE THREAD

**Issue by benleilei** [ecomfe/vue-echarts#444]
## The type of this issue / Issue 类型

- [x] Bug report / Bug 报告

## Not introduced by 非 ECharts 本身问题

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

ECharts 使用 webpack-cdn-plugin 插件引入，但是通过命令 vue-cli-service build --report 检测，打包的文件里还是包含 echarts 的文件。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

vue-echarts 4.1.0

## 修改建议

修改 src/components/ECharts.vue 文件的第 13 行
import echarts from 'echarts/lib/echarts'
为
import echarts from 'echarts'

**Comment by Justineo** [comment]
引用 `echarts/lib/echarts` 是刻意的，否则无法按需加载。你可能需要调整 webpack 插件的配置。
