### ISSUE TITLE
error：Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by chengmanxiang** [ecomfe/vue-echarts#446]
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。
## 详情
./~/zrender/lib/core/event.js
258行 var stop = isDomLevel2？ function（e）.{ e.preventDefault() }

error：Unable to preventDefault inside passive event listener invocation

**Comment by Justineo** [comment]
你没有提供必要的信息，也没有确认这是否是 ECharts 本身的问题，我们无法提供帮助。

**Comment by chengmanxiang** [comment]
> 你没有提供必要的信息，也没有确认这是否是 ECharts 本身的问题，我们无法提供帮助。

./~/zrender/lib/core/event.js    这个js报错，不是vue-echarts里面的吗？

**Comment by Justineo** [comment]
Vue-ECharts 只是 ECharts 的一层封装，ZRender 是 ECharts 调用的底层库，和 Vue 组件无关的。

**Comment by chengmanxiang** [comment]
> Vue-ECharts 只是 ECharts 的一层封装，ZRender 是 ECharts 调用的底层库，和 Vue 组件无关的。

好的，谢谢，不过更新echarts没啥效果，官网的echarts移动就没这个问题，哎，不好定位

**Comment by 1113519870** [comment]
![BO B09UJ`V{P71CK8Q8HN`H](https://user-images.githubusercontent.com/60683690/113668772-50ab1a80-96e5-11eb-819f-e294995587f1.png)
大佬解决了吗？
我这边是为了解决上图的问题，在main.js中引入了：import 'default-passive-events'，但是就导致了echart 的datazoom在缩放的时候控制台报错：Unable to preventDefault inside passive event listener invocation.但是图表的效果没有影响

**Comment by 1113519870** [comment]
已解决：参考https://www.it610.com/article/1294610360782888960.htm

**Comment by nidepan** [comment]
> 已解决：参考https://www.it610.com/article/1294610360782888960.htm

还有网址吗？ 怎么解决的~ 我也是引入了import 'default-passive-events 然后在echart的datazoom会报错 求解
