### ISSUE TITLE
tooltip自定义formatter

### ISSUE THREAD

**Issue by TangTangJia** [ecomfe/vue-echarts#448]
![image](https://user-images.githubusercontent.com/34622385/83834300-8d526200-a720-11ea-868d-dd5b855850b1.png)

拼接formatter字符串后，显示出来会多一个逗号
![image](https://user-images.githubusercontent.com/34622385/83834323-9e02d800-a720-11ea-9b53-a79a13feefd0.png)

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。

---

PS. ECharts 本身的问题请不要提交到这个项目。
