### ISSUE TITLE
echarts-gl warning when autoresize

### ISSUE THREAD

**Issue by likeben** [ecomfe/vue-echarts#451]
after import echarts-gl, there is always a warning message (Dom has no width and height) in browser console when toggle chart(autoresize is set to be true) between hidden and show (such as switch tabs)

![image](https://user-images.githubusercontent.com/24544714/84017335-15e73180-a9b1-11ea-9f28-86ce377f6a8a.png)

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.
