### ISSUE TITLE
can't find getMap method in the recently version

### ISSUE THREAD

**Issue by stalkercn** [ecomfe/vue-echarts#454]
## The type of this issue / Issue 类型
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题
- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
5.0.0-beta.0

## Reproduction link / 复现链接
https://github.com/ecomfe/vue-echarts/tree/master/src/components

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**
在4个月前加入的新方法getMap https://github.com/ecomfe/vue-echarts/pull/416  用npm 引入最新版本(5.0.0-beta.0)中却没有此内容

**Comment by Justineo** [comment]
静态方法可以直接通过 `echarts` 本身调用。

Ps. 现在可以尝试迁移到最新版的 `6.0.0-beta.2`。
