### ISSUE TITLE
markline首次渲染不出来？

### ISSUE THREAD

**Issue by zongyan86** [ecomfe/vue-echarts#455]
![image](https://user-images.githubusercontent.com/3397251/85374747-ce8fa200-b567-11ea-988e-52fa9b12df37.png)
![image](https://user-images.githubusercontent.com/3397251/85374870-01d23100-b568-11ea-8994-029e29c29004.png)

computed中配置series ，首次请求，markline渲染不出来，重新请求后，第二次请求就能渲染。。

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
