### ISSUE TITLE
在使用 vue-charts 时如何自定义 echarts 版本

### ISSUE THREAD

**Issue by heyi-let** [ecomfe/vue-echarts#457]
## The type of this issue / Issue 类型

Feature request / 新特性需求

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

如何修改 vue-echarts 中使用的 echarts 版本，或者在使用 vue-charts 时如何自定义 echarts 版本。

**Comment by Justineo** [comment]
不使用打包版本引入，自己安装 `echarts` 依赖即可。
