### ISSUE TITLE
TypeError: Cannot assign to read only property 'exports' of object '#<Object>' 【Module../node_modules/vue-echarts/node_modules/lodash/isObject.js】

### ISSUE THREAD

**Issue by wrhwww** [ecomfe/vue-echarts#461]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
"echarts": "^4.8.0",
"vue-echarts": "^5.0.0-beta.0",

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

![image](https://user-images.githubusercontent.com/53960031/89126227-b91e7800-d516-11ea-85ee-99c6056e6b03.png)

![image](https://user-images.githubusercontent.com/53960031/89126244-da7f6400-d516-11ea-9a88-565dfb33d5e6.png)

![image](https://user-images.githubusercontent.com/53960031/89126149-064e1a00-d516-11ea-8295-12f0f79735e4.png)

**Comment by willwan92** [comment]
我遇到了同样的问题，通过[这个方案](https://www.jianshu.com/p/acec542bcfc4)解决了这个问题

**Comment by zhenhuiWang** [comment]
> 我遇到了同样的问题，通过[这个方案](https://www.jianshu.com/p/acec542bcfc4)解决了这个问题

同样解决了

**Comment by Justineo** [comment]
见 @willwan92 的评论。
