### ISSUE TITLE
manual-update 手动更新不生效问题

### ISSUE THREAD

**Issue by suchenglin2017** [ecomfe/vue-echarts#463]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

"^2.4.1"

## Reproduction link / 复现链接
`<v-chart ref="chart" :manual-update="true" :autoresize="true" />`

 const opt = {
        customTitle: 'aaa',
        xAxis: {
          type: 'category',
          data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        },
        yAxis: {
          type: 'value',
        },
        series: [{
          data: [820, 932, 901, 934, 1290, 1330, 1320],
          type: 'line',
        }],
  };

` this.$refs.chart && this.$refs.chart.mergeOptions(opt);`

手动更新按以上配置，但没有生效，已排除 opt 配置的问题，帮忙看看是否写的有问题。

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by suchenglin2017** [comment]
应该是我使用的版本太低了。

**Comment by Justineo** [comment]
我先关了，升级后依然有问题的话再说。
