### ISSUE TITLE
I want use bar， but has error

### ISSUE THREAD

**Issue by Roxannej** [ecomfe/vue-echarts#464]
// my code
import 'echarts/lib/chart/line'
import 'echarts/lib/component/polar'
import 'echarts/lib/component/tooltip'

import 'echarts-gl'
import 'echarts/lib/component/bar'

// error
* echarts/lib/component/bar in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/h5/chart.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save echarts/lib/component/bar

**Comment by Justineo** [comment]
Please follow the issue template, otherwise we'll close the issue directly. Thank you.
