### ISSUE TITLE
组件在Linux下打包，报Module parse failed: Unexpected token (1:0)

### ISSUE THREAD

**Issue by Damon-duan** [ecomfe/vue-echarts#465]
ERROR in ./node_modules/vue-echarts/components/ECharts.vue
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
<template>
<div class="echarts"/>
</template>

resolve:

<template>
<div class="echarts"></div>
</template>

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
