### ISSUE TITLE
Component dont Show when Deployed

### ISSUE THREAD

**Issue by arikardnoir** [ecomfe/vue-echarts#479]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

I haven't demonstration because my problems is very dificult to find, cuz my Component didnt appear when the project is deployed. But, locally is working.

I dont know if I need to do something special

**Comment by Justineo** [comment]
Without reproduction it’s not possible for us to identify the problem. I’m sorry.
