### ISSUE TITLE
Component isnt appear on dist to deploy

### ISSUE THREAD

**Issue by arikardnoir** [ecomfe/vue-echarts#480]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/pedantic-chaplygin-bm7g7?file=/src/main.js) demo below:**

https://codesandbox.io/s/pedantic-chaplygin-bm7g7?file=/src/main.js

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/pedantic-chaplygin-bm7g7?file=/src/main.js) 上 demo 的链接：**

My problem consists when dist folder is generated or he's not be generated in dist 

When i run "npm run serve" the component is showed

But, when i run "npm run build" & later run "serve -s dist" the component stop being showed

But, i cans see him when a i inspect the elements

like this:
![error-component](https://user-images.githubusercontent.com/18501593/95324036-07455400-0897-11eb-9679-bdbf80fa168b.png)

I dont know if i miss some configuration

**Comment by Justineo** [comment]
It seems that you render the chart when the container isn’t visible yet. You can either use the `autoresize` prop or make sure the container has a non-zero size.

**Comment by arikardnoir** [comment]
Thanks for the reply, but it can happen only when the dist is created? 

> It seems that you render the chart when the container isn’t visible yet. You can either use the `autoresize` prop or make sure the container has a non-zero size.
