### ISSUE TITLE
series.tooltip 不生效，配置在外面才可以

### ISSUE THREAD

**Issue by Lyle666** [ecomfe/vue-echarts#482]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
chartOptions: {
        // tooltip: {
        //   trigger: 'item',
        //   showContent: true,
        //   confine: false,
        //   position: 'right',
        //   formatter: function(params) {
        //     console.log(params);
        //     let imgUrl = params.data.thumbnail;
        //     let htmlStr = `<img style=width:20px;height:15px; src= ${imgUrl}/>`;
        //     return htmlStr;
        //   }
        // },
        grid: { top: '70%' },
        geo: {
          show: true,
          map: 'USA',
          roam: true,
          // center: 中心点
          zoom: 1.5,
          selectedMode: 'multiple',
          itemStyle: {
            normal: {
              areaColor: '#DEE4F1',
              borderType: 'dotted',
              borderColor: '#8B9AB2',
              borderWidth: '2'
            },
            emphasis: {
              areaColor: '#DCF6ED',
              borderColor: '#4BD1A0',
              borderType: 'solid',
              borderWidth: '2'
            }
          },
          top: '20%'
        },
        series: [
          {
            type: 'scatter',
            coordinateSystem: 'geo',
            name: 'USA',
            symbol: `image://${svg}`,
            symbolSize: 15,
            tooltip: {
              trigger: 'item',
              triggerOn: 'mousemove',
              showContent: true,
              confine: false,
              position: 'right',
              formatter: function(params) {
                console.log(params);
                let imgUrl = params.data.thumbnail;
                let htmlStr = `<img style=width:20px;height:15px; src= ${imgUrl}/>`;
                return htmlStr;
              }
            },
            itemStyle: {
              color: '#ddb926'
            },
            data: this.mapData
          }
        ]
      },

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [ ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
