### ISSUE TITLE
Example of using mergeOptions or appendData

### ISSUE THREAD

**Issue by lesovsky** [ecomfe/vue-echarts#483]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告
- [x] Usage example

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

5.0.0-beta.0

Hi, could you provide an example of using mergeOptions or appendData function for updating charts. I saw examples in native Charts, but have no clue how to do the same using vue-echarts.

Thanks.

**Comment by lesovsky** [comment]
I could do this with the following, a straightforward way, but I am not sure this is a vue-echarts correct (or preferred) way )))
```
<template>
  <v-chart :options="options"/>
</template>

<script>
import ECharts from 'vue-echarts'
import 'echarts/lib/chart/line'
import 'echarts/lib/component/tooltip'
import 'echarts/lib/component/legend'
import 'echarts/lib/component/title'

export default {
  name: "LineChart2",
  components: {
    'v-chart': ECharts
  },
  mounted() {
    this.pollData()
  },
  data() {
    let data = [];
    let start = Date.now() - 100000

    for (let i = 0; i < 100; i++) {
      data.push([start, Math.random() * 100]);
      start += 1000
    }

    return {
      polling: null,
      options: {
        title: {
          text: 'Test chart',
        },
        animation: false,
        grid: {
          left: '5%',
        },
        legend: {
          bottom: 0,
          left: 'center',
          data: ['total']
        },
        tooltip: {
          trigger: 'axis',
        },
        xAxis: {
          type: 'time'
        },
        yAxis: {
          type: 'value'
        },
        series: [{
          name: 'total',
          type: 'line',
          data: data,
        }]
      }
    }
  },
  methods: {
    pollData () {
      this.polling = setInterval(async () => {
        let data0 = this.options.series[0].data
        data0.shift()
        data0.push([Date.now(), Math.random() * 100])
      }, 1000)
    },
  }
}
</script>

<style scoped>
.echarts {
  width: 90%;
  margin: 20px auto;
  height: 350px;
}
</style>
```

**Comment by Justineo** [comment]
You can just use the data-driven way. `mergeOptions` is an escape hatch to bypass Vue's reactivity system for occasions with with huge amount of data and you don't want Vue to observe all of your data.
