### ISSUE TITLE
Example with using mouse events

### ISSUE THREAD

**Issue by lesovsky** [ecomfe/vue-echarts#484]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告
- [x] Need help or example

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

vue-echarts 5.0.0-beta.0

Hi, could you provide a minimal example of how to register a function (e.g. console.log()) when user clicks on chart's object.

I read [API docs](https://echarts.apache.org/en/tutorial.html#Events%20and%20Actions%20in%20ECharts) about mouse events, but I'm a bit confused, because when I use vue-echarts I don't have chart instance created by `echarts.init` and thus I have no clue how to execute `.on('click', function (params) {})` method.

Thanks.

**Comment by lesovsky** [comment]
Solved, using refs

```
<template>
    <v-chart :options="options" ref="mychart" autoresize></v-chart>
</template>

<script>
import ECharts from 'vue-echarts'
import 'echarts/lib/chart/graph'
import options from '@/assets/data.json'

export default {
  name: "Main",
  components: {
    'v-chart': ECharts
  },
  mounted () {
    this.$refs.mychart.chart.on('click', function (params) {
      console.log('lessqq:', params.data);
    })
  },
  data () {
    return {
      options: options
    }
  },
}
</script>

<style scoped>
</style>
```

**Comment by Justineo** [comment]
Doesn't the following work for you?

```html
<v-chart :options="options" autoresize @click="...">
```

**Comment by lesovsky** [comment]
Then how in such case get access to `params` ?

**Comment by Justineo** [comment]
```html
<v-chart :options="options" autoresize @click="handleClick">
```

```js
{
  // ...
  methods: {
    handleClick (params) {
      console.log(params)
    }
  }
  // ...
}
```

**Comment by lesovsky** [comment]
Yes, this works ))) Looks very simple and easy, but at the same time it isn't obvious (for me).
Thank you!

**Comment by ivanmcgregor** [comment]
@Justineo this works fine, but how would you achieve `.on('click', 'myName.line', function (params) {})` with the `@click` method? 
I have tried the ref approach for both `5.0.0-beta.0` as well as `4.1.0`, yet in both cases the ref actually is undefined when mounting so I cannot really apply the click there. My example would look similar to the one from lesovsky, but differs a bit as I am using nuxt.js.
