### ISSUE TITLE
How to set on Serie - Data a dynamic value like waiting values from request

### ISSUE THREAD

**Issue by arikardnoir** [ecomfe/vue-echarts#485]
## The type of this issue / Issue 类型

- [X] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [X] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [https://codesandbox.io/s/musing-https-9ucjw) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/musing-https-9ucjw) 上 demo 的链接：**

I Want o set value os data from series, but my values come from an request. When i open the page chart is empty.
How can i do to set the value after request? Thanks

Demo Link above

**Comment by Justineo** [comment]
https://codesandbox.io/s/headless-pine-qh20g

The problem is not related to this project, instead it's about general usage of Vue.js. You need to use `computed` in this case.

**Comment by arikardnoir** [comment]
Man Thanks, many thanks!
