### ISSUE TITLE
legend的tooltip配置无效

### ISSUE THREAD

**Issue by jeby007** [ecomfe/vue-echarts#488]
`
legend: {
          show:true,
          tooltip:{
            show:true,
            backgroundColor:'rgba(255,255,255,1)',
            padding:0,
            position:['50%','50%'],
            formatter:function (params) {
              console.log(params);
              `<div style="background: #ccc;padding-left: 10px">${params.name}</div>`
              return `<div style="max-width: 200px;word-break: normal;white-space: normal;font-size: 12px">其他收入 + 新报收入 + 续报收入</div>`
            }
          }
        },
`
配置padding、backgroundColor、position均无效

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
