### ISSUE TITLE
Transparently enable brush on the charts.

### ISSUE THREAD

**Issue by lesovsky** [ecomfe/vue-echarts#489]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

5.0.0-beta.0

I would like to transparently enable `brush` tool and don't show the toolbox. I found similar [thread](https://stackoverflow.com/questions/44941586/brush-by-default-active-on-scatter-chart) on SO where people recommend to use `_componentsViews`. This thread is quite old and was created 3 years ago. Also I found nothing about `_componentsViews` in the docs.

Is there any way to transparently enable brush in recent Echarts? Is `_componentsViews` still exist in Echarts? If it exists then how to use it using vue-echarts?

**Comment by Justineo** [comment]
This project is only a Vue.js wrapper for ECharts so we only support its public API. Thank you.
