### ISSUE TITLE
Echarts 5 Support

### ISSUE THREAD

**Issue by lz1998** [ecomfe/vue-echarts#491]
https://echarts.apache.org/next/zh/api.html#echarts

**Comment by wmn1525** [comment]
5.0 echars库的加载方式变了
`
var echarts = require('echarts');
// import echarts from 'echarts/lib/echarts'
`

**Comment by Moxie1776** [comment]
> https://echarts.apache.org/next/zh/api.html#echarts

Agreed. V5 has some very nice perk's I would like to be using.

**Comment by itaken** [comment]
> 5.0 echars库的加载方式变了
> `var echarts = require('echarts'); // import echarts from 'echarts/lib/echarts'`

看到也可以这样引入 `import * as echarts from 'echarts'`

**Comment by Moxie1776** [comment]
> > 5.0 echars库的加载方式变了
> > `var echarts = require('echarts'); // import echarts from 'echarts/lib/echarts'`
> 
> 看到也可以这样引入 `import * as echarts from 'echarts'`

That is already required for echarts 4.x and does not fix the 5.0 compatibility problems.

**Comment by Jaffsterz** [comment]
Would be really useful to get an updated on any plans to support eCharts 5.

NPM reports a version called 5.0.0-beta.0 - should we be using that? I don't see any information in the "Releases" section of github for this project so don't know what 5.0.0-beta.0 is?

**Comment by ambit-tsai** [comment]
> Would be really useful to get an updated on any plans to support eCharts 5.
> 
> NPM reports a version called 5.0.0-beta.0 - should we be using that? I don't see any information in the "Releases" section of github for this project so don't know what 5.0.0-beta.0 is?



> 5.0 echars库的加载方式变了
> `var echarts = require('echarts'); // import echarts from 'echarts/lib/echarts'`



> > https://echarts.apache.org/next/zh/api.html#echarts
> 
> Agreed. V5 has some very nice perk's I would like to be using.


I recommend [echarts-for-vue](https://github.com/ambit-tsai/echarts-for-vue#readme) which supports ECharts 5, and it is compatible with Vue 3 and 2.

**Comment by Moxie1776** [comment]
> Would be really useful to get an updated on any plans to support eCharts 5.
> 
> NPM reports a version called 5.0.0-beta.0 - should we be using that? I don't see any information in the "Releases" section of github for this project so don't know what 5.0.0-beta.0 is?

That still uses 4.x as a core instead of Echarts 5

**Comment by chris-envas** [comment]
If you use Echart5.0, so you need change require module method
```
import * as echarts from 'echarts'
```

**Comment by lesovsky** [comment]
Tried to upgrade ECharts in my project. Updated imports accordingly to ECharts 5 upgrade guide and almost all look working. 
But in console I got the errors:
```
"import echarts from 'echarts/lib/echarts'" is not supported anymore. Use "import * as echarts from 'echarts/lib/echarts'" instead;" 
```
due to old-style import in [components/ECharts.vue](https://github.com/ecomfe/vue-echarts/blob/dd6d925304f18b6aee6d2a8bfd4c74bffc20e6c4/src/components/ECharts.vue#L13)

**Comment by KSDaemon** [comment]
@lesovsky Great! How about PR? May be we can push this out of the ice :)

**Comment by lesovsky** [comment]
Not sure about PR, I have no strong skills in JS and not completely sure that my onliner will not broke something.

**Comment by anka** [comment]
Any plans for official support via the vue-echarts library itself?

**Comment by Justineo** [comment]
@anka Yes we plan to add ECharts 5 and Vue 3 support in the next release.

**Comment by Moxie1776** [comment]
> @anka Yes we plan to add ECharts 5 and Vue 3 support in the next release.

Can you give us an idea when that might be?

**Comment by Justineo** [comment]
Hi everyone, sorry for the late response.

Based on Apache ECharts 5, `vue-echarts@6` is published with support for both Vue 2 and 3. See our latest documentation [here](https://github.com/ecomfe/vue-echarts#readme).
