### ISSUE TITLE
请问为什么要使用transpileDependencies

### ISSUE THREAD

**Issue by 19Qingfeng** [ecomfe/vue-echarts#492]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts

none

## Details

我查看vue-echarts/dist目录下的代码认为已经是经过babel-loader处理过后的代码，请问为什么要在vuecli3中使用transpileDependencies在进行babel转译？

## Reproduction link / 复现链接
none

**Comment by Justineo** [comment]
https://github.com/ecomfe/vue-echarts/blob/dd6d925304f18b6aee6d2a8bfd4c74bffc20e6c4/package.json#L14

webpack 在 import 时会优先使用 `.vue` 源文件。
