### ISSUE TITLE
如何知道该手动 import 哪些模块呢

### ISSUE THREAD

**Issue by starliiit** [ecomfe/vue-echarts#495]
## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情

怎么知道哪些模块需要手动引入？我从官网上复制了一些 options，但是这些 options 并不会告诉我它需要哪些模块支持。我得到的只有一堆 Cannot ready property xxx of undefined……要手动尝试好久才能成功画出图来。

有没有什么可供参考的 options 与模块的映射关系？

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

whatever

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

no need

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**

**Comment by pissang** [comment]
https://echarts.apache.org/next/examples/zh/editor.html?c=line-simple

新版本示例页的完整代码 Tab，在选择按需引入后有显示需要引入哪些模块
