### ISSUE TITLE
Event updateAxisPointer is missing

### ISSUE THREAD

**Issue by sharkguto** [ecomfe/vue-echarts#496]
## The type of this issue / Issue 类型

- [X ] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [X ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [X ] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
```package.json
"dependencies": {
    "@fortawesome/fontawesome-free": "^5.13.0",
    "axios": "^0.19.2",
    "axios-mock-adapter": "^1.18.1",
    "buefy": "^0.8.13",
    "core-js": "^3.6.4",
    "echarts": "^4.9.0",
    "extenso": "^2.0.1",
    "fs-extra": "^9.0.1",
    "moment": "^2.27.0",
    "pdfjs-dist": "^2.5.207",
    "qs": "^6.9.4",
    "uuid": "^8.3.0",
    "vee-validate": "^3.2.5",
    "vue": "^2.6.11",
    "vue-country-flag": "^1.3.1",
    "vue-currency-input": "^1.17.3",
    "vue-echarts": "^4.1.0",
    "vue-excel-xlsx": "^1.0.11",
    "vue-friendly-iframe": "^0.18.0",
    "vue-html2pdf": "^1.8.0",
    "vue-i18n": "^8.15.6",
    "vue-json-csv": "^1.2.10",
    "vue-pdf-search-keyword": "^0.1.3",
    "vue-router": "^3.1.6",
    "vuejs-jwt": "^1.1.0",
    "vuelidate": "^0.7.5",
    "vuex": "^3.1.3",
    "vuex-persistedstate": "^2.7.1"
  },
```

## Reproduction link / 复现链接
missing updateAxisPointer event
@updateAxisPointer

https://echarts.apache.org/examples/en/editor.html?c=dataset-link I need help to implement this example with vue2

**Comment by Justineo** [comment]
This problem You can try the latest version `6.0.0-beta.2`. (Or `5.0.0-beta.0` which is mostly compatible with v4.)
