### ISSUE TITLE
按需引入dataZoom里面的属性zoomLock无效

### ISSUE THREAD

**Issue by LongYue9608** [ecomfe/vue-echarts#497]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ ] Bundled version/打包版本 (`import ECharts from 'vue-echarts/dist/vue-echarts'`)
- [x] The `.vue` component/`.vue` 组件 (`import ECharts from 'vue-echarts'`)

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your [CodeSandbox](https://codesandbox.io/s/vue) demo below:**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 [CodeSandbox](https://codesandbox.io/s/vue) 上 demo 的链接：**
### 在线链接没发写vue里面`import 'echarts/lib/component/dataZoom'`这种方式的只能用`script`这种引入`vue-echarts`,而这种方式我试过了`zoomLock:true`是可以生效的 `import`这种的`zoomLock:true`无效
我是这样用的
```
import ECharts from 'vue-echarts'
import 'echarts/lib/chart/bar'
import 'echarts/lib/chart/line'
import 'echarts/lib/chart/pie'
import 'echarts/lib/component/legend' //引入图例组件
import 'echarts/lib/component/tooltip' //引入图例组件
import 'echarts/lib/component/dataZoom'
import 'echarts/lib/component/legendScroll'
//省略
  components: {
    'v-chart': ECharts,
  },
```
###版本
```
"echarts": "^5.0.0",
"vue-echarts": "^5.0.0-beta.0",
```

**Comment by LongYue9608** [comment]
我找到问题的原因了，npm install echarts vue-echarts echarts版本现在为5.0.0 你们script例子引入版本为4.1.0,这个版本zoomLock:true是没有问题的 而5.0.0版本 zoomLock失效，[在线例子](http://jsrun.net/SSIKp)

**Comment by LongYue9608** [comment]
但是4.x版的echarts样式全变了。。。。。

**Comment by Justineo** [comment]
你可以尝试使用 `vue-echarts@6`，支持 ECharts 5。
