### ISSUE TITLE
加急！npm 包中引用echarts方式报错，请及时更新

### ISSUE THREAD

**Issue by HuRuilin** [ecomfe/vue-echarts#498]
-  Bug 报告

-  我已检查过，这个问题非 ECharts 本身的问题。

- 引入方式：(`import ECharts from 'vue-echarts'`)

###  Vue-ECharts 的版本

^5.0.0-beta.0

## 复现链接

- 描述：代码部署到线上后，控制台报错（来自：echarts.js ）【猜测echarts 引用方式更新后，vue-echarts 未及时适配】
```
"import echarts from 'echarts/lib/echarts'" is not supported anymore. Use "import * as echarts from 'echarts/lib/echarts'" instead;
```

**Comment by Justineo** [comment]
Vue-ECharts 目前还不支持 ECharts 5.0。

**Comment by HuRuilin** [comment]
建议版本是多少啊？着急上线，谢谢

**Comment by Justineo** [comment]
你要用 echarts@4.

**Comment by HuRuilin** [comment]
> 你要用 echarts@4
好的，感谢
