### ISSUE TITLE
怎么引入vue-echarts

### ISSUE THREAD

**Issue by zhumingjie1996** [ecomfe/vue-echarts#499]
echarts.js?21c7:35 "import echarts from 'echarts/lib/echarts'" is not supported anymore. Use "import * as echarts from 'echarts/lib/echarts'" instead;

`<template>
  <div class="echarts">
    <v-chart
      :style="echartStyle"
      :options="orgOptions"
      :auto-resize="true"
    ></v-chart>
  </div>
</template>

<script>
import ECharts from "vue-echarts";
import "echarts/lib/chart/line";
import "echarts/lib/component/polar";
export default {
  name: "Echarts",
  components: {
    "v-chart": ECharts,
  },`

**Comment by Justineo** [comment]
目前 vue-echarts 尚不支持 echarts@5。

**Comment by humayunkabir** [comment]
I also got this error. I removed echarts and reinstall echarts@4.9.0. It worked for me.
vue-echarts don't support echarts@5
