### ISSUE TITLE
调用getDataURL报错

### ISSUE THREAD

**Issue by 7Q1024** [ecomfe/vue-echarts#502]
![dpr错误](https://user-images.githubusercontent.com/75796582/106719378-2f727300-663d-11eb-933d-7ec84d2ea2b2.png)
您好，调用getDataURL报这个错，请问怎么解决？

##版本
echarts: 5.0.0

**Comment by 7Q1024** [comment]
这个是echarts5的bug

**Comment by Justineo** [comment]
你提这个问题的时候，Vue-ECharts 还不支持 ECharts 5……你可以尝试使用最新版的 `vue-echarts@6`。
