### ISSUE TITLE
更新到vue-charts6.0并按文档修改引入方式后，报无法找到./node_modules/vue-echarts/components/ECharts.vue

### ISSUE THREAD

**Issue by 565871779** [ecomfe/vue-echarts#509]
"echarts": "^5.0.2",
 "vue-echarts": "^6.0.0-alpha.4"
"@vue/composition-api": "^1.0.0-rc.2"
![image](https://user-images.githubusercontent.com/41174671/108828490-e1300e80-7601-11eb-8278-e3e529b3d6e4.png)

![image](https://user-images.githubusercontent.com/41174671/108828467-d2e1f280-7601-11eb-8bfb-f7078d5ddbd8.png)
![image](https://user-images.githubusercontent.com/41174671/108828515-e9884980-7601-11eb-9ffc-99240c375950.png)

**Comment by Justineo** [comment]
感觉是缓存的问题，因为新版本是不可能引入 `components/ECharts.vue` 这个文件的。你把 `node_modules/.cache` 删了重新跑一下试试？

**Comment by 565871779** [comment]
> 感觉是缓存的问题，因为新版本是不可能引入 `components/ECharts.vue` 这个文件的。你把 `node_modules/.cache` 删了重新跑一下试试？

就是缓存问题，我刚把node-modules全部删除后，就没报那个错了。而是报了另一个错
![image](https://user-images.githubusercontent.com/41174671/108831207-bf845680-7604-11eb-9c08-eb3f5478dc15.png)
然后我看文档上确实是写的 import { xxx } from 'echarts/chart'，但我根据文档链接到的echarts代码中发现应该是from 'echarts/charts'才对，然后我引入代码改成from 'echarts/charts'后就真的正常了
![image](https://user-images.githubusercontent.com/41174671/108831376-ff4b3e00-7604-11eb-9ce9-c62e562d52f3.png)
![image](https://user-images.githubusercontent.com/41174671/108831400-07a37900-7605-11eb-8fd4-ab763ef80d28.png)

**Comment by Justineo** [comment]
Oops，是文档的 typo，谢谢报告。

**Comment by shiyuanzheng** [comment]
> Oops，是文档的 typo，谢谢报告。

vue2文档部分还未修正
