### ISSUE TITLE
vue-echartv6，vue2版本开发环境和CDN环境都能显示出来，打包生成压缩环境显示不出来

### ISSUE THREAD

**Issue by zhuangxiaohui** [ecomfe/vue-echarts#511]
v6版本开发环境和CDN环境都能显示出来，打包生产压缩环境显示不出来
![image](https://user-images.githubusercontent.com/5791725/108940067-b095b680-768d-11eb-8ba1-137a5ff22c19.png)
生产压缩环境
![image](https://user-images.githubusercontent.com/5791725/108940175-d9b64700-768d-11eb-9ea5-58a89d478732.png)

**Comment by Justineo** [comment]
控制台异常信息有吗？

**Comment by zhuangxiaohui** [comment]
> 控制台异常信息有吗？

没有异常，有异常还好办，应该打包没引入vue-echart

**Comment by Justineo** [comment]
能否提供一个 GitHub repo 进行最小化复现？在 Vue CLI 新建的 Vue 2 项目中无法复现。

**Comment by zhuangxiaohui** [comment]
> 能否提供一个 GitHub repo 进行最小化复现？在 Vue CLI 新建的 Vue 2 项目中无法复现。

https://github.com/zhuangxiaohui/vue-echart-demo

**Comment by Justineo** [comment]
@zhuangxiaohui 我找到原因了，`vue-echarts@6` 依赖的 `vue-demi` 标注了 `sideEffects: false`，导致编译的时候自动注册 `@vue/composition-api` 的逻辑被优化掉了。你可以先在项目中手动注册一下：

```js
import Vue from 'vue'
import VueCompositionAPI from '@vue/composition-api'

Vue.use(VueCompositionAPI)
```

我先 reopen 了，等相关 PR 合入并发布后关闭：https://github.com/vueuse/vue-demi/pull/40

**Comment by Justineo** [comment]
可以升级 `vue-demi` 到最新版，这个问题应该已经解决了。

**Comment by ming-young** [comment]
我用了上述方法    线上环境还是没有显示啊。
