### ISSUE TITLE
new, simple example with V6, please

### ISSUE THREAD

**Issue by Moxie1776** [ecomfe/vue-echarts#512]
[Old read me link](http://https://ecomfe.github.io/vue-echarts/)

It would be awesome to have an example using version 6. I have been tinkering with a vanilla nuxt/vuetify project and I cannot get this to work with V6.

Here is the 'old' code example from the link above, which is a full, working example that is easy to follow.

    <template>
    <v-chart :options="polar"/>
    </template>

    <style>
    /**
    * The default size is 600px×400px, for responsive charts
    * you may need to set percentage values as follows (also
    * don't forget to provide a size for the container).
    */
    .echarts {
     width: 100%;
    height: 100%;
    }
    </style>

    <script>
    import ECharts from 'vue-echarts'
    import 'echarts/lib/chart/line'
    import 'echarts/lib/component/polar'

    export default {
    components: {
        'v-chart': ECharts
    },
    data () {
        let data = []

        for (let i = 0; i <= 360; i++) {
            let t = i / 180 * Math.PI
            let r = Math.sin(2 * t) * Math.cos(2 * t)
            data.push([r, i])
        }

        return {
        polar: {
            title: {
            text: '极坐标双数值轴'
            },
            legend: {
            data: ['line']
            },
            polar: {
            center: ['50%', '54%']
            },
            tooltip: {
            trigger: 'axis',
            axisPointer: {
                type: 'cross'
            }
            },
            angleAxis: {
            type: 'value',
            startAngle: 0
            },
            radiusAxis: {
            min: 0
            },
            series: [
            {
                coordinateSystem: 'polar',
                name: 'line',
                type: 'line',
                showSymbol: false,
                data: data
            }
            ],
            animationDuration: 2000
        }
        }
    }
    }
    </script>

**Comment by Justineo** [comment]
Added an [*SFC example*](https://github.com/ecomfe/vue-echarts#sfc-example) section to the README. 😄

**Comment by Moxie1776** [comment]
> Added an [_SFC example_](https://github.com/ecomfe/vue-echarts#sfc-example) section to the README. smile

thank you :)
