### ISSUE TITLE
How to import LinearGradient

### ISSUE THREAD

**Issue by pieroliviermarquis** [ecomfe/vue-echarts#515]
Is LinearGradient a part of GraphicComponents? I tried every import possible. Please indicate how to import and create a new echarts.graphic.LinearGradient. Thanks.

**Comment by Justineo** [comment]
https://github.com/ecomfe/vue-echarts/blob/121570378fcfbe331f784535e33033094a689547/src/demo/data/scatter.js#L1

**Comment by doglex** [comment]
> https://github.com/ecomfe/vue-echarts/blob/121570378fcfbe331f784535e33033094a689547/src/demo/data/scatter.js#L1

vite dev 下可以使用， vite build后报错
Cannot set properties of undefined (setting 'colorStops')
