### ISSUE TITLE
may be should add `emits` option to avoid trigger native event

### ISSUE THREAD

**Issue by Spike-Leung** [ecomfe/vue-echarts#516]
### description
when i want to listen click event on echart, i will add `@click` on  vue-echart component like this

`  <v-chart @click="onClickLine" />`

so, when click on echart graph item , it will trigger echart's `click` event and give me `clicked graph item` as param and call `onClickLine` method.

howerver, in vue3, if there is no `emits` options, `@click` will also trigger native click event, and return native click event 

obj, which will also trigger `onClickLine` method.

so, it will call `onClickLine` twice, but i only want to trigger echarts's click event, not native click event.

Surely, i can judge if is echart's event or native event, but there are too many place i need to add this code.

在组件上注册了`click`时间后，会触发两次，一次是echart的click事件，一次是原生的click事件，但其实我并不需要原生的click
事件。这似乎是因为vue3的[emtis-option](https://v3.vuejs.org/guide/migration/emits-option.html#emits-option)导致的，
如果没有在组件中描述emit出去的事件，那么就会默认触发原生事件。

### expect
may be add a props to control if we need to trigger native event ? 
是否可以增加一个props，控制是否需要原生事件呢？
thanks : )

**Comment by Justineo** [comment]
Fixed.

**Comment by Spike-Leung** [comment]
Thanks :)

**Comment by Justineo** [comment]
Native events are suppressed for now. As `.native` modifiers are removed in Vue 3, we will consider to support native events if users do need them (currently it's actually trivial to bind native events to a wrapper element).

**Comment by hbkgoing** [comment]
> Native events are suppressed for now. As `.native` modifiers are removed in Vue 3, we will consider to support native events if users do need them (currently it's actually trivial to bind native events to a wrapper element).

support native evnets right now?
