### ISSUE TITLE
finished 这个事件如何触发？

### ISSUE THREAD

**Issue by djkloop** [ecomfe/vue-echarts#517]
![image](https://user-images.githubusercontent.com/21050914/109639186-d9381780-7b89-11eb-89e5-42b9e2515542.png)
这样写不触发。。。

**Comment by Justineo** [comment]
无法复现，你能确定 `useChartRenderFinish` 没有执行吗？

**Comment by djkloop** [comment]
@Justineo 

```shell
# 上面那个问题我刚重新装了下包就好了...感谢回复
```
