### ISSUE TITLE
Charts overflow after upgrade.

### ISSUE THREAD

**Issue by lesovsky** [ecomfe/vue-echarts#518]
Hi,
After upgrading vue-echarts and echarts, at page refresh (F5) all charts widthes overflow parent v-col component.

Visually it looks like on the picture below, right side of the chart is wider than width of parent box. Width of the chart more than width of parent box - 817px vs. 765.5px.
![echarts-overflow](https://user-images.githubusercontent.com/953312/109647678-66c03b00-7b7b-11eb-8e0d-ca239396946e.png)

Later, chart's width fits into box's width, but if refresh page again it overflows again. Old version of vue-echarts worked correctly. Maybe this is related to the style changes: `Now the root element of the component have 100%×100% size by default, instead of 600×400.` ?

I tried to use different values for `width`, `min-width`, `max-width` and `box-sizing` CSS properties, but had no success.

Changed versions:
- echarts updated from `^4.9.0` to `5`
- vue-echarts updated from `^5.0.0-beta.0` to `^6.0.0-beta.3`

Chart's style is not changed during upgrade:
```
<style scoped>
.echarts {
  width: auto;
  height: 370px;
}
</style>
```

**Comment by Justineo** [comment]
It's unlikely to be caused by the component itself. Are you using the `autoresize` prop on your chart?

**Comment by lesovsky** [comment]
Yes, `autoresize` is used. I tried to remove the prop, but it doesn't help.

**Comment by lesovsky** [comment]
Also in case of removing `height` (or set it to 'auto') CSS property from style, finally chart's height calculates as `0` and chart is not showing.

**Comment by lesovsky** [comment]
I made a [fiddle](https://jsfiddle.net/lesovsky/7sjvcnu2/266/) with problem illustrated (`Bottom results` layout have to be enabled in the Settings).
When page is rendered, both charts don't fir into parent card blocks. After clicking on navbar button (for hide and show navbar) charts are resized and charts fit into cards now.

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/109912063-55477200-7ce6-11eb-81b1-714904d60c99.png)

I still cannot reproduce this with your fiddle. Isn't this working as expected?

**Comment by lesovsky** [comment]
Try with wide "Bottom Result" layout.
There should be like this:

1. Charts don't fit into cards at first render.
![fiddle-1](https://user-images.githubusercontent.com/953312/109918720-44443400-7cd9-11eb-8ae9-66ce68f45522.png)

2. Click the button to hide NavBar and charts autoresized and fit into the cards.
![fiddle-2](https://user-images.githubusercontent.com/953312/109918721-44dcca80-7cd9-11eb-9f94-0f40c5370722.png)

3. Click the button to show NavBar again, charts auto-resized and look good as expected in the first render.
![fiddle-3](https://user-images.githubusercontent.com/953312/109918722-44dcca80-7cd9-11eb-9bae-18d258deadab.png)

**Comment by Justineo** [comment]
Thanks for the reproduction! You can upgrade to `6.0.0-beta.7` to see if it's fixed.

**Comment by lesovsky** [comment]
Thanks, with `6.0.0-beta.7` it works.

There is a very short period (few milliseconds) between render and resizing, but I think this is not critical.
