### ISSUE TITLE
vue-echarts 6.0  echarts5.0 单文件引入 报错Object(...) is not a function

### ISSUE THREAD

**Issue by YorkZhangZ** [ecomfe/vue-echarts#519]
![image](https://user-images.githubusercontent.com/25559727/109769622-6dab8400-7c35-11eb-8aef-345264adde26.png)

**Comment by cjjlovedsn** [comment]
vue-demi中不存在mergeProps方法导致的错误

**Comment by mishengqiang** [comment]
in ./node_modules/vue-echarts/dist/index.esm.min.js

"export 'mergeProps' (imported as 'v') was not found in 'vue-demi'

**Comment by YorkZhangZ** [comment]
> vue-demi中不存在mergeProps方法导致的错误

vue-demi 这文件我看着是node_modules里的，我这里该怎么处理呢

**Comment by mishengqiang** [comment]
> > vue-demi中不存在mergeProps方法导致的错误
> 
> vue-demi 这文件我看着是node_modules里的，我这里该怎么处理呢

我看了源码vue-demi中的mergeProps来自Vue，但是只有最新的Vue3有[这个API](https://v3.vuejs.org/api/global-api.html#mergeprops)，vue2.x是没有的。

**Comment by Justineo** [comment]
应该是 `@vue/composition-api` 不支持 `mergeProps` 导致的，我们自己处理一下，不直接引入了。

See https://github.com/vuejs/composition-api/pull/390#issuecomment-647488094-permalink:~:text=mergeProps

**Comment by Justineo** [comment]
Fixed in `6.0.0-beta.5`.

**Comment by Ice-Hazymoon** [comment]
TypeError:Object(...) is not a function

这个问题貌似依旧存在

echarts 5.3.2
vue-echarts 6.0.3
nuxt 2.15.8
@nuxtjs/composition-api 0.32.0

```
TypeError:Object(...) is not a function

import {watch as e, inject as t, computed as n, unref as o, watchEffect as r, defineComponent as i, shallowRef as a, toRefs as u, onMounted as c, onUnmounted as s, h as l, Vue2 as p, nextTick as v} from "vue-demi";
```

**Comment by Justineo** [comment]
@Ice-Hazymoon 请提交一个新的bug，并且提供一下最小的复现场景，谢谢。

**Comment by oushu1suzhijie1** [comment]
> Ice-Hazymoon

请问最后如何解决了

**Comment by lardern** [comment]
可以看看是不是与我同样的问题：https://github.com/ecomfe/vue-echarts/issues/824#issuecomment-3077437662
