### ISSUE TITLE
no exported member named 'DefineComponent'

### ISSUE THREAD

**Issue by qiwang97** [ecomfe/vue-echarts#520]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> 6.0.0-beta.7

Great work to join Vue and Echarts.
I try to use echartjs but errors occur.
It says

```
ERROR in /path/to/node_modules/vue-echarts/dist/index.d.ts(1,90):
1:90 Module '"../../vue-demi/lib/index.js"' has no exported member 'AllowedComponentProps'.
  > 1 | import { DefineComponent, PropType, Ref, ComputedRef, ComponentOptionsMixin, VNodeProps, AllowedComponentProps, ComponentCustomProps } from 'vue-demi';
      |                                                                                          ^
    2 | import { ECBasicOption } from 'echarts/types/dist/shared';
    3 | import { init } from 'echarts/core';
    4 | import styleInject from '../node_modules/style-inject/dist/style-inject.es.js';

ERROR in  /path/to/node_modules/vue-echarts/dist/index.d.ts(1,113):
1:113 Module '"../../vue-demi/lib/index.js"' has no exported member 'ComponentCustomProps'.
  > 1 | import { DefineComponent, PropType, Ref, ComputedRef, ComponentOptionsMixin, VNodeProps, AllowedComponentProps, ComponentCustomProps } from 'vue-demi';
      |                                                                                                                 ^
    2 | import { ECBasicOption } from 'echarts/types/dist/shared';
    3 | import { init } from 'echarts/core';
    4 | import styleInject from '../node_modules/style-inject/dist/style-inject.es.js';

```

![image](https://user-images.githubusercontent.com/37304367/110010095-e5260400-7d58-11eb-8074-91eeeb464c64.png)

Other info:
```
    "@vue/composition-api": "^1.0.0-rc.2",
    "echarts": "^5.0.2",
    "vue-echarts": "^6.0.0-beta.7",
    "vue-i18n": "^8.21.0",
    "vue-router": "^3.4.9",
    "vuex": "^3.4.0",
   "typescript": "^4.1.3",
    "vue-template-compiler": "^2.6.11",
    "vuex-ts-enhance": "^0.0.5"

```

Is it the types error? What should i do?

I add a mini [demo](https://github.com/qiwang97/vue-echarts-issues-520) here

**Comment by qiwang97** [comment]
I add i mini [demo](https://github.com/qiwang97/vue-echarts-issues-520).

**Comment by Justineo** [comment]
It's probably because `index.d.ts` from `vue-echarts` is generated under a Vue 3 environment. It's indeed a known issue but without easy workarounds now. We'll need some time to figure it out.

**Comment by qiwang97** [comment]
My friend adds ` "skipLibCheck": true` in `tsconfig.json` and it works.
But I think more work to do to fix it without ignoring errors.

**Comment by Justineo** [comment]
> My friend adds ` "skipLibCheck": true` in `tsconfig.json` and it works.

This will ignore all `.d.ts` checks which might not be something you want.

**Comment by Justineo** [comment]
Hi, can you provide the reproduction steps for your problem? I tried to create a Vue 2 + TS project with Vue CLI and it doesn't complain about type errors.

**Comment by qiwang97** [comment]
> Hi, can you provide the reproduction steps for your problem? I tried to create a Vue 2 + TS project with Vue CLI and it doesn't complain about type errors.

https://github.com/qiwang97/vue-echarts-issues-520

**Comment by Justineo** [comment]
Hi, can you please try `vue-echarts@6.0.0-rc.3`? We added a `postinstall` script so that type checks will be skipped for `vue-echarts`'s default export and you don't need to use `skipLibCheck: true` anymore.
