### ISSUE TITLE
文档中有错误

### ISSUE THREAD

**Issue by kiccer** [ecomfe/vue-echarts#522]
错误位置：https://github.com/ecomfe/vue-echarts/blob/main/README.zh-Hans.md#%E5%8D%95%E6%96%87%E4%BB%B6%E7%BB%84%E4%BB%B6%E7%A4%BA%E4%BE%8B
错误内容：
```html
<v-chart class="chart" :option="option" />
```
应为
```html
<v-chart class="chart" :options="option" />
```

我直接复制了文档里的代码，然后运行后无效，不渲染canvas元素，排查好久才发现，组件props为`options`。

**Comment by Justineo** [comment]
这是新版本的文档，的确是 `option`。老版本的文档请查看 `5.x` 分支，我在新版文档上加个链接去。

**Comment by kiccer** [comment]
嗷，这样啊

**Comment by su7max** [comment]
Worked! :ambulance::ambulance::ambulance:
