### ISSUE TITLE
vue2.x版本中局部引入组件报: Renderer 'undefined' is not imported. Please import it first.

### ISSUE THREAD

**Issue by 565871779** [ecomfe/vue-echarts#523]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x ] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [ x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-rc.3

![image](https://user-images.githubusercontent.com/41174671/110735469-d2ce2d80-8264-11eb-9d6c-c25647dead1d.png)
![image](https://user-images.githubusercontent.com/41174671/110735523-e9748480-8264-11eb-98d2-15b6854792d4.png)

![image](https://user-images.githubusercontent.com/41174671/110735401-b7632280-8264-11eb-93ea-769c131e53ee.png)

但若使用import 'echarts'全量引入就能正常显示图表

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/110736608-ed090b00-8266-11eb-9ac9-2ac15cec44f4.png)
你编辑器的报错已经提示你了，引入以后没有用 `echarts` 的 `use` 方法注册。
