### ISSUE TITLE
Label 显示在折线下面，层级问题。

### ISSUE THREAD

**Issue by mishengqiang** [ecomfe/vue-echarts#527]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-beta.5

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your CodeSandbox demo below: ([Vue 3 template](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 template](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue))**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 CodeSandbox 上 demo 的链接：（[Vue 3 模板](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 模板](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue)）**

国内打不开这模板网站！

描述：label有时候在折线的下一层。
复现：请把下面的代码复制粘贴到[这里](https://echarts.apache.org/examples/zh/editor.html?c=line-smooth)的左侧代码区域，将鼠标放到右侧图表的x轴 Thu 位置就能看到 label 会被遮挡。具体看图。
代码：
```js
option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
        axisPointer: {
            show: true,
            type: "line",
            lineStyle: {
              color: "#E5E6E8",
              type: "solid",
            },
            label: {
              show: false,
            },
            z: 0,
          },
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 9346, 12906, 1330, 1320],
        type: 'line',
        smooth: true,
        showSymbol: false,
        symbolSize: 10,
        emphasis: {
          label: {
            show: true,
            position: "top",
            padding: [6, 10],
            color: "#fff",
            backgroundColor: "rgba(0,0,0,0.7)",
            borderRadius: 4,
          },
        },
    }]
};
```

![image](https://user-images.githubusercontent.com/9413032/110915101-31bda080-8352-11eb-8ad1-0e59a188b1f6.png)

**Comment by Justineo** [comment]
> * [ ]  I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

你好，让你填这个的意思就是，这个项目不负责修复 ECharts 本身的问题，请给 ECharts 项目提交 bug report。
