### ISSUE TITLE
LineChart error: xAxis [0] not found

### ISSUE THREAD

**Issue by sondh0127** [ecomfe/vue-echarts#528]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。
[`https://echarts.apache.org/examples/en/editor.html?c=area-basic
`](https://echarts.apache.org/examples/en/editor.html?c=area-basic
)
### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-beta.5

## Reproduction link / 复现链接

https://codesandbox.io/s/linecharterror-u9qw7

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/111102937-3370a980-8588-11eb-9389-4f3b1e52110d.png)

按需加载的时候你漏了 `GridComponent`。
