### ISSUE TITLE
 SyntaxError Unexpected token 'export'

### ISSUE THREAD

**Issue by Moxie1776** [ecomfe/vue-echarts#536]
- [x] Bug report / Bug 报告

### Vue version / Vue 版本
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`

### The version of Vue-ECharts you are using / Vue-ECharts 的版本
vue-echarts 6.0.0-beta.5
echarts 5.0.2
nuxt 2.15.4

## Reproduction link / 复现链接
https://codesandbox.io/s/keen-bird-8eb1p?file=/pages/index.vue
- occurs on launch
- if you navigate to an invalid link and then select the link to navigate to the chart comes up with no error
- after it comes up while you are on that page if a refresh is done the error comes back

**Comment by treetopdevs** [comment]
I am having this issue as well.  Webpack, Vue 2 in the browser.

**Comment by lesovsky** [comment]
Have the same issue after upgrading ECharts and vue-echarts in one of my projects
Packages version changes:
- `echarts 4.9.0` -> `echarts 5.0.2`
- `vue-echarts 5.0.0-beta.0` -> `vue-echarts 6.0.0-rc.4`
- `vue 2.6.11` -> `vue 2.6.12`
- `nuxt 2.15.3` (is not changed)


Everything worked fine before upgrade.

**Comment by Justineo** [comment]
Are you all experiencing this only with Nuxt? @Moxie1776 @treetopdevs

**Comment by Moxie1776** [comment]
> Are you all experiencing this only with Nuxt? @Moxie1776 @treetopdevs 

I haven't tried it w/o nuxt since the only project I code on is a nuxt project, and yes I am still having the problem.

**Comment by Moxie1776** [comment]
> Are you all experiencing this only with Nuxt? @Moxie1776 @treetopdevs

I haven't tried it w/o nuxt since the only project I code on is a nuxt project, and yes I am still having the problem.

**Comment by lesovsky** [comment]
I have another project on pure VueJS where ECharts and vue-echarts were upgraded a month ago, and there was no such problem. I think this problem `Unexpected token 'export'` is Nuxt specific, because when I looked for the solutions I found a lot of similar problems with another packages (not ECharts) and almost all of them were related to Nuxt only.

**Comment by lesovsky** [comment]
Solved this using the following approach.

1. Create new Nuxt plugin `~/plugins/vue-echarts.js`. Specify modules needed for you.
```
import { use } from 'echarts/core'
import { CanvasRenderer } from 'echarts/renderers'
import { GraphChart } from 'echarts/charts'
import { TitleComponent } from 'echarts/components'

import Vue from 'vue'
import VChart from 'vue-echarts'

use([
  CanvasRenderer,
  GraphChart,
  TitleComponent
])

Vue.use(VChart)

```

2.  Add created plugin and specify `build.transpile` setting in `nuxt.config.js`.
```
export default {
  plugins: [
    { src: '~/plugins/vue-echarts', ssr: false }
  ],

  build: {
    transpile: [
      'vue-echarts',
      'echarts/core',
      'echarts/renderers',
      'echarts/charts',
      'echarts/components',
      'zrender'
    ]
  }
}

```

3. Use in component
```
<template>
  <div>
    <client-only>
      <v-chart ref="diagram" autoresize :option="option" />
    </client-only>
  </div>
</template>

<script>
import VChart from 'vue-echarts'

export default {
  name: 'Diagram',
  components: {
    'v-chart': VChart
  },
  data () {
    return {
      option: {
      // define chart options here
      }
    }
  }
}
</script>
```

I'm newbie in VueJS/Nuxt and this might be suboptimal, but it works for me. Maybe this also could be placed into README.

**Comment by Justineo** [comment]
You can work around this by adding the following config in `nuxt.config.js`:

```js
  build: {
    transpile: [/echarts/, /zrender/]
  }
```

**Comment by Moxie1776** [comment]
> You can work around this by adding the following config in `nuxt.config.js`:
> 
> ```js
>   build: {
>     transpile: [/echarts/, /zrender/]
>   }
> ```

I removed the vue-echarts from the transpile and updated it to read exactly as you list here. It is now working in the following [codesandbox](https://codesandbox.io/s/thirsty-shirley-c6tfx?file=/nuxt.config.js). Thank you for looking into this.

**Comment by Justineo** [comment]
I’m closing this issue. I’ll put the caveats in the docs later. Thank you all for providing info :)

**Comment by alikamrani** [comment]
i have the sam issue . but none of those thing that you mentioned above not works for me . i already create a new nuxt project and add the code that you use in [this](https://codesandbox.io/s/thirsty-shirley-c6tfx?file=/nuxt.config.js) . but nuxt return Unexpected token 'export' for me .

**Comment by itmysm** [comment]
The solution in Vue3 + Nuxt3 is like this

-1 create a plugin in `plugins folder` with `echarts.client.ts` name and add your codes like this

![echarts-nuxt3-codes](https://user-images.githubusercontent.com/75526205/196654164-009a7ae8-411a-45d5-a018-1aa1127d4cc3.png)

-2 use echarts plugin in your project

![code](https://user-images.githubusercontent.com/75526205/196654734-e15d9072-73ff-4c13-8dea-25fe0eee9d09.png)

* If you still have this problem, you can look at [this project](https://github.com/itmysm/graph-project)
