### ISSUE TITLE
是否有可能放宽依赖Vue 2的版本限制

### ISSUE THREAD

**Issue by ztyzbb** [ecomfe/vue-echarts#538]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-beta.5
6.0.0-rc.4

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your CodeSandbox demo below: ([Vue 3 template](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 template](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue))**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 CodeSandbox 上 demo 的链接：（[Vue 3 模板](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 模板](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue)）**

目前要求Vue 2 版本 >= 2.6.12，由于一些原因，目前使用的是2..6.10，升级较为困难，请问是否有可能放宽版本要求？

**Comment by Justineo** [comment]
2.6.10 升级到 2.6.12 没有 breaking change，是哪里升级比较困难？

**Comment by ztyzbb** [comment]
@Justineo 因为我们是通用框架+子系统的模式，框架通过异步加载组件的形式加载各个子系统的代码，最终在页面上形成一个SPA，如果要改版本，需要框架以及各个系统一起更改

**Comment by Justineo** [comment]
决定不放宽了，v2.6.11 有过一个安全性升级，我们就保留 `^2.6.12` 了。
