### ISSUE TITLE
Update data from sibling component

### ISSUE THREAD

**Issue by fmmattioni** [ecomfe/vue-echarts#541]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

`"vue-echarts": "^6.0.0-rc.4"`

---

This is my scenario:

I have a page where a load two components:

```vue
<template>
    <div>
        <component-a />
        <component-b />
    </div>
</template>
```

In `ComponentA` I have a calendar where I can select a given date. Once the date is changed, I then request some data from an API.

In `ComponentB` I have an `Echart`:

```vue
<template>
    <v-chart
      class="__chart"
      :option="this.$store.state.chartData"
    />
</template>
```

As you can see, I made the `option` as the data in the store that I use for this page.

Therefore, what I do is that once I get the data from the API in `ComponentA`, I save this data in `chartData`. The goal was to then automatically update the data in `ComponentB`.

The issue is that I get the following error messages:

```
[Vue warn]: Error in nextTick: "Error: `setOption` should not be called during main process."
```

```
Error: `setOption` should not be called during main process.
```

Any ideas?

**Comment by Justineo** [comment]
Please provide a runnable and minimal reproduction. Thank you.

**Comment by fmmattioni** [comment]
Thank you.

I have just found out that this was caused for not setting `yAxis` in `chartData`. Everything is working now.
