### ISSUE TITLE
在vue-echarts6.00-rc.4中是否继续支持setOption中的notMerge变化？

### ISSUE THREAD

**Issue by yang-mengyue** [ecomfe/vue-echarts#543]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-rc.4
![image](https://user-images.githubusercontent.com/78328465/115990185-82344900-a5f4-11eb-8184-2c1fd0305413.png)

6.0.0-rc.4是否继续支持以上方法？现在出现了删除一个series中的对象，并且从新复制option给v-echarts,但是图无反应？

**Comment by Justineo** [comment]
参考 [`update-options`](https://github.com/ecomfe/vue-echarts/blob/main/README.zh-Hans.md#user-content-prop:~:text=update%2Doptions,-%3A) prop，也可以用相关的 `provide` 接口。
