### ISSUE TITLE
toolbox/restore does not restore graph after zooming the data

### ISSUE THREAD

**Issue by Moxie1776** [ecomfe/vue-echarts#545]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [X] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。
I am unable to reproduce the problem using the echarts example page

- [X] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [X] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [X] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-beta.5
vue-echarts 6.0.0-beta.5
echarts 5.1.0

## Reproduction link / 复现链接
https://codesandbox.io/s/adoring-shadow-sx231?file=/package.json

#### Steps to reproduce
use the sliders to zoom the data
hit the restore button in the toolbox in the upper right corner (I have labeled as reset when hovering over it)

**Comment by Justineo** [comment]
Please provide a minimal reproduction. (Fork [this](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue) and remove all irrelevant logic).

**Comment by Moxie1776** [comment]
> Please provide a minimal reproduction. (Fork [this](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue) and remove all irrelevant logic).

The only part of the example that was unessential was an auto resize function, which I just remove. I'm not sure how I would demonstrate a chart reset after datazoom on a pie chart. The problem is after the chart is zoomed and the toolbox restore option is used the chart is emptied but never restores the data and is simply blank.

This seems to only be a problem when it has a zoom slider for both X and Y axis. This is a minimal pre

**Comment by Justineo** [comment]
The restore button will reset the `option` to the first time it is set. You are updating the option after the component is mounted so by restoring it means you'll get the initial data (which doesn't show anything). I believe the code is working as expected.

**Comment by Moxie1776** [comment]
> The restore button will reset the `option` to the first time it is set. You are updating the option after the component is mounted so by restoring it means you'll get the initial data (which doesn't show anything). I believe the code is working as expected.

Please show me a working example if this is how it is intended to work that will restore the graph to the default view when the restore button is clicked.

https://echarts.apache.org/examples/en/editor.html?c=mix-zoom-on-value&theme=dark I disagree that this is working as intended. This is not how it works in the examples and this is definitely not how this worked in prior version of vue-echarts. If a solution to this is not found I am going to have to use something other than vue-echarts.

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/117390507-e6260e00-af20-11eb-9056-da116e324c6a.png)

You can try setting an empty option first. By pressing the "restore" button you'll get an empty chart.

**Comment by Moxie1776** [comment]
When restore is pressed before it would reset my zoom to the default values, or assigned values of start and end if I had assigned them, and it would chart the values in dataset.source It no longer does that. I'm not seeing a restore event on the echarts example page forcing me to setOption(option) when the restore button is pressed in order it to chart data.

If I am not understanding something correct please help me out. From what I can ascertain this is not functioning correctly.

**Comment by Justineo** [comment]
The “restore” feature is not designed for resetting data zoom but for resetting the `option` to its initial value and then rerender the whole chart. The key point here is that you are providing an initial `option` value that won't render anything and then adding data to it. This way by pressing the restore button ECharts will return to its first rendered state, which is empty.

**Comment by Moxie1776** [comment]
> The “restore” feature is not designed for resetting data zoom but for resetting the `option` to its initial value and then rerender the whole chart. The key point here is that **you are providing an initial `option` value that won't render anything and then adding data to it in the `mounted` hook**. This way by pressing the restore button ECharts will return to its first rendered state, which is empty.

Perhaps the Chinese version of the help file is more clear because the English version does not specify.

Either the previous version is broken or this version is because the 2 do not perform the same way. Once the variable dataset.source had a value I was never required to re-populate it in order to get the chart to show data, but I think I have made that clear. When I inspect dataset.source, before and after a reset, it is not empty.

I see no reason to debate it further. It is clear you believe it is functioning 'as intended' currently and since you are the developer I will have to acquiesce.

**Comment by Justineo** [comment]
I mean I checked ECharts itself and it’s how it works. If you think it’s a bug you should report it to apache/echarts instead.

**Comment by Moxie1776** [comment]
Thank you for taking the time to check this
