### ISSUE TITLE
Missed console log in last release

### ISSUE THREAD

**Issue by dvago** [ecomfe/vue-echarts#550]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

6.0.0-rc.5

From the Echarts.ts file:

Line 66 - 68
```
created() {
    console.log(this);
},
```

You might want to consider a lint option to warn/break the commit/push when `console.log`s are left in your code

**Comment by Justineo** [comment]
> You might want to consider a lint option to warn/break the commit/push when `console.log`s are left in your code

Yeah, you are right. Thank you.

**Comment by GermanRodrickson** [comment]
Hi! any news on this issue? :)

**Comment by Justineo** [comment]
Fixed in `vue-echarts@6.0.0-rc.6`.
