### ISSUE TITLE
dataset in option not working

### ISSUE THREAD

**Issue by hxgqh** [ecomfe/vue-echarts#555]
> Vue3 
> vue-echarts 6.0.0
> ECharts 5.1.1

sandbox: https://codesandbox.io/s/jolly-ellis-hu64g?file=/src/App.vue

option works in echarts official site: https://echarts.apache.org/examples/zh/editor.html?c=pie-simple

option:

```json
{
  "title": {
    "text": "ECharts 基础饼图"
  },
  "dataset": {
    "source": [
      {
        "product": "衬衫",
        "sales": 5
      },
      {
        "product": "羊毛衫",
        "sales": 20
      },
      {
        "product": "雪纺衫",
        "sales": 36
      },
      {
        "product": "裤子",
        "sales": 10
      },
      {
        "product": "高跟鞋",
        "sales": 10
      },
      {
        "product": "袜子",
        "sales": 20
      }
    ]
  },
  "series": [
    {
      "type": "pie"
    }
  ]
}
```

**Comment by zhyt0520** [comment]
just import `DatasetComponent`

![Snipaste_2021-06-18_15-20-06](https://user-images.githubusercontent.com/10279099/122522690-d124ba80-d048-11eb-9c29-4e9ff14ea81d.png)

**Comment by Justineo** [comment]
As @zhyt0520 said, you need to import and use the `DatasetComponent`.
