### ISSUE TITLE
使用例子引用进去报错 项目无法运行

### ISSUE THREAD

**Issue by 1046492212** [ecomfe/vue-echarts#556]
These dependencies were not found:

* echarts/components in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/financeManage/costManage/BomHistoryCost.vue
* echarts/core in ./node_modules/vue-echarts/dist/index.esm.min.js, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/financeManage/costManage/BomHistoryCost.vue
* echarts/renderers in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/financeManage/costManage/BomHistoryCost.vue

To install them, you can run: npm install --save echarts/charts echarts/components echarts/core echarts/renderers

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
