### ISSUE TITLE
按照文档一步步操作以后，会报错

### ISSUE THREAD

**Issue by 1046492212** [ecomfe/vue-echarts#557]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

## Details / 详情
These dependencies were not found:
按照步骤一步步按照 使用运行会报如下错误
    echarts/components in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/financeManage/costManage/BomHistoryCost.vue
    echarts/core in ./node_modules/vue-echarts/dist/index.esm.min.js, ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/financeManage/costManage/BomHistoryCost.vue
    echarts/renderers in ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/financeManage/costManage/BomHistoryCost.vue

To install them, you can run: npm install --save echarts/charts echarts/components echarts/core echarts/renderers
### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> 最新版

## Reproduction link / 复现链接

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your CodeSandbox demo below: ([Vue 3 template](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 template](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue))**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 CodeSandbox 上 demo 的链接：（[Vue 3 模板](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 模板](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue)）**

**Comment by Justineo** [comment]
> 按照步骤一步步按照 使用运行会报如下错误

你安装 `echarts` 了吗？

**Comment by 1046492212** [comment]
执行了文档中的 npm install echarts vue-echarts 
但是会报错，查看版本后发现  echarts 安装的是4.9版本，vue-echarts 是6.0版本，将echarts 升级到了最新版问题得以解决，

**Comment by 1046492212** [comment]
建议文档中的  npm安装语句  指定下版本

**Comment by Justineo** [comment]
![image](https://user-images.githubusercontent.com/1726061/118943425-2f954500-b986-11eb-9c76-cb2054e4f702.png)

你如果没有安装过 `echarts`，默认安装的就会是符合要求的版本。
