### ISSUE TITLE
关于再次渲染数据问题

### ISSUE THREAD

**Issue by 1046492212** [ecomfe/vue-echarts#560]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [ ] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> 最新版本

## Reproduction link / 复现链接
第一次初始化以后，修改数据，减少两条数据，重新渲染的时候，数据渲染会不正常，图表还是原来的数据

**For bug reports, please provide the steps to reproduce and if possible a minimal demo of the problem. Please paste the link to your CodeSandbox demo below: ([Vue 3 template](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 template](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue))**

**对于 Bug 报告，请在下面提供复现的步骤，最好是最小化的能够重现问题的 demo。请在下方贴入在 CodeSandbox 上 demo 的链接：（[Vue 3 模板](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 模板](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue)）**

**Comment by Justineo** [comment]
请提供一个可执行的复现环境，谢谢。

**Comment by 1046492212** [comment]
我的是折线图，数据如果多与之前的数据可以重新渲染，但是如果数据少与之前的数据，就不会渲染，
比如说第一个图渲染5条数据，但是第二次我之渲染4条，那么折线图不会有改动，

**Comment by 1046492212** [comment]
抱歉没办法提供复现环境，应为是在公司的内网，
代码是这样写的
this.option.legend.data = [];
        this.option.series = [];
        for (let x in res.Data) {
          this.option.legend.data.push(res.Data[x].Name);
          this.option.series.push({
            name: res.Data[x].Name,
            type: "line",
            smooth: true,
            data: res.Data[x].Data,
          });
          this.init = true;
        }

**Comment by Justineo** [comment]
最小化实现不需要你贴完整的代码，你把关键的部分拿出来简化一下就可以了。直接这样提 issue 我们没有办法提供帮助。

**Comment by gongym12138** [comment]
> 抱歉没办法提供复现环境，应为是在公司的内网，
> 代码是这样写的
> this.option.legend.data = [];
> this.option.series = [];
> for (let x in res.Data) {
> this.option.legend.data.push(res.Data[x].Name);
> this.option.series.push({
> name: res.Data[x].Name,
> type: "line",
> smooth: true,
> data: res.Data[x].Data,
> });
> this.init = true;
> }

可以看下是不是这个配置的问题，我好像遇到过类似的问题。后来检查是这个配置没有配置正确
https://echarts.apache.org/zh/api.html#echartsInstance.setOption

**Comment by 1046492212** [comment]
配置没问题的，我把组件加了一个v-if 每次重新加载数据先false再true，然后就可以了；
第一次加载数据的配置文件如下：
{"title":{"text":"单价Top5 PN历史趋势图"},"tooltip":{"trigger":"axis"},"legend":{"data":["A30-0BF-RD5-01EA","A30-0BF-RD5-02EU","A30-0BF-RD5-01E0","A30-0BF-RD5-04E0","A30-0BA-RD5-04E0"]},"grid":{"left":"3%","right":"4%","bottom":"3%","containLabel":true},"toolbox":{"feature":{"saveAsImage":{}}},"xAxis":{"type":"category","boundaryGap":false,"data":["21-05","21-04","21-03","21-02","21-01","20-12","20-11","20-10","20-09","20-08","20-07","20-06"]},"yAxis":{"type":"value"},"series":[{"name":"A30-0BF-RD5-01EA","type":"line","smooth":true,"data":[515.44,0,0,0,0,0,0,0,0,0,0,0]},{"name":"A30-0BF-RD5-02EU","type":"line","smooth":true,"data":[444.62,0,0,0,0,0,0,0,0,0,0,0]},{"name":"A30-0BF-RD5-01E0","type":"line","smooth":true,"data":[431.14,0,0,0,0,0,0,0,0,0,0,0]},{"name":"A30-0BF-RD5-04E0","type":"line","smooth":true,"data":[431.03,0,0,0,0,0,0,0,0,0,0,0]},{"name":"A30-0BA-RD5-04E0","type":"line","smooth":true,"data":[408.91,0,0,0,0,0,0,0,0,0,0,0]}]}

第二次加载的配置文件如下：
{"title":{"text":"单价Top5 PN历史趋势图"},"tooltip":{"trigger":"axis"},"legend":{"data":["A35-0UL-RD6-01AU"]},"grid":{"left":"3%","right":"4%","bottom":"3%","containLabel":true},"toolbox":{"feature":{"saveAsImage":{}}},"xAxis":{"type":"category","boundaryGap":false,"data":["21-05","21-04","21-03","21-02","21-01","20-12","20-11","20-10","20-09","20-08","20-07","20-06"]},"yAxis":{"type":"value"},"series":[{"name":"A35-0UL-RD6-01AU","type":"line","smooth":true,"data":[364.5,0,0,0,0,0,0,0,0,0,0,0]}]}

核心代码：
option: {
        title: {
          text: "单价Top5 PN历史趋势图",
        },
        tooltip: {
          trigger: "axis",
        },
        legend: {
          data: [],
        },
        grid: {
          left: "3%",
          right: "4%",
          bottom: "3%",
          containLabel: true,
        },
        toolbox: {
          feature: {
            saveAsImage: {},
          },
        },
        xAxis: {
          type: "category",
          boundaryGap: false,
          data: ["21-05",
            "21-04",
            "21-03",
            "21-02",
            "21-01",
            "20-12",
            "20-11",
            "20-10",
            "20-09",
            "20-08",
            "20-07",
            "20-06"],
        },
        yAxis: {
          type: "value",
        },
        series: [],
      },
      
  取到数据后赋值
  this.option.legend.data = [];
        this.option.series = [];
        for (let x in res.Data) {
          this.option.legend.data.push(res.Data[x].Name);
          this.option.series.push({
            name: res.Data[x].Name,
            type: "line",
            smooth: true,
            data: res.Data[x].Data,
          });
        }

**Comment by Justineo** [comment]
我再说一遍：请提供一个**可执行**的复现环境，谢谢。

Issue 模板里面都提供了复现环境模板链接了，请帮忙填充一下。

**Comment by Justineo** [comment]
如果有可执行的复现环境，可以重新提一个 issue，这个我先关闭了。

**Comment by xdlumia** [comment]
我也遇到这个问题了.头大.比如给series 里 push了多条数据.可以正常渲染.如果删除数据就不能渲染了

**Comment by Justineo** [comment]
@xdlumia

> 如果有可执行的复现环境，可以重新提一个 issue，这个我先关闭了。

**Comment by xdlumia** [comment]
> @xdlumia
> 
> > 如果有可执行的复现环境，可以重新提一个 issue，这个我先关闭了。

不好意思是我的问题.需要配置 'UPDATE_OPTIONS_KEY' 里的 notMerge为true .

**Comment by bohaothu** [comment]
@xdlumia 非常谢谢你！我同样遇到数据变少时不会重新渲染的问题，照你说的设置 `UPDATE_OPTIONS_KEY` 为 trure 后就解决了
