### ISSUE TITLE
resize延迟时间是否可以自定义

### ISSUE THREAD

**Issue by bf109f** [ecomfe/vue-echarts#562]
> ## Help / 帮助
>
> Replace the `[ ]` with `[x]` to check an option. / 将 `[ ]` 替换为 `[x]` 以选择对应选项。

## The type of this issue / Issue 类型

- [x] Feature request / 新特性需求
- [ ] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [ ] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [x] Vue 3
- [x] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

> eg. 6.0.0-beta.5

## Reproduction link / 复现链接

if (this.autoResize) {
        this.__resizeHanlder = debounce(() => {
          chart.resize()
        }, 100, { leading: true })
        window.addEventListener('resize', this.__resizeHanlder)
      }

**Comment by bf109f** [comment]
如果传了设置为用户传的值，不传默认100

**Comment by bf109f** [comment]
如果传了设置为用户传的值，不传默认100

**Comment by coader** [comment]
同样问题 如果父节点使用了动效 transition echarts就会发生闪烁

**Comment by Justineo** [comment]
Implemented in `v6.6.0`. Now `autoresize` accepts an options object like `{ throttle: 300 }` so that you can specify a custom throttle delay.
