### ISSUE TITLE
getOption() returns undefined when "autoresize" is being used

### ISSUE THREAD

**Issue by nick-true-dev** [ecomfe/vue-echarts#568]
## The type of this issue / Issue 类型

- [ ] Feature request / 新特性需求
- [x] Bug report / Bug 报告

## Not introduced by ECharts / 非 ECharts 本身问题

Problems about ECharts itself are not handled in this repo. / 本 repo 不负责处理 ECharts 本身的问题。

- [x] I've checked it's not a problem of ECharts itself. / 我已检查过，这个问题非 ECharts 本身的问题。

### Vue version / Vue 版本

- [x] Vue 3
- [ ] Vue 2

### How are you importing Vue-ECharts? / 你是如何引入 Vue-ECharts 的？

- [x] Importing `vue-echarts` with a bundler environment / 在 webpack 等打包工具环境下引入 `vue-echarts`
- [ ] Using the global variable by including `<script>` tags / 通过 `<script>` 标签引入全局变量

### The version of Vue-ECharts you are using / Vue-ECharts 的版本

    echarts: 5.1.2
    vue: 3.0.5
    vue-echarts: 6.0.0-rc.6

## Reproduction link / 复现链接

https://codesandbox.io/s/cocky-shadow-co9xc?file=/src/App.vue

- This example shows that the _getOption()_ function returns _undefined_ when the _autoresize_ attribute is present.
- Remove the _autoresize_ attribute and _getOption()_ returns the live options object as expected.

## Comment

By the way, I just want to take this opportunity to thank the maintainers and the community for all you're hard work. You folks are awesome!

**Comment by Justineo** [comment]
If `autoresize` is used, the ECharts instance is actually rendered in the `nextTick` for some reason.

https://github.com/ecomfe/vue-echarts/blob/bb9540bf4a224a0343bcc5de0cdb4903933963b9/src/ECharts.ts#L156-L165

And the `getOption` returns merged `option` only after ECharts renders so it will return `undefined` in your case. You can now get the live options object after the `nextTick` for now.

**Comment by nick-true-dev** [comment]
Ok thanks Justineo!
