### ISSUE TITLE
Q: 请问下怎么查看某个版本的源代码？

### ISSUE THREAD

**Issue by donglixiaoche** [ecomfe/vue-echarts#569]
项目中使用到了 `vue-echarts` `4.1.0` 版本, 想看下对应版本的代码, 但是没有找到对应的 tag, 请问下怎么看对应版本的代码呢？

**Comment by Justineo** [comment]
https://github.com/ecomfe/vue-echarts/tree/5.x

5.x 只发了一个小的修改，就被 6.x 取代了，你可以参考 5.x 的代码。
