### ISSUE TITLE
按需引入label配置的时候没找到对应模块

### ISSUE THREAD

**Issue by Shadows-kk** [ecomfe/vue-echarts#570]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

import {
    UniversalTransition,
    LabelLayout
} from './export/features';
将echarts改成vue-charts后，按需引入labellayout。这一步操作在文件里面报错，找不到对应的模块，是没导出这个模块吧

**Comment by Justineo** [comment]
请选择正确的 issue 表单进行填写，否则将直接关闭。谢谢。
