### ISSUE TITLE
使用Vue-cli4.5.0创建的项目npm run serve报错

### ISSUE THREAD

**Issue by dwlinn** [ecomfe/vue-echarts#571]
### 

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
vue-app@0.1.0 E:\code\vue-app
├─┬ @vue/cli-plugin-babel@4.5.13
│ └─┬ @vue/babel-preset-app@4.5.13
│   └── vue@3.1.3 deduped
├─┬ @vue/compiler-sfc@3.1.3
│ └── vue@3.1.3 deduped
├── echarts@5.1.2
├─┬ vue-echarts@6.0.0-rc.6
│ ├── echarts@5.1.2 deduped
│ ├─┬ vue-demi@0.9.1
│ │ └── vue@3.1.3 deduped
│ └── vue@3.1.3 deduped
└── vue@3.1.3
```

### 问题详情

![image](https://user-images.githubusercontent.com/46804832/124253926-1a9dfb00-db5b-11eb-8666-8362426f4c9e.png)

### 问题复现

1、使用vue-cli@4.5.0的版本创建默认的vue3项目模板 2、npm i echarts vue-echarts -S 3、npm run serve  即可复现

**Comment by Justineo** [comment]
看样子是你本地的 Vue 源码本身报的错，你可以试试移除 vue-echarts 是否能正常工作。

**Comment by dwlinn** [comment]
> 看样子是你本地的 Vue 源码本身报的错，你可以试试移除 vue-echarts 是否能正常工作。

是的... 移除后还是会报错。奇怪，昨天启动还是好的

**Comment by dwlinn** [comment]
https://github.com/vuejs/vue-cli/issues/6562 找到了，应该是vue的问题

**Comment by Justineo** [comment]
好的，这个 issue 我关闭了。
