### ISSUE TITLE
how to use  chart.on('click', 'series.line', function () {...});  

### ISSUE THREAD

**Issue by jhonnyalphas** [ecomfe/vue-echarts#572]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

how to use chart.on('click', 'series.line', function () {...});
 or equivalent

**Comment by Justineo** [comment]
```html
<v-chart @click="handleClick" .../>
```

```
handleClick (e) {
  if (e.componentType === 'series' && e.seriesType === 'line') {
    // ...
  }
}
```

**Comment by Moh-Snoussi** [comment]
I confirm that the click event is not firing with  vue: 3.2.* and  vue-echarts: 6.2.3

**Comment by Justineo** [comment]
@Moh-Snoussi Please file a bug report with proper reproduction. Thanks!
