### ISSUE TITLE
"createElement() has been called outside of render function"  when used inside wrapper

### ISSUE THREAD

**Issue by jclaessens97** [ecomfe/vue-echarts#573]
### 

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
vue-start-template-web@0.1.0 /Users/jclaessens/dev/projects/xxx/npmpackages/vue-start-template-web
├─┬ bm-echarts@0.0.1 extraneous -> /Users/jclaessens/dev/projects/xxx/npmpackages/bm-echarts
│ ├─┬ @vue/composition-api@1.0.3 extraneous
│ │ └── vue@2.6.14 extraneous
│ ├── echarts@5.1.2 extraneous
│ └─┬ vue-echarts@6.0.0-rc.6 extraneous
│   ├── echarts@5.1.2 deduped
│   ├─┬ vue-demi@0.9.1 extraneous
│   │ └── vue@2.6.14 deduped
│   └── vue@2.6.14 deduped
├─┬ bm-web-core@2.4.0
│ └── vue@2.6.14 deduped
└── vue@2.6.14
```

### Details

Our company wraps all external libraries to provide an internal stable & reusable api. Vue-Echarts is working when I use it directly, but as soon as I add a wrapper around it, it throws the following:

`[Vue warn]: createElement() has been called outside of render function.`.

Our web template doesn't use `@vue/composition-api`, so I suspect it has something to do with that, but I don't have any experience with the composition api yet. We do want to use the latest e-charts lib so we would like to use the latest vue-echarts library as well.

### Reproduction (didn't know how to replicate this in a CodeSandbox)

1. Take the SFC example for Vue2, put it in `echarts.vue` file.
2. Create a seperate npm module with following dependencies:
```
"@vue/composition-api": "^1.0.3",
"echarts": "^5.1.2",
"vue-echarts": "^6.0.0-rc.6"
```
3. export that component in an `index.js` file with `export { default } from './echarts';`
4. use `npm link` to use it in a vue2 project
5. use that component
6. See console error on page load

### Reproduction

/

**Comment by Justineo** [comment]
Please do provide a valid reproduction.

**Comment by jclaessens97** [comment]
@Justineo here you go: https://github.com/jclaessens97/vue-echarts-wrapper-repro

**Comment by jclaessens97** [comment]
@Justineo any idea that comes up? I tried to do some investigating myself and I'm wondering if it has something to do with `vue-demi`? 🤔

**Comment by Justineo** [comment]
You don't have `vue` in your dependencies in the `wrapper` package so `vue-demi` will assume you are using Vue 3 by default. You can try running `npx vue-demi switch 2` in the `wrapper` directory and see if this resolves your problem.

**Comment by jclaessens97** [comment]
Hi @Justineo ,

I ran `npx vue-demi-switch 2` inside the wrapper, but it doesn't seem to be changing anything.

```
vue-echarts-wrapper-repro/wrapper on  main is 📦 v1.0.0 via  v14.16.1
❯ npx vue-demi-switch 2
[vue-demi] Switched for Vue 2 (entry: "vue")
```

**Comment by Justineo** [comment]
I tried your repro again and got the same result.

After running the steps you provided I got this:

![image](https://user-images.githubusercontent.com/1726061/128288899-7e3649fa-d80e-42e3-866d-670b3fed4772.png)

And then I ran `npx vue-demi-switch 2` in the `wrapper` directory and everything works as expected.

![image](https://user-images.githubusercontent.com/1726061/128289014-b27fa062-d8bc-4c8b-bbf3-8ed038955ee9.png)

**Comment by jclaessens97** [comment]
Okay, so on `node v14.16.1 & npm 7.11.0`  I couldn't get it working, then I downgraded to `node v12.22.2 & npm 6.14.13` then it worked like you described 🤔 

What are your versions if I may ask?

**Comment by Justineo** [comment]
I'm on Node v14 and npm 6.

**Comment by jclaessens97** [comment]
Thanks @Justineo . 

I can now confirm after some additional testing, that the problem is `npm 6`. Probably an issue with `vue-demi` and not with this library, but using node lts with npm 6, works for me 👍🏻

**Comment by mxh861001** [comment]
The same error occurs in nuxt.js

**Comment by Justineo** [comment]
> The same error occurs in nuxt.js

Try this:

Install `@nuxtjs/composition-api` and add `'@nuxtjs/composition-api/module'` to the `buildModules` array in `nuxt.config.js`.

**Comment by shiyuanzheng** [comment]
遇到了同样问题，npx vue-demi-switch 2后依旧报‘[Vue warn]: `createElement()` has been called outside of render function.’

"vue-echarts": "^6.0.0",
"echarts": "^5.2.1",
"vue": "2.6.12",
"@vue/composition-api": "^1.2.4",
npm:  6.14.10
node: v14.15.4

**Comment by morinooji** [comment]
I'm using nuxt, and I've spent a lot of time on this issue.
And, I solved it by adding the settings below.

- add below to nuxt.config.js

  alias: {
    vue: 'vue/dist/vue.runtime.esm.js'
  },

I hope it helps someone.
