### ISSUE TITLE
radar雷达图显示不出来

### ISSUE THREAD

**Issue by zhou-tao** [ecomfe/vue-echarts#574]
### 

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
5.0.0-beta.0
```

### 问题详情

radar雷达图显示不出来

### 问题复现

radar雷达图显示不出来

**Comment by Justineo** [comment]
请按 issue 模板填写，否则将直接关闭。谢谢。
