### ISSUE TITLE
怎么获取echarts本身的实例  我要调用里面的方法

### ISSUE THREAD

**Issue by bill-mark** [ecomfe/vue-echarts#575]
### 

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
XXX
```

### 问题详情

XXX

### 问题复现

XXX

**Comment by Justineo** [comment]
请阅读 README。
