### ISSUE TITLE
Can not upgrade project to Vue 3.2.1 

### ISSUE THREAD

**Issue by ntgraph** [ecomfe/vue-echarts#576]
### 

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
├─┬ @vue/cli-plugin-babel@4.5.13
│ └─┬ @vue/babel-preset-app@4.5.13
│   └── vue@3.1.1 deduped
├─┬ @vue/compiler-sfc@3.1.1
│ └── vue@3.1.1 deduped
├── echarts@5.1.2
├─┬ element-plus@1.0.2-beta.48
│ └── vue@3.1.1 deduped
├─┬ vue-axios@3.2.4
│ └── vue@3.1.1 deduped
├─┬ vue-draggable-next@2.0.1
│ └── vue@3.1.1 deduped
├─┬ vue-echarts@6.0.0-rc.6
│ ├── echarts@5.1.2 deduped
│ ├─┬ vue-demi@0.9.1
│ │ └── vue@3.1.1 deduped
│ └── vue@3.1.1 deduped
├─┬ vue-i18n@9.1.6
│ └── vue@3.1.1 deduped
├─┬ vue-router@4.0.9
│ └── vue@3.1.1 deduped
├── vue@3.1.1
└─┬ vuex@4.0.2
  └── vue@3.1.1 deduped
```

### Details

I have a projet running all versions described about. Everything runs ok.
If I want to upgrade Vue to a newer version, I run npm update.
It seems a package @vue\composition-api block the update.  
Can you assist

### Reproduction

https://codesandbox.io/s/charming-night-2y6m6?file=/package.json

**Comment by techouse** [comment]
Same here.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! vue-echarts@"^6.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @vue/composition-api@1.1.1
npm ERR! node_modules/@vue/composition-api
npm ERR!   peerOptional @vue/composition-api@"^1.0.5" from vue-echarts@6.0.0
npm ERR!   node_modules/vue-echarts
npm ERR!     vue-echarts@"^6.0.0" from the root project
```

**Comment by Justineo** [comment]
Can you privide the complete log output for the error?

**Comment by Justineo** [comment]
Does the issue still exist?

**Comment by Zefau** [comment]
Error still exists for me. I forked this repo and removed line https://github.com/ecomfe/vue-echarts/blob/main/package.json#L60. This removes the peer dependency "@vue/composition-api", which is not required for Vue 3.

**Comment by Justineo** [comment]
It is marked as an optional peer deps, are you still using `npm@6` which may not recognize the [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#peerdependenciesmeta) field?

**Comment by Zefau** [comment]
No I'm on latest npm. Works with yarn though.

**Comment by techouse** [comment]
Yea, still causing issues with npm 8.3.1

**Comment by djtuBIG-MaliceX** [comment]
Any update on this issue? Nuxt 3 is currently on RC and will be cementing the need for working Vue3 support.

**Comment by Justineo** [comment]
I still cannot reproduce this with npm@8:

```sh
➜  ve-test ls
index.html   package.json
➜  ve-test npm ls
ve-test@1.0.0 /Users/justineo/dev/ve-test
└── (empty)

➜  ve-test npm -v
8.7.0
➜  ve-test npm i -D vue echarts vue-echarts

added 27 packages, and audited 28 packages in 5s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  ve-test npm ls
ve-test@1.0.0 /Users/justineo/dev/ve-test
├── echarts@5.3.2
├── vue-echarts@6.0.2
└── vue@3.2.33

➜  ve-test
```

**Comment by brunoalod** [comment]
This is still an ongoing problem

**Comment by Justineo** [comment]
Is this still a problem? Can you provide a repo that can reproduce this issue?

**Comment by notesjor** [comment]
npm install echarts - works fine
if I try to install vue-echarts
npm install vue-echarts
I get this error-stack:

CONSOLE

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: vue@3.2.47
npm ERR! node_modules/vue
npm ERR!   peer vue@"^3.2.47" from @nuxt/vite-builder@3.2.0
npm ERR!   node_modules/@nuxt/vite-builder
npm ERR!     @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0
npm ERR!     node_modules/nuxt
npm ERR!       dev nuxt@"^3.1.2" from the root project
npm ERR!   peer vue@">=2.7 || >=3" from @unhead/vue@1.0.21
npm ERR!   node_modules/@unhead/vue
npm ERR!     @unhead/vue@"^1.0.21" from @vueuse/head@1.0.25
npm ERR!     node_modules/@vueuse/head
npm ERR!       @vueuse/head@"^1.0.25" from nuxt@3.2.0
npm ERR!       node_modules/nuxt
npm ERR!         dev nuxt@"^3.1.2" from the root project
npm ERR!   8 more (@vitejs/plugin-vue, @vitejs/plugin-vue-jsx, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! vue-echarts@"*" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.0.5" from vue-echarts@6.5.4
npm ERR!     node_modules/vue-echarts
npm ERR!       vue-echarts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

LOG-FILE:

# npm resolution error report

While resolving: undefined@undefined
Found: vue@3.2.47
node_modules/vue
  peer vue@"^3.2.47" from @nuxt/vite-builder@3.2.0
  node_modules/@nuxt/vite-builder
    @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0
    node_modules/nuxt
      dev nuxt@"^3.1.2" from the root project
  peer vue@">=2.7 || >=3" from @unhead/vue@1.0.21
  node_modules/@unhead/vue
    @unhead/vue@"^1.0.21" from @vueuse/head@1.0.25
    node_modules/@vueuse/head
      @vueuse/head@"^1.0.25" from nuxt@3.2.0
      node_modules/nuxt
        dev nuxt@"^3.1.2" from the root project
  peer vue@"^3.2.25" from @vitejs/plugin-vue@4.0.0
  node_modules/@vitejs/plugin-vue
    @vitejs/plugin-vue@"^4.0.0" from @nuxt/vite-builder@3.2.0
    node_modules/@nuxt/vite-builder
      @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0
      node_modules/nuxt
        dev nuxt@"^3.1.2" from the root project
  peer vue@"^3.0.0" from @vitejs/plugin-vue-jsx@3.0.0
  node_modules/@vitejs/plugin-vue-jsx
    @vitejs/plugin-vue-jsx@"^3.0.0" from @nuxt/vite-builder@3.2.0
    node_modules/@nuxt/vite-builder
      @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0
      node_modules/nuxt
        dev nuxt@"^3.1.2" from the root project
  peer vue@"3.2.47" from @vue/server-renderer@3.2.47
  node_modules/@vue/server-renderer
    @vue/server-renderer@"3.2.47" from vue@3.2.47
  peer vue@"^3.0.0" from @vuetify/loader-shared@1.7.1
  node_modules/@vuetify/loader-shared
    @vuetify/loader-shared@"^1.7.1" from vite-plugin-vuetify@1.0.2
    node_modules/vite-plugin-vuetify
      peerOptional vite-plugin-vuetify@"^1.0.0-alpha.12" from vuetify@3.1.4
      node_modules/vuetify
        peer vuetify@"^3.0.0-beta.4" from @vuetify/loader-shared@1.7.1
        peer vuetify@"^3.0.0-beta.4" from vite-plugin-vuetify@1.0.2
        dev vuetify@"^3.1.4" from the root project
      dev vite-plugin-vuetify@"^1.0.2" from the root project
  peer vue@">=2.7 || >=3" from @vueuse/head@1.0.25
  node_modules/@vueuse/head
    @vueuse/head@"^1.0.25" from nuxt@3.2.0
    node_modules/nuxt
      dev nuxt@"^3.1.2" from the root project
  vue@"^3.2.47" from nuxt@3.2.0
  node_modules/nuxt
    dev nuxt@"^3.1.2" from the root project
  peer vue@"^3.2.0" from vue-router@4.1.6
  node_modules/vue-router
    vue-router@"^4.1.6" from nuxt@3.2.0
    node_modules/nuxt
      dev nuxt@"^3.1.2" from the root project
  peer vue@"^3.2.0" from vuetify@3.1.4
  node_modules/vuetify
    peer vuetify@"^3.0.0-beta.4" from @vuetify/loader-shared@1.7.1
    peer vuetify@"^3.0.0-beta.4" from vite-plugin-vuetify@1.0.2
    dev vuetify@"^3.1.4" from the root project

Could not resolve dependency:
vue-echarts@"*" from the root project

Conflicting peer dependency: vue@2.6.14
node_modules/vue
  peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
  node_modules/@vue/composition-api
    peerOptional @vue/composition-api@"^1.0.5" from vue-echarts@6.5.4
    node_modules/vue-echarts
      vue-echarts@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

This ist a minimal project solution.
Techstack: Nuxt3 + Vuetify3

[Nuxt3Base.zip](https://github.com/ecomfe/vue-echarts/files/10706537/Nuxt3Base.zip)

**Comment by muffinhydra** [comment]
I had the same problem. Updating from npm 7.24.2 to npm 9.5.1 solved this issue for me. My stack is also Nuxt3 and Vuetify3.

**Comment by luisaugs** [comment]
> npm install echarts - works fine if I try to install vue-echarts npm install vue-echarts I get this error-stack:
> 
> CONSOLE
> 
> npm ERR! code ERESOLVE npm ERR! ERESOLVE could not resolve npm ERR! npm ERR! While resolving: undefined@undefined npm ERR! Found: vue@3.2.47 npm ERR! node_modules/vue npm ERR! peer vue@"^3.2.47" from @nuxt/vite-builder@3.2.0 npm ERR! node_modules/@nuxt/vite-builder npm ERR! @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0 npm ERR! node_modules/nuxt npm ERR! dev nuxt@"^3.1.2" from the root project npm ERR! peer vue@">=2.7 || >=3" from @unhead/vue@1.0.21 npm ERR! node_modules/@unhead/vue npm ERR! @unhead/vue@"^1.0.21" from @vueuse/head@1.0.25 npm ERR! node_modules/@vueuse/head npm ERR! @vueuse/head@"^1.0.25" from nuxt@3.2.0 npm ERR! node_modules/nuxt npm ERR! dev nuxt@"^3.1.2" from the root project npm ERR! 8 more (@vitejs/plugin-vue, @vitejs/plugin-vue-jsx, ...) npm ERR! npm ERR! Could not resolve dependency: npm ERR! vue-echarts@"_" from the root project npm ERR! npm ERR! Conflicting peer dependency: vue@2.6.14 npm ERR! node_modules/vue npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1 npm ERR! node_modules/@vue/composition-api npm ERR! peerOptional @vue/composition-api@"^1.0.5" from vue-echarts@6.5.4 npm ERR! node_modules/vue-echarts npm ERR! vue-echarts@"_" from the root project npm ERR! npm ERR! Fix the upstream dependency conflict, or retry npm ERR! this command with --force or --legacy-peer-deps npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> 
> LOG-FILE:
> 
> # npm resolution error report
> While resolving: undefined@undefined Found: vue@3.2.47 node_modules/vue peer vue@"^3.2.47" from @nuxt/vite-builder@3.2.0 node_modules/@nuxt/vite-builder @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0 node_modules/nuxt dev nuxt@"^3.1.2" from the root project peer vue@">=2.7 || >=3" from @unhead/vue@1.0.21 node_modules/@unhead/vue @unhead/vue@"^1.0.21" from @vueuse/head@1.0.25 node_modules/@vueuse/head @vueuse/head@"^1.0.25" from nuxt@3.2.0 node_modules/nuxt dev nuxt@"^3.1.2" from the root project peer vue@"^3.2.25" from @vitejs/plugin-vue@4.0.0 node_modules/@vitejs/plugin-vue @vitejs/plugin-vue@"^4.0.0" from @nuxt/vite-builder@3.2.0 node_modules/@nuxt/vite-builder @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0 node_modules/nuxt dev nuxt@"^3.1.2" from the root project peer vue@"^3.0.0" from @vitejs/plugin-vue-jsx@3.0.0 node_modules/@vitejs/plugin-vue-jsx @vitejs/plugin-vue-jsx@"^3.0.0" from @nuxt/vite-builder@3.2.0 node_modules/@nuxt/vite-builder @nuxt/vite-builder@"3.2.0" from nuxt@3.2.0 node_modules/nuxt dev nuxt@"^3.1.2" from the root project peer vue@"3.2.47" from @vue/server-renderer@3.2.47 node_modules/@vue/server-renderer @vue/server-renderer@"3.2.47" from vue@3.2.47 peer vue@"^3.0.0" from @vuetify/loader-shared@1.7.1 node_modules/@vuetify/loader-shared @vuetify/loader-shared@"^1.7.1" from vite-plugin-vuetify@1.0.2 node_modules/vite-plugin-vuetify peerOptional vite-plugin-vuetify@"^1.0.0-alpha.12" from vuetify@3.1.4 node_modules/vuetify peer vuetify@"^3.0.0-beta.4" from @vuetify/loader-shared@1.7.1 peer vuetify@"^3.0.0-beta.4" from vite-plugin-vuetify@1.0.2 dev vuetify@"^3.1.4" from the root project dev vite-plugin-vuetify@"^1.0.2" from the root project peer vue@">=2.7 || >=3" from @vueuse/head@1.0.25 node_modules/@vueuse/head @vueuse/head@"^1.0.25" from nuxt@3.2.0 node_modules/nuxt dev nuxt@"^3.1.2" from the root project vue@"^3.2.47" from nuxt@3.2.0 node_modules/nuxt dev nuxt@"^3.1.2" from the root project peer vue@"^3.2.0" from vue-router@4.1.6 node_modules/vue-router vue-router@"^4.1.6" from nuxt@3.2.0 node_modules/nuxt dev nuxt@"^3.1.2" from the root project peer vue@"^3.2.0" from vuetify@3.1.4 node_modules/vuetify peer vuetify@"^3.0.0-beta.4" from @vuetify/loader-shared@1.7.1 peer vuetify@"^3.0.0-beta.4" from vite-plugin-vuetify@1.0.2 dev vuetify@"^3.1.4" from the root project
> 
> Could not resolve dependency: vue-echarts@"*" from the root project
> 
> Conflicting peer dependency: vue@2.6.14 node_modules/vue peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1 node_modules/@vue/composition-api peerOptional @vue/composition-api@"^1.0.5" from vue-echarts@6.5.4 node_modules/vue-echarts vue-echarts@"*" from the root project
> 
> Fix the upstream dependency conflict, or retry this command with --force or --legacy-peer-deps to accept an incorrect (and potentially broken) dependency resolution.
> 
> This ist a minimal project solution. Techstack: Nuxt3 + Vuetify3
> 
> [Nuxt3Base.zip](https://github.com/ecomfe/vue-echarts/files/10706537/Nuxt3Base.zip)




**Same issue. echarts install fine, but vue-echarts throw this error**

node v: 16.5.0
npm v: 8.9.0
vue v: 3.2.25

**Comment by jinyukk** [comment]
node v.

**Comment by jinyukk** [comment]
Environment:

**Comment by jinyukk** [comment]
When I add vue-echarts to my Nuxt3 project by `npm install vue-echarts`, it failed and had same problem.
And then I use `pnpm install vue-echarts`, it succeeded.

I hope this helpes.

My Environment:
node version: 18.15.0
npm version: 9.6.3
Nuxt version: 3.5.2

**Comment by Justineo** [comment]
The npm resolution error shows that the conflict is from `@vue/compisiton-api` marking `vue@">= 2.5 < 2.7"` as its peer dep. But in fact `@vue/composition-api` itself is marked as an optional peer dep of `vue-echarts` and not used by Vue 3 projects:

https://github.com/ecomfe/vue-echarts/blob/53ebc2941ea39cddd4181efc30331ad06ed315e7/package.json#L76-L80

...but npm doesn't seem to respect this. As `vue-echarts` supports both Vue 2 and Vue 3 so that `@vue/composition-api` cannot be completely removed from peer deps.

Does it work with npm if we enable the `--legacy-peer-deps` flag (as the error log suggests)?

**Comment by jpengelbrecht** [comment]
would be nice if this was fixed.

**Comment by Justineo** [comment]
> Does it work with npm if we enable the `--legacy-peer-deps` flag (as the error log suggests)?

**Comment by rafalh** [comment]
I have the same problem with npm 10.2.3. Adding `--legacy-peer-deps` resolves the problem but I would prefer if it was fixed upstream...
Maybe having a separate version for Vue 2 would be a solution?

**Comment by Justineo** [comment]
> I have the same problem with npm 10.2.3.

I still cannot reproduce with npm 10.2.3. Can you elaborate on how to reproduce this error in a fresh project?

**Comment by rafalh** [comment]
> Can you elaborate on how to reproduce this error in a fresh project?

Not really which surprises me. I get this error in existing project. I stripped down package.json as much as I could and you can find the result here: [reproduction.zip](https://github.com/ecomfe/vue-echarts/files/13822127/reproduction.zip)
Running `npm install vue-echarts` triggers the error.
But if I remove lock file and node_module, optionally change the version specifier for vue to `3.3.10` (so it is the same as in the removed lock file) and then install from scratch the error does not happen.
If I just change `"vue": "^3.3.10"` to `"vue": "3.3.10"` without removing anything the error also does not trigger.
I feel my knowledge of npm and peer dependencies is too low to debug it further. Maybe it's not a bug of vue-echarts but a bug of npm?

**Comment by bahmanian** [comment]
I gave this error during installation using command "npm i echarts vue-echarts":
While resolving: undefined@undefined
Found: vue@3.4.27
node_modules/vue
  dev vue@"^3.4.7" from the root project

Could not resolve dependency:
peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.2
node_modules/@vue/composition-api
  @vue/composition-api@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
