### ISSUE TITLE
本地构建（执行npm run build）报错： Error: Package subpath './lib/index.iife.js' is not defined by "exports"

### ISSUE THREAD

**Issue by zhounewz** [ecomfe/vue-echarts#577]
### 

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
mtv-charts-vue@1.0.0 /Users/zhouxinzhe/git/mtc-vue-visual/packages/mtv-charts-vue
├── echarts@5.1.2 
└── UNMET PEER DEPENDENCY vue@3.1.1 

npm ERR! peer dep missing: vue@>= 2.5 < 3, required by @vue/composition-api@1.0.5
```

### 问题详情

本地构建（执行npm run build）报错： Error: Package subpath './lib/index.iife.js' is not defined by "exports"

### 问题复现

https://github.com/ecomfe/vue-echarts

**Comment by Justineo** [comment]
请提供一个有效的最小复现环境，谢谢。
