### ISSUE TITLE
cli3， lib 打包，调用报错

### ISSUE THREAD

**Issue by igfz** [ecomfe/vue-echarts#578]
### 

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
├── echarts@5.1.2 
├── vue@2.6.12 
└── vue-echarts@6.0.0
```

### 问题详情

cli3  打 lib 包，导出组件。

引用 该组件 报错
biz.common.js?75c0:35403 Uncaught TypeError: external_commonjs_vue_commonjs2_vue_root_Vue_.use is not a function
    at lib_install (biz.common.js?75c0:35403)

报错位置：
function lib_install(_vue) {
  _vue = _vue || external_commonjs_vue_commonjs2_vue_root_Vue_
  if (_vue && !_vue['__composition_api_installed__'])
    external_commonjs_vue_commonjs2_vue_root_Vue_.use(vue_composition_api_esm)
}

应该 是  不知道如何解决，望帮助

### 问题复现

http://localhost:8080/?id=52

**Comment by Justineo** [comment]
你好，最小化的复现是必须的，否则我们无法提供帮助，谢谢。
