### ISSUE TITLE
echarts.graphic.clipRectByRect未定义

### ISSUE THREAD

**Issue by cinos1** [ecomfe/vue-echarts#579]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

在使用自定义图形时，引入了
import echarts from 'echarts/lib/echarts'
自定义绘制矩形时
var rectShape = echarts.graphic.clipRectByRect({})
报错:
TypeError: Cannot read property 'clipRectByRect' of undefined

**Comment by Justineo** [comment]
1. 这不是 feature request；
2. 你上面的例子和 Vue-ECharts 毫无关系，你勾选确认的内容真的有读过吗？
