### ISSUE TITLE
点击还原后图表丢失

### ISSUE THREAD

**Issue by ZhouShuren1881** [ecomfe/vue-echarts#580]
### 

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
vtest@0.1.0 D:\Programming\vtest    
+-- echarts@5.1.2 
+-- UNMET PEER DEPENDENCY vue@3.2.4 
`-- vue-echarts@6.0.0
```

### 问题详情

点击项目右上角的“还原”按钮，原本渲染的图像丢失，只剩一片空白

### 问题复现

https://codesandbox.io/s/brave-darwin-g0i92

**Comment by Justineo** [comment]
请升级到 `vue-echarts@6.0.2` 测试一下是否依然有这个问题。
