### ISSUE TITLE
Is it possible to integrate 3rd party transform methods in vue-echarts?

### ISSUE THREAD

**Issue by DanielBogenrieder** [ecomfe/vue-echarts#581]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

Hey,

In ECharts I can integrate 3rd party transformations like this one here: https://github.com/100pah/echarts-simple-transform
This would be very useful for vue-echarts as well. I am wondering if this is already possible and I am missing something, or if this is missing functionality. I only found one StackOverflow post with no answer: https://stackoverflow.com/questions/67274213/vue-echarts-how-to-use-transform-ecsimpletransformaggregate

Greetings and thanks a lot for the great work,
Daniel

**Comment by Justineo** [comment]
Yes. ECharts extensions should work with Vue ECharts (as long as their `echarts` dependencies resolve to the same package).
