### ISSUE TITLE
K线图是否可以支持方向键

### ISSUE THREAD

**Issue by mymmsc** [ecomfe/vue-echarts#582]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

左移:：左键
右移：右键
向上：放大
向下：缩小

**Comment by Justineo** [comment]
这方面功能请提交到 ECharts 项目本身，这里不会进行支持，谢谢。
