### ISSUE TITLE
是否支持dataset管理数据

### ISSUE THREAD

**Issue by xiaoyuliushuihualala** [ecomfe/vue-echarts#584]
### 

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
"vue-echarts": "^6.0.0-rc.5",
```

### 问题详情

使用dataset管理数据时，图形无法绘制出来

### 问题复现

https://codesandbox.io/s/serene-austin-qbot6?file=/src/App.vue

**Comment by Justineo** [comment]
Duplicate of #555
