### ISSUE TITLE
总是在编译的时候npm install --save vue-echarts 但是我已经安装了vu-echarts

### ISSUE THREAD

**Issue by daniel-lij** [ecomfe/vue-echarts#589]
### 

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
"echarts": "^5.2.1",
"vue-echarts": "^6.0.0",
```

### Details

我没有在index.js挂载vue-echarts,每次都是到相应的页面import
`import YChart from 'vue-echarts'
import theme from './theme.json'
import EchartDeploy from '@utils/echarts/echart-deploy'
YChart.registerTheme('walden', theme)`
但是在编译的时候总是报错
To install it, you can run: npm install --save vue-echarts

### Reproduction

没有

**Comment by hlfine** [comment]
同样的问题， 我删除了node_modules, 然后重新下载，然后解决了这个问题。

**Comment by Justineo** [comment]
请提供一个复现环境，可以是一个 repo，如果没有复现我们很难提供帮助。

**Comment by Justineo** [comment]
Closing as no runnable reproduction is provided.
