### ISSUE TITLE
升级 vue-demi 到 0.12.x

### ISSUE THREAD

**Issue by anchel** [ecomfe/vue-echarts#591]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

vue-demi 的下面这个issue会引起项目报错，vue-demi已经在0.12.x的版本中修复了，需要vue-echarts升级对它的依赖到0.12.x
https://github.com/vueuse/vue-demi/issues/106

**Comment by Justineo** [comment]
Updated in v6.0.1.
