### ISSUE TITLE
Detail Nuxt 3 Usage in Docs

### ISSUE THREAD

**Issue by Destaq** [ecomfe/vue-echarts#593]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

There is already an example of using Vue-ECharts with the Nuxt Composition API, but [Nuxt v3](https://v3.nuxtjs.org/) that fully supports Vue 3 has already been released.

As such, it would be great to have the docs describe how to use Vue-ECharts with Nuxt 3. I've tried personally to no avail due to unfamiliarity with this component.

**Comment by Destaq** [comment]
Stack Trace:
```
(node:93331) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/---/Desktop/vue-echarts-nuxt3/node_modules/echarts/lib/core/echarts.js:26
import { __extends } from "tslib";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1026:15)
    at Module._compile (node:internal/modules/cjs/loader:1061:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
```

Minimum repro: [here](https://github.com/Destaq/vue-echarts-nuxt3)

**Comment by Destaq** [comment]
A way to integrate the two is described [here](https://github.com/nuxt/framework/discussions/2474#discussioncomment-1850092).

**Comment by numberslk** [comment]
@Destaq The link you provided is broken, I am trying to integrate with nuxt 3, haven't found any useful documentation. if you could provide one it could be very useful.

**Comment by Destaq** [comment]
> @Destaq The link you provided is broken, I am trying to integrate with nuxt 3, haven't found any useful documentation. if you could provide one it could be very useful. 

@numberslk I'm afraid I can't help you -- the repository discussion was deleted by someone other than me, and since it's been about a year, I don't remember how I accomplished the integration.

**Comment by gpueyo** [comment]
I was facing the same problem and these examples help me a lot:
- [Vue-ECharts + Vue 3](https://stackblitz.com/edit/vue-echarts-vue-3?file=vite.config.js,src%2FApp.vue%3AL27)
- [Destaq - Vue Echarts Nuxt3](https://stackblitz.com/edit/github-unqktr?file=app.vue%3AL10)

**Comment by peterroe** [comment]
I meet the same problem. @gpueyo. The problem still occurs after manually refreshing the page 😥

**Comment by savokiss** [comment]
> I meet the same problem. @gpueyo. The problem still occurs after manually refreshing the page 😥

@peterroe 

I am encoutering the same issue when using Nuxt@3.6.2 after build.

After reviewing it, I found that the [Destaq Demo](https://stackblitz.com/edit/github-unqktr?file=app.vue%3AL10) was different with my local project. Mainly because the `.npmrc` file created by Nuxt CLI.
```text
shamefully-hoist=true
strict-peer-dependencies=false
```

### Solution:
Add `/resize-detector/` to your `nuxt.config.ts` file!

Your config will have this snippet:
```ts
  build: {
    transpile: [/echarts/, /resize-detector/],
  },
```

Hope this can help you~

**Comment by BenJackGill** [comment]
I think the docs still need to be updated for Nuxt 3.

I was unaware we needed this in `nuxt.config.ts`:

```
  build: {
    transpile: ["echarts"],
  },
```

**Comment by kingyue737** [comment]
I write a Nuxt ECharts module which does not need to transpile any dependencies. Very welcome to take a try.

https://github.com/kingyue737/nuxt-echarts
