### ISSUE TITLE
update should always have notMerge: true?

### ISSUE THREAD

**Issue by ilylx** [ecomfe/vue-echarts#596]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

commit/7aa9edca96108a75056b7932ec3b7670416b76b4

比如我放大了图表，然后增加了新的坐标点数据，
如果notMerge=false，图表的缩放会保持，只会增加新的坐标点。
如果notMerge=true，图表的缩放会还原，这样就没法在缩放的状态下看到数据的动态变化了。

**Comment by ilylx** [comment]
@Justineo

**Comment by Justineo** [comment]
从数据本身的机制来说，只有 `notMerge: true` 才是正确的，因为从 Vue 组件的视角来看，每次 `option` prop 更新都应该是全量的。不过如果对于 ECharts 来说这样引起很多非预期的问题的话可能只能 revert 回去了。

/cc @pissang 关于这个问题有没有什么好的办法？

**Comment by ilylx** [comment]
true或者false，echarts的行为表现不同，所以就给用户个选择的机会吧

**Comment by Justineo** [comment]
回退到了 5.x 的行为。当 `option` 引用发生变化时，将设置 `notMerge: true`，否则则不添加，同时可以通过 `update-options` prop 来显式覆盖。
