### ISSUE TITLE
qiankun子应用采用CDN方式接入vue-echarts，无法加载

### ISSUE THREAD

**Issue by ydobi** [ecomfe/vue-echarts#597]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

qiankun加载子应用vue-echarts脚本时，修改了window指向，导致globalThis无法获取VueDemi，请问下这种情况可以兼容一下吗？
<img width="1035" alt="WX20220121-101900@2x" src="https://user-images.githubusercontent.com/22515445/150462799-c63ed219-f388-4d7b-9838-15a66565a1a9.png">
<img width="1017" alt="WX20220121-101832@2x" src="https://user-images.githubusercontent.com/22515445/150462826-067958a4-6ab4-486d-bdbe-ca90f345e896.png">

**Comment by Justineo** [comment]
这怎么看都是 qiankun 的问题吧，不是这个项目能解决的。
