### ISSUE TITLE
how to use chart.on('click', 'series.line', function () {...}); 

### ISSUE THREAD

**Issue by xiaoyezi312** [ecomfe/vue-echarts#598]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

1、问题：无法调用echarts的@click方法
2、问题描述：
      代码：` <EChart @click="handleClick"> </EChart>`
      使用的是`vue3^3.2.4(script-setup语法糖) + typescript: "~4.1.5" + vue-echarts: "^6.0.0",`
      但是click事件触发的是元素的原生click事件，而非echarts的click事件
3、[尝试过这个方法没解决](https://github.com/ecomfe/vue-echarts/issues/572)

**Comment by Justineo** [comment]
Please provide a runnable reproduction otherwise we can't provide help. Thank you.

**Comment by shady-xia** [comment]
这个问题还没解决吗？vue3直接使用click是没效果的，使用native:click，触发的是原生click而不是echarts封装的click

**Comment by kingyue737** [comment]
@shady-xia 我这里没有发现问题 https://stackblitz.com/edit/vue-echarts-vue-3-global-8qxmessc?file=index.html

请提供一个最小复现

**Comment by shady-xia** [comment]
> [@shady-xia](https://github.com/shady-xia) 我这里没有发现问题 https://stackblitz.com/edit/vue-echarts-vue-3-global-8qxmessc?file=index.html
> 
> 请提供一个最小复现

解决了，应该是我理解有问题，折线图只有点击到点位上才会触发echarts的click
https://codesandbox.io/p/sandbox/romantic-lichterman-r5c9n4?file=%2Fsrc%2FApp.vue%3A130%2C25

**Comment by kingyue737** [comment]
@shady-xia 如果希望监听在非图形元素处的点击，可以使用zrender的事件`@zr:click="handleClick"`

**Comment by shady-xia** [comment]
> [@shady-xia](https://github.com/shady-xia) 如果希望监听在非图形元素处的点击，可以使用zrender的事件`@zr:click="handleClick"`

好的，感谢:)
