### ISSUE TITLE
setOption should not be called during

### ISSUE THREAD

**Issue by samchenws** [ecomfe/vue-echarts#600]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
6.0.2
```

### Details

单个页面多个图表，异步的数据很经常出现 setOption should not be called during。
我看了demo但是我看不出单个图表和多个图标差异在哪？

### Reproduction

无

**Comment by Justineo** [comment]
没有可复现的场景我们无法提供帮助，谢谢。
