### ISSUE TITLE
UPDATE_OPTIONS_KEY 不起作用

### ISSUE THREAD

**Issue by qzmlgfj** [ecomfe/vue-echarts#608]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
├─┬ @vue/cli-plugin-babel@4.5.15
│ └─┬ @vue/babel-preset-app@4.5.15
│   └── vue@3.2.31 deduped
├── echarts@5.3.1
├─┬ vue-echarts@6.0.2
│ ├── echarts@5.3.1 deduped
│ ├─┬ vue-demi@0.12.1
│ │ └── vue@3.2.31 deduped
│ └── vue@3.2.31 deduped
└─┬ vue@3.2.31
  └─┬ @vue/server-renderer@3.2.31
    └── vue@3.2.31 deduped
```

### 问题详情

我在仿照Echarts官网的[可缩放折线图](https://echarts.apache.org/examples/zh/editor.html?c=area-time-axis)来实现一个动态折线图时，发现数据变化时会还原缩放状态，但使用官网提供的在线环境没有这种情况。

我参照了之前一个关闭的Issue #596，将`UPDATE_OPTIONS_KEY`中的`notMerge`参数设置为`false`，但这并没有像那个Issue中所期望的那样工作。

我不知道哪里出了问题，之后我通过Vue CLI新建了一个默认Vue 3项目并重现了它。

### 问题复现

https://github.com/qzmlgfj/default-vue3

**Comment by Justineo** [comment]
我看了一下，应该是 ECharts 的一个 bug，你可以关注一下：https://github.com/apache/echarts/issues/16961
