### ISSUE TITLE
Unknown custom element: <x-vue-echarts> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by aWestbrookFan** [ecomfe/vue-echarts#609]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
+-- echarts@5.3.1
+-- vue@2.6.14
+-- vue-echarts@6.0.2
```

### 问题详情

vue2项目中引用vue-echarts 图表已经渲染出来，但是报 【vue.runtime.esm.js:619 [Vue warn]: Unknown custom element: <x-vue-echarts> - did you register the component correctly? For recursive components, make sure to provide the "name" option.】

### 问题复现

无

**Comment by Justineo** [comment]
You can suppress the warning by adding:

```js
Vue.config.ignoredElements.push('x-vue-echarts')
```

**Comment by kongchengxinde** [comment]
这个报错只能忽略吗，是否影响使用？

**Comment by Justineo** [comment]
> 这个报错只能忽略吗，是否影响使用？

你用最新的版本不会有这个提示。
