### ISSUE TITLE
Chart does not render in shadow dom

### ISSUE THREAD

**Issue by dciccale** [ecomfe/vue-echarts#613]
### Confirmation

- [x] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
vue 3.2.8
echarts 5.1.2
vue-echarts 6.0.0
```

### Details

When using vue's [defineCustomElement](https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue) the chart stops rendering.

I can't confirm this problem is reproducible with ECharts, I'm not sure how to test this without vue.

Please check the CodeSandbox link below to see what I mean, it is a copy from the CodeSandbox Vue3 demo present on this repository's README.md file, the only change is defining a custom element and using this custom element on the index.html file as shown below:

`src/main.js`

```js
// import { createApp } from 'vue'
import { defineCustomElement } from "vue";
import App from "./App.vue";

// createApp(App).mount('#app')

const app = defineCustomElement(App);
customElements.define("my-app", app);
```

`public/index.html`

```html
<!-- <div id="app"></div> -->
<my-app></my-app>
```

`src/App.vue`

```vue
<template>
  <p>this renders, chart does not</p>
  <v-chart class="chart" :option="option" />
</template>
```

### Reproduction

https://codesandbox.io/s/twilight-fire-hd4bd6?file=/src/main.js

**Comment by Justineo** [comment]
See https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue

**Comment by dciccale** [comment]
> See https://vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue

Hi @Justineo thanks for your time. I've read the page you sent me, it's the one I read to prepare the reproduction codesandbox link above.
I am unable to see what you suggest, could you help me out by being more specific?
Thanks in advance

**Comment by Justineo** [comment]
> The official SFC toolings support importing SFCs in "custom element mode" (requires @vitejs/plugin-vue@^1.4.0 or vue-loader@^16.5.0). An SFC loaded in custom element mode inlines its <style> tags as strings of CSS and exposes them under the component's styles option. This will be picked up by defineCustomElement and injected into the element's shadow root when instantiated.

Your reproduction shows that the root element's height is not correctly injected into the custom element. The chart is rendered, it's invisible because of its height is 0. Anyway, it's not a problem caused by this project.

**Comment by dciccale** [comment]
Thanks @Justineo I see what you mean, indeed, loading styles as a string inside the shadow dom is the only way to make it work, or use plain style="" to give the v-chart component some height/width.

sorry for opening a stupid issue, and thanks for building vue-echarts, i'm starring it!
