### ISSUE TITLE
Namespace "/node_modules/vue-demi/lib/index" has no exported member 'DefineComponent'

### ISSUE THREAD

**Issue by ws511341206** [ecomfe/vue-echarts#616]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
"echarts": "^5.3.2",
"vue": "^2.6.14",
"vue-echarts": "^6.0.2",
"@vue/composition-api": "^1.4.9"
```

### 问题详情

vue-echarts依赖"vue-demi": "^0.12.1"，
我项目中的是"vue-demi": "^0.12.5",
node_modules/vue-echarts/dist/index.d.ts中，找不到vue_demi.DefineComponent

### 问题复现

123

**Comment by Justineo** [comment]
你可以尝试重新安装一下 `vue-echarts`，在 `postinstall` 脚本里面有切换 TS 声明到降级版本的。

**Comment by ws511341206** [comment]
> 你可以尝试重新安装一下 `vue-echarts`，在 `postinstall` 脚本里面有切换 TS 声明到降级版本的。

感谢

**Comment by ws511341206** [comment]
> 你可以尝试重新安装一下 `vue-echarts`，在 `postinstall` 脚本里面有切换 TS 声明到降级版本的。

能具体说一下怎么操作吗，没找到在哪里

**Comment by Justineo** [comment]
`npm i vue-echarts`

**Comment by ws511341206** [comment]
大神有邮箱吗，发你给demo帮我看下

**Comment by ws511341206** [comment]
> ```shell
> npm i vue-echarts
> ```
大神有邮箱吗，发你给demo帮我看下
