### ISSUE TITLE
vue2无法使用vue-echarts6.0.2版本

### ISSUE THREAD

**Issue by ws511341206** [ecomfe/vue-echarts#617]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
"echarts": "^5.3.2",
"vue": "^2.6.14",
"vue-echarts": "^6.0.2"
```

### 问题详情

![1650289965(1)](https://user-images.githubusercontent.com/13127890/163818152-a1339211-e73c-46ec-8910-c3d69d608357.jpg)
![1650290027(1)](https://user-images.githubusercontent.com/13127890/163818279-17fba222-38fd-4e12-8aa5-adcb26b68b2e.jpg)

### 问题复现

https://gitee.com/RelaxWang/demo.git

**Comment by Justineo** [comment]
```sh
npx vue-demi-fix
```
