### ISSUE TITLE
Vue3 + VueUse Conditional Color Change

### ISSUE THREAD

**Issue by pjmanning** [ecomfe/vue-echarts#618]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

I'm trying to conditionally change colors within a Gauge chart using [VueUse's `useDark` function.](https://vueuse.org/core/usedark/#usedark).

Is there a simple way to conditionally render colors/styles in a Charts options based on something like `const isDark = useDark()`?

**Comment by Justineo** [comment]
It already works if you `provide` different theme according to the value of `isDark`.
