### ISSUE TITLE
Vue2 Typescript Support

### ISSUE THREAD

**Issue by kingyue737** [ecomfe/vue-echarts#622]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

How to use Typescript with Vue 2? In Vue 2 project, type of the VueEcharts component is any. Is it possible to obtain types of component methods?

**Comment by Justineo** [comment]
v6.0.3 is published with better TypeScript support for Vue 2. If you use Volar you should get type check in your template for props and methods. For template refs:

```vue
<script setup lang="ts">
import VChart from 'vue-echarts'
import { ref, onMounted } from '@vue/composition-api'

const chart = ref<InstanceType<typeof VChart> | null>(null);

onMounted(() => {
  if (c.value) {
    console.log(chart.value) // this should expose methods
  }
})
</script>

<template>
<v-chart ref="c" />
</template>
```
