### ISSUE TITLE
如何获取点击的节点信息？

### ISSUE THREAD

**Issue by hiddendeer** [ecomfe/vue-echarts#624]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

<v-chart @selectchanged="_click(e)" ref="refChart" :option="option" />
打印出的e是没有的，我看原生的方法都是监听on('click'),请问该组件如何获取呢。

**Comment by hiddendeer** [comment]
<v-chart @selectchanged="_click(e)" ref="refChart" :option="option" />

**Comment by hiddendeer** [comment]
<v-chart @selectchanged="_click(e)" ref="refChart" :option="option" />
打印出的e是没有的，我看原生的方法都是监听on('click'),请问该组件如何获取呢。

**Comment by Justineo** [comment]
这是你使用 `v-on` 不正确的问题。

Vue 3：https://vuejs.org/guide/essentials/event-handling.html#accessing-event-argument-in-inline-handlers

Vue 2：
https://v2.vuejs.org/v2/guide/events.html#Methods-in-Inline-Handlers
