### ISSUE TITLE
在开启 autoresize 的时候，无法安全地通过组件实例调用 convertToPixel 方法

### ISSUE THREAD

**Issue by BiosSun** [ecomfe/vue-echarts#625]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
vue: 3.2.37
echarts: 5.3.2
vue-echarts: 6.0.3
```

### 问题详情

具体效果请看「问题复现」提供的 Demo（需要从 unpkg.com 中加载所依赖很多模块，请确保可以正常访问 unpkg.com，然后多等一会）。

1. 使用 vue-echarts 组件，引用组件实例，但先不开启 autoresize：
   ```html
   <vue-echarts :option="option" ref="chartRef" />
   ```
3. watch 组件实例，将 flush 设置为 `post`，并在其中调用 `convertToPixel` 方法：
   ```javascript
   watch(chartRef, (chart) => {
       chart?.convertToPixel({ yAxisIndex: 0 }, 150)
   }, { flush: 'post' })
   ```
   此时，watch 会在组件 mounted 时触发，convertToPixel 也可以调用并返回结果；
5. 然后，开启 autoresize：
   ```html
   <vue-echarts :option="option" ref="chartRef" autoresize />
   ```
   修改后，convertToPixel 在被调用时将会抛出异常：`Cannot read properties of undefined (reading 'queryComponents')`。
  
   需要等待一次 nextTick 之后，才能正常调用：

   ```javascript
   watch(chartRef, async (chart) => {
       await nextTick()
       chart?.convertToPixel({ yAxisIndex: 0 }, 150)
   }, { flush: 'post' })
   ```

### 问题复现

[Vue SFC Playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCAqIGFzIGVjaGFydHMgZnJvbSAnZWNoYXJ0cyc7XG48L3NjcmlwdD5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG5leHRUaWNrLCB3YXRjaCB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFY2hhcnRzIGZyb20gJ3Z1ZS1lY2hhcnRzJ1xuICBcbmNvbnN0IGNoYXJ0UmVmID0gcmVmKG51bGwpXG5cbmNvbnN0IG9wdGlvbiA9IHJlZih7XG4gIHhBeGlzOiB7XG4gICAgdHlwZTogJ2NhdGVnb3J5JyxcbiAgICBkYXRhOiBbJ01vbicsICdUdWUnLCAnV2VkJywgJ1RodScsICdGcmknLCAnU2F0JywgJ1N1biddXG4gIH0sXG4gIHlBeGlzOiB7XG4gICAgdHlwZTogJ3ZhbHVlJ1xuICB9LFxuICBzZXJpZXM6IFtcbiAgICB7XG4gICAgICBkYXRhOiBbMTUwLCAyMzAsIDIyNCwgMjE4LCAxMzUsIDE0NywgMjYwXSxcbiAgICAgIHR5cGU6ICdsaW5lJ1xuICAgIH1cbiAgXVxufSlcbiAgXG5jb25zdCBtZXNzYWdlID0gcmVmKClcblxud2F0Y2goY2hhcnRSZWYsIGFzeW5jIChjaGFydCkgPT4ge1xuICBpZiAoY2hhcnQpIHtcbiAgICAvLyBOT1RFOiDnp7vpmaTor6XooYznmoTms6jph4rvvIznqIvluo/lsIbkvJrmraPluLjmiafooYxcbiAgICAvLyAgICAgICDmiJbliKDpmaTmqKHlnZfkuK3nmoQgYXV0b3Jlc2l6ZSDlsZ7mgKdcbiAgICAvLyBhd2FpdCBuZXh0VGljaygpXG4gICAgXG4gICAgdHJ5IHtcbiAgICAgIG1lc3NhZ2UudmFsdWUgPSAnY2FsbCBjaGFydC5jb252ZXJ0VG9QaXhlbCByZXN1bHQgaXMgJyArIGNoYXJ0LmNvbnZlcnRUb1BpeGVsKHsgeUF4aXNJbmRleDogMCB9LCAxNTApXG4gICAgfVxuICAgIGNhdGNoIChlcnJvcikge1xuICAgICAgbWVzc2FnZS52YWx1ZSA9ICdjYWxsIGNoYXJ0LmNvbnZlcnRUb1BpeGVsIGVycm9yIGlzICcgKyBlcnJvci5tZXNzYWdlXG4gICAgfVxuICB9XG59LCB7XG4gIGZsdXNoOiAncG9zdCcgXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8aDE+Q2hhcnQ8L2gxPlxuXHRcdDxFY2hhcnRzIGNsYXNzPVwiY2hhcnRcIiA6b3B0aW9uPVwib3B0aW9uXCIgcmVmPVwiY2hhcnRSZWZcIiBhdXRvcmVzaXplIC8+XG4gICAgPGJyIC8+XG4gICAgPHN0cm9uZz5tZXNzYWdlOjwvc3Ryb25nPiB7eyBtZXNzYWdlIH19XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuY2hhcnQge1xuICAgIGhlaWdodDogNDAwcHg7XG4gICAgYm9yZGVyOiAzcHggc29saWQgIzAwMDtcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4zNy9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJ2dWUtZWNoYXJ0c1wiOiBcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1lY2hhcnRzQDYuMC4zL2Rpc3QvaW5kZXguZXNtLmpzXCIsXG4gICAgXCJ2dWUtZGVtaVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL3Z1ZS1kZW1pQDAuOC4wL2xpYi9pbmRleC5lc20ubWpzXCIsXG4gICAgXCJyZXNpemUtZGV0ZWN0b3JcIjogXCJodHRwczovL3VucGtnLmNvbS9yZXNpemUtZGV0ZWN0b3JAMC4zLjAvZXNtL2luZGV4LmpzXCIsXG4gICAgXCJ0c2xpYlwiOiBcImh0dHBzOi8vdW5wa2cuY29tL3RzbGliQDIuNC4wL3RzbGliLmVzNi5qc1wiLFxuICAgIFwiZWNoYXJ0c1wiOiBcImh0dHBzOi8vdW5wa2cuY29tL2VjaGFydHNANS4zLjIvaW5kZXguanNcIixcbiAgICBcImVjaGFydHMvXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vZWNoYXJ0c0A1LjMuMi9cIixcbiAgICBcInpyZW5kZXJcIjogXCJodHRwczovL3VucGtnLmNvbS96cmVuZGVyQDUuMy4xL2luZGV4LmpzXCIsXG4gICAgXCJ6cmVuZGVyL1wiOiBcImh0dHBzOi8vdW5wa2cuY29tL3pyZW5kZXJANS4zLjEvXCIsXG4gICAgXCJ2dWUvc2VydmVyLXJlbmRlcmVyXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9zZXJ2ZXItcmVuZGVyZXJAMy4yLjM3L2Rpc3Qvc2VydmVyLXJlbmRlcmVyLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9)

**Comment by Justineo** [comment]
应该和这个 issue 是同样的问题：
https://github.com/ecomfe/vue-echarts/issues/568#issuecomment-893154124

当开启了 `autoresize` 以后，目前是在 nextTick 中设置 `option` 的，所以正常情况下也需要在 nextTick 才能获取设置完的结果。这目前是一种权衡，可能需要在文档里面说明一下。
