### ISSUE TITLE
[Bug Report] Event modifiers are not supported, and will make the original event invalid

### ISSUE THREAD

**Issue by meteorlxy** [ecomfe/vue-echarts#628]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
- vue@3.2.37
- echarts@5.3.2
- vue-echarts@6.0.3
```

### Details

Event modifiers are not supported. Seems that we don't handle the modifier suffix:

- `@click.once` -> `onClickOnce` -> `clickonce` -> invalid

https://github.com/ecomfe/vue-echarts/blob/57cd2e6a1640d89b663f3a850107291ffc463eb9/src/ECharts.ts#L117-L120
https://github.com/ecomfe/vue-echarts/blob/57cd2e6a1640d89b663f3a850107291ffc463eb9/src/ECharts.ts#L131-L135

### Reproduction

https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmNvbnN0IFZDaGFydCA9ICgpID0+IG51bGxcbmNvbnN0IG9uQ2xpY2tPbmNlID0gKCkgPT4ge31cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxWQ2hhcnQgQGNsaWNrLm9uY2U9XCJvbkNsaWNrT25jZVwiPjwvVkNoYXJ0PlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=

**Comment by Justineo** [comment]
Since all the modifiers except `once` are strongly coupled to DOM events, I think supporting `once` should be enough.
