### ISSUE TITLE
vue生命周期updated响应的时候，一个界面多个vchart 组件会刷新曲线

### ISSUE THREAD

**Issue by Zerbaoo** [ecomfe/vue-echarts#631]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
+-- @vue/cli-plugin-babel@5.0.4
| `-- @vue/babel-preset-app@5.0.4
|   `-- vue@2.6.14 deduped
+-- @vue/composition-api@1.6.2
| `-- vue@2.6.14 deduped
+-- echarts@5.3.2
+-- element-ui@2.15.8
| `-- vue@2.6.14 deduped
+-- vue-echarts@6.0.3
| +-- echarts@5.3.2 deduped
| +-- vue-demi@0.12.5
| | `-- vue@2.6.14 deduped
| `-- vue@2.6.14 deduped
+-- vue@2.6.14
`-- vuex@3.6.2
  `-- vue@2.6.14 deduped
```

### 问题详情

在一个vue界面同时放置多个vchart 组件，
更新data里的任意数据都会刷新vchart的界面

  <v-chart
          ref="electricChart2"
          style="width: 100%; height: 100%"
          :init-options="{ devicePixelRatio: 2 }"
          :option="electricOption2"
          :update-options="{ notMerge: true }"
        />

  <v-chart
          ref="electricChart3"
          style="width: 100%; height: 100%"
          :init-options="{ devicePixelRatio: 2 }"
          :option="electricOption2"
          :update-options="{ notMerge: true }"
        />

### 问题复现

无

**Comment by Justineo** [comment]
请提供问题复现，不然无法提供帮助。
