### ISSUE TITLE
loading / loadingOptions props not working in vue 2.7

### ISSUE THREAD

**Issue by youthug** [ecomfe/vue-echarts#637]
### Confirmation

- [x] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
├── echarts@5.3.3 
├── vue@2.7.3 
└── vue-echarts@6.2.3
```

### Details

`loading` won't change chart's loading animation and `loadingOptions` doesn't take effect either

### Reproduction

https://stackblitz.com/edit/vitejs-vite-jak4rr?file=src/App.vue

**Comment by Justineo** [comment]
The issue seems to be already resolved after upgrading to `vue@2.7.4`.

See https://stackblitz.com/edit/vitejs-vite-nkf98x

**Comment by Justineo** [comment]
F.Y.I. The related issue: https://github.com/vuejs/vue/issues/12624
