### ISSUE TITLE
ability to show some values in label

### ISSUE THREAD

**Issue by VoOneCode** [ecomfe/vue-echarts#638]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

Hi there! OIn pie diagram Please explain how can I do label like 
![image](https://user-images.githubusercontent.com/60251968/179164289-e4f13fa7-d731-416a-b293-8ab4c91d5dcc.png)
with one name and two parameters.
Thanks))

**Comment by Justineo** [comment]
https://echarts.apache.org/en/option.html#series-pie.label.formatter

Please read the documentation of ECharts.

**Comment by VoOneCode** [comment]
already read, no idea. May be with dimensions, but no doc how to use it with data. I need to show one name and two values
