### ISSUE TITLE
Event type missing in .tsx

### ISSUE THREAD

**Issue by ryancui92** [ecomfe/vue-echarts#640]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
vue-echarts 6.2.3
echarts 5.3.3
```

### Details

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/3788103/180167186-28cb02c4-8870-4c31-85b5-133986e9c46a.png">

Everything is ok under vite, click event works well, except the type issue.

### Reproduction

don't think need this

**Comment by Justineo** [comment]
Added basic type support for events in v6.3.2.
