### ISSUE TITLE
Vue2 vue-demi 引用问题

### ISSUE THREAD

**Issue by zhaoyuhang1033** [ecomfe/vue-echarts#645]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
├─┬ @bjwisdom/client-framework@3.5.0-beta.10 // 自研脚手架
│ └── vue@2.6.10 
├── echarts@5.3.3 
├── vue@2.6.14 
└── vue-echarts@6.2.3
```

### Details

根据文档的Vue2环境使用的代码DEMO 进行操作 启动项目编译后
![image](https://user-images.githubusercontent.com/36781875/183329791-b6454ada-5df9-4a51-9ca8-c07592886da5.png)
原因是因为默认使用了vue3的编译环境
然后使用切换工具 /node_modules/vue-echarts/node_modules/.bin/vue-demi-switch  切换为2的版本 就可以了 
但我看 `postinstall.js` 中确实有自动判断版本的逻辑  因为切换只限于自己的电脑版本 其他小伙伴拉下启动项目仍然要切换版本
预期:能够根据vue版本自动切换

### Reproduction

none

**Comment by Justineo** [comment]
本地 `npm install` 应该就可以了。
