### ISSUE TITLE
Shadow properties like `shadowBlur` removes the line on the graph

### ISSUE THREAD

**Issue by JeromeDeLeon** [ecomfe/vue-echarts#648]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
"echarts": "^5.3.3"
"vue": "^3.2.37"
"vue-echarts": "^6.2.3"
```

### Details

The problem is when all the series data have the same value, the line on the graph disappears, but pasting it on echart, it works just fine.

```js
options = {
  xAxis: {
    data: ['2022-07-23', '2022-08-12'],
  },
  yAxis: {
    type: 'value',
  },
  series: [
    {
      data: [519, 519],
      type: 'line',
      lineStyle: {
        width: 3,
        // If I remove these properties, the line on the graph works
        shadowBlur: 2,
        shadowOffsetX: 2,
        shadowOffsetY: 2,
      },
    },
  ],
}
```

### Reproduction

https://stackblitz.com/edit/vue-echarts-vue-3-v7nkjt?file=src/App.vue

**Comment by Justineo** [comment]
This seems to be a problem of ECharts itself. If you switch to its SVG renderer the same problem can be reproduced on ECharts' own [online editor](https://echarts.apache.org/examples/en/editor.html).

**Comment by JeromeDeLeon** [comment]
Thanks for confirming
