### ISSUE TITLE
渲染问题

### ISSUE THREAD

**Issue by thelonelyDreamer** [ecomfe/vue-echarts#649]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
echart-vue-ts@0.0.0 F:\code-note\github\vue-demos\vue-echarts\echart-vue-ts
├─┬ @vitejs/plugin-vue@3.0.3
│ └── vue@3.2.38 deduped
├── echarts@5.3.3
├─┬ vue-echarts@6.2.3
│ ├── echarts@5.3.3 deduped
│ ├─┬ vue-demi@0.13.11
│ │ └── vue@3.2.38 deduped
│ └── vue@3.2.38 deduped
├─┬ vue-router@4.1.5
│ └── vue@3.2.38 deduped
└─┬ vue@3.2.38
  └─┬ @vue/server-renderer@3.2.38
    └── vue@3.2.38 deduped
```

### 问题详情

```
<template>
    <e-charts class="chart" :option="option" />
    <!-- 这个地方访问才会渲染 -->
    <p>{{ option }}</p>
</template>
```

### 问题复现

<template>     <e-charts class="chart" :option="option" />          <p>{{ option }}</p> </template>  <script lang="ts" setup> import { ref, computed, onMounted } from 'vue' const data = ref([     { value: 50, name: 'A' },     { value: 50, name: 'B' },     { value: 50, name: 'C' },     { value: 50, name: 'D' },     { value: 50, name: 'E' }, ]) setInterval(() => {     data.value = data.value.map(item => ({         ...item,         value: Math.random() * 100     })) }, 1000) const option = computed(() => {     return {         xAxis: {             type: 'category',             data: data.value.map(d => d.name)         },         yAxis: {             type: 'value'         },         series: [             {                 data: data.value.map(d => d.value),                 type: 'line'             }         ]     } }) onMounted(() => {  }) </script>  <style scoped> .chart {     height: 400px; } </style>

**Comment by thelonelyDreamer** [comment]
求解

**Comment by Justineo** [comment]
> 请提供一个精炼的问题复现（去除无关依赖的最小化可运行 demo）。如果在线环境无法复现，可以创建对应的 GitHub repo 来提供复现环境。请在下方贴入在 CodeSandbox 上 demo 的链接或 GitHub repo 链接：（[Vue 3 模板](https://codesandbox.io/s/charming-night-2y6m6?file=/src/App.vue) / [Vue 2 模板](https://codesandbox.io/s/suspicious-glitter-mk66j?file=/src/App.vue)）

**Comment by thelonelyDreamer** [comment]
谢谢。我知道原因了，未设置宽和高
