### ISSUE TITLE
建议给项目添加tag和Releases. Please add tag/release to the repo.

### ISSUE THREAD

**Issue by jiawulin001** [ecomfe/vue-echarts#653]
vue-echarts项目作为echarts的vue配套组件，使echarts能适配vue开发者的编程习惯，提高了开发效率，是一款优秀的开源社区作品。但美中不足的是在github没有tag和release，不符合社区规范，不利于版本管理和漏洞溯源，与echarts本体的配套也无法得到保障。可以的话建议尽快发布github上的tag或者release，并在后续npm发布版本时也在github上发布对应tag/release。

As a community work of echarts, this project does not release tag and release on github, which is not in line with the community specification and is not conducive to version management and vulnerability tracing, and the support with echarts itself cannot be guaranteed. If possible, we suggest releasing the tag or release on github as soon as possible, and releasing the corresponding tag/release on github when subsequent npm releases are made.

**Comment by Justineo** [comment]
Published the latest release and tag on GitHub.

https://github.com/ecomfe/vue-echarts/releases/tag/v6.2.3
