### ISSUE TITLE
Transform not working with Vue 3

### ISSUE THREAD

**Issue by alexdohm** [ecomfe/vue-echarts#654]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
├─┬ @vue/cli-plugin-babel@5.0.8
│ └─┬ @vue/babel-preset-app@5.0.8
│   ├─┬ @vue/babel-preset-jsx@1.3.1
│   │ └── vue@3.2.37 deduped
│   └── vue@3.2.37 deduped
├─┬ @vueuse/core@9.1.0
│ ├─┬ @vueuse/shared@9.1.0
│ │ └─┬ vue-demi@0.13.8
│ │   └── vue@3.2.37 deduped
│ └─┬ vue-demi@0.13.8
│   └── vue@3.2.37 deduped
├─┬ bootstrap-vue-3@0.3.4
│ └── vue@3.2.37 deduped
├── echarts@5.3.3
├─┬ vue-echarts@6.2.3
│ ├── echarts@5.3.3 deduped
│ ├─┬ vue-demi@0.13.7
│ │ └── vue@3.2.37 deduped
│ └── vue@3.2.37 deduped
├─┬ vue-router@4.1.5
│ └── vue@3.2.37 deduped
├─┬ vue@3.2.37
│ └─┬ @vue/server-renderer@3.2.37
│   └── vue@3.2.37 deduped
```

### Details

I'm updating my code base from Vue 2 to Vue 3. One of my charts implements echarts transform. I've noticed that even with a simple example, transform doesn't work when I use Vue 3. With Vue 2 this works.

I'm not sure if there is something to do with echarts imports, but I toyed around and couldn't find an import that works.

### Reproduction

https://stackblitz.com/edit/vue-echarts-vue-3-ltlcyr?file=src/App.vue

**Comment by Justineo** [comment]
Not sure what is the expected result but it seems that you are missing the `TransformComponent` in your reproduction (which should be imported and used like other components).

**Comment by alexdohm** [comment]
for those that come here also having issues getting this to work :

make sure you import both of these components

import {
  DatasetComponent,
  TransformComponent
} from 'echarts/components';

echarts.use([
  DatasetComponent,
  TransformComponent
]);
