### ISSUE TITLE
hideOverlap does not work

### ISSUE THREAD

**Issue by mierkismantas** [ecomfe/vue-echarts#655]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
+-- @quasar/app-webpack@3.5.9    
| `-- vue@3.2.31 deduped         
+-- echarts@5.4.0                
+-- vue-currency-input@3.0.0     
| `-- vue@3.2.31 deduped         
+-- vue-echarts@6.2.3            
| +-- echarts@5.4.0 deduped      
| +-- vue-demi@0.13.11           
| | `-- vue@3.2.31 deduped       
| `-- vue@3.2.31 deduped         
+-- vue-i18n@9.1.9               
| `-- vue@3.2.31 deduped         
+-- vue-router@4.0.14            
| `-- vue@3.2.31 deduped         
+-- vue@3.2.31                   
| `-- @vue/server-renderer@3.2.31
|   `-- vue@3.2.31 deduped
+-- vue3-apexcharts@1.4.1
| `-- vue@3.2.31 deduped
+-- vuex-module-decorators@1.2.0
| `-- vue@3.2.31 deduped
`-- vuex@4.0.2
  `-- vue@3.2.31 deduped
```

### Details

I am trying to use this setting
labelLayout: {
  hideOverlap: true
}

I made this sandbox
https://codesandbox.io/s/amazing-dewdney-uj4x78?file=/src/App.vue

Labels do look good
![image](https://user-images.githubusercontent.com/78933635/193233212-e9f228a9-7b7b-4560-a316-10528d11a51f.png)

When I copy & paste code from sandbox to my project, labels are all being showed
![image](https://user-images.githubusercontent.com/78933635/193233702-844c119e-0ce7-4e23-aa16-7c7c8452b2e6.png)

### Reproduction

https://codesandbox.io/s/amazing-dewdney-uj4x78?file=/src/App.vue

**Comment by Justineo** [comment]
The reproduction link seems to work as expected. The screenshot of your project seems to have a lot more data than the reproduction. I don't think it's a problem caused by Vue-ECharts.

**Comment by mierkismantas** [comment]
The problem is that in sandbox screenshot (upper one) some of the labels are hidden (hideOverlap works)
While on my project all labels are being shown - none are hidden (hideOverlap does not work)

Can you please try to copy sandbox code to your local project? (vue@3.2.31/vue-echarts@6.2.3)

**Comment by Justineo** [comment]
Please provide a reproduction repo if the sandbox doesn't reflect the actual problem. Thank you!

**Comment by mierkismantas** [comment]
https://github.com/mierkismantas/TestEcharts here you go :) 
![image](https://user-images.githubusercontent.com/78933635/196431954-f245d0c8-4c4f-401c-a9ce-3b96644b6a40.png) result in repo
![image](https://user-images.githubusercontent.com/78933635/196432101-c02a2efe-6a21-43dc-97dc-03ff44c93582.png)
result in sandbox

**Comment by Justineo** [comment]
Does this only happen with Quasar?

**Comment by mierkismantas** [comment]
I am using Quasar for my project, so this is where i found out about such issue, have not tried other frameworks :)

**Comment by Justineo** [comment]
I can't reproduce this in a project initialized with `create-vue`. Currently I still don't have a clue why this happens in your Quasar project.

**Comment by mierkismantas** [comment]
Will you be able to help me this issue? Maybe I can help you somehow?
