### ISSUE TITLE
ScatterCharts Tooltip Display Error

### ISSUE THREAD

**Issue by anno189** [ecomfe/vue-echarts#656]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
├─┬ @vitejs/plugin-vue-jsx@2.0.1
│ └── vue@3.2.40 deduped
├─┬ @vitejs/plugin-vue@3.1.0
│ └── vue@3.2.40 deduped
├── echarts@5.4.0
├─┬ vue-axios@3.4.1
│ └── vue@3.2.40 deduped
├─┬ vue-echarts@6.2.3
│ ├── echarts@5.4.0 deduped
│ ├─┬ vue-demi@0.13.11
│ │ └── vue@3.2.40 deduped
│ └── vue@3.2.40 deduped
├─┬ vue-router@4.1.5
│ └── vue@3.2.40 deduped
└─┬ vue@3.2.40
  └─┬ @vue/server-renderer@3.2.40
    └── vue@3.2.40 deduped
```

### 问题详情

在 Echart 中和 Vue-Echarts 中显示的toolstip 不一致。

Vue-Echarts中使用 axios 加载通过 option 传递数据。

Vue-Echarts的显示效果
<img width="476" alt="截屏2022-10-01 18 56 50" src="https://user-images.githubusercontent.com/3339262/193406340-671275a4-d5c3-4a4a-9a99-80b52ac29d8a.png">

Echarts 的显示效果
<img width="435" alt="截屏2022-10-01 18 57 13" src="https://user-images.githubusercontent.com/3339262/193406350-982754e8-7b16-4fb3-9cfa-fb042a56c501.png">

### 问题复现

https://codesandbox.io/s/confident-voice-chgp8r

**Comment by Justineo** [comment]
Your reproduction link doesn't seem to be valid and Vue-ECharts won't transform your `option` passed into ECharts itself. I think there's a big chance that you are not passing in the correct option.
