### ISSUE TITLE
update-options 如何使用dispatchAction

### ISSUE THREAD

**Issue by is-cool** [ecomfe/vue-echarts#661]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
6.2.3
```

### Details

update-options 如何使用dispatchAction,看了文档不是很明白
![截屏2022-10-25 11 49 43](https://user-images.githubusercontent.com/78067806/197680153-14ef21d4-2af8-4157-a4f8-e458abca1c47.png)

### Reproduction

https://codesandbox.io/s/funny-black-05z8p0?file=/src/App.vue

**Comment by is-cool** [comment]
<img width="280" alt="截屏2022-10-25 12 10 41" src="https://user-images.githubusercontent.com/78067806/197680597-3eb2b6ee-b8fd-4f0e-98fd-1f41245ae9c9.png">

**Comment by Justineo** [comment]
你这个用法的来源是？

**Comment by is-cool** [comment]
> 你这个用法的来源是？

是我看错了，我是想用静态的方法，对图例切换做更改的，调用dispatchAction在点击图例的时候，隐藏其他图例。
