### ISSUE TITLE
结合dialog组件使用，图表展示问题

### ISSUE THREAD

**Issue by Shadows-kk** [ecomfe/vue-echarts#669]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

我在使用dialog组件展示图表的时候，出现找不到dom的警告。希望重新调用下vue-echarts的初始化方法，这个有无大佬指点下怎么去操作哇

**Comment by ntnyq** [comment]
Please provide a minimal reproduction.

**Comment by Justineo** [comment]
Closing this as we can't offer help without a minimal repro.
