### ISSUE TITLE
I cannot render MarkPoint in vue-echarts

### ISSUE THREAD

**Issue by bromoapp** [ecomfe/vue-echarts#673]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
└─┬ vue@3.2.45
  └─┬ @vue/server-renderer@3.2.45
    └── vue@3.2.45 deduped
```

### Details

I tried to implement a Markpoint in my quasar proj, but I cannot make it works.

So I test my OPTION setup in [https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh](https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh) and it works (you can see my attached screenshot it has a blue color pin)

So I create a project to recreate a bug report in https://stackblitz.com/ and it also failed to render my Markpoint.

Below image is my OPTION implemented in https://echarts.apache.org/examples/en/editor.html?c=candlestick-sh
<img width="616" alt="Capture" src="https://user-images.githubusercontent.com/21073705/203079833-391721de-d871-44d3-873d-cc0836a93df7.PNG">

based on these two, I think the problem may not in the echarts but at vue-echarts.

### Reproduction

https://stackblitz.com/edit/vue-echarts-vue-3-mn3yng?file=src%2FApp.vue

**Comment by ntnyq** [comment]
You missed to import `MarkPointComponent`

```diff
import {
  TitleComponent,
  LegendComponent,
  GridComponent,
  TooltipComponent,
  DataZoomComponent,
+ MarkPointComponent,
} from 'echarts/components';

use([
  CanvasRenderer,
  CandlestickChart,
  TitleComponent,
  LegendComponent,
  GridComponent,
  TooltipComponent,
  DataZoomComponent,
+ MarkPointComponent,
]);
```

Checkout all available components [here](https://github.com/apache/echarts/tree/master/src/component)

**Comment by bromoapp** [comment]
OMG... that's embarrassing... thanks mate :)
