### ISSUE TITLE
使series.data支持对象数组

### ISSUE THREAD

**Issue by Valar103769** [ecomfe/vue-echarts#674]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

这样一个需求:添加和删除一条线
echarts旧版本使用的series.data. 能做到，但是不支持对象数组，
echarts新版支持对象数组，使用dataset.source ，动态显隐一条线。需要搭配sourceindex，就需要重新克隆原来的dataset.source ，有点麻烦，
能否让series.data支持 对象数组
echarts旧版本 估计不会添加东西了

**Comment by Justineo** [comment]
这个项目只处理对 ECharts 原生功能的封装，ECharts 本身的需求请提到 https://github.com/apache/echarts。
