### ISSUE TITLE
使用 uniapp cli 项目出现 vue 动态组件引入失败错误

### ISSUE THREAD

**Issue by alexzarkk** [ecomfe/vue-echarts#676]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
+-- echarts@5.4.0
+-- vue@2.7.10
`-- vue-echarts@6.2.3
```

### 问题详情

项目使用 uniapp 的 Hbuilder 进行开发，出现 vue 动态组件引入失败错误，导致项目无法启动，希望开源小组能升级兼容一下

![image](https://user-images.githubusercontent.com/62702808/205532473-838c83ed-961f-4420-9c7c-d655396a2f8a.png)

### 问题复现

https://github.com/alexzarkk/uni-vue-echarts

**Comment by Justineo** [comment]
Please provide a reproduction step.

**Comment by alexzarkk** [comment]
1.pull  project (https://github.com/alexzarkk/uni-vue-echarts)
2. npm i
3. import project by Hbuilder (https://www.dcloud.io/hbuilderx.html)
4. run to chrome

**Comment by Justineo** [comment]
I'm sorry but I don't use HBuilder and maybe it's better to look for help in the uni-app community first, or try [earlier workarounds](https://github.com/ecomfe/vue-echarts/issues/644#issuecomment-1211434054) for similar problem.
