### ISSUE TITLE
provide 的 [THEME_KEY] 不能动态监听其变化来实现切换主题

### ISSUE THREAD

**Issue by Krue1** [ecomfe/vue-echarts#677]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
+-- echarts@5.3.3
+-- vue@2.7.3
`-- vue-echarts@6.2.3
```

### 问题详情

我希望在页面顶层容器通过provide提供主题，然后让下属所有vue-echarts都响应这个主题变更，这个变更是发生在运行时的。目前看来，是不是一定要在每一个下属组件通过`theme`这个prop来传入改变？但是这样操作的话，跟没有这个provide没什么区别吧 非常麻烦。

在问题复现的链接里面，我在mounted处用定时器模拟了运行时的主题变更。

### 问题复现

https://codesandbox.io/s/great-snowflake-bzvpd8?file=/src/App.vue

**Comment by Krue1** [comment]
> 使用 Composition API 的话应该是可以的，你可以 provide 一个 `ref` 进去。

可否兼容一下Options API呢，毕竟大部分vue2项目都是用options的

**Comment by Justineo** [comment]
Implemented in v6.3.0.

---

可以参考[这里的说明](https://github.com/ecomfe/vue-echarts/blob/main/README.zh-Hans.md#:~:text=Vue%203-,vue%202,-%E6%96%B9%E6%B3%95)，通过 `this.theme.value = 'light'` 这样来进行切换。
