### ISSUE TITLE
Resizing shouldn't call `brushSelected` event 

### ISSUE THREAD

**Issue by ashokgelal** [ecomfe/vue-echarts#681]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
"vue-echarts": "^6.3.3"
"echarts": "^5.4.1"
```

### Details

When autoresize is set, resizing the window calls `brushSelected` event repeatedly. 

Steps to repro:
1. Select some scatter dots using brush selection. 
2. Look at console, handler is called as it should
3. Now trigger a resize (either resizing the window or resizing the dev tool view)
4. handler is called multiple times but since no brush-selection has taken place, it shouldn't

### Reproduction

https://codesandbox.io/s/adoring-euclid-rfu8z1?file=/src/App.vue

**Comment by Justineo** [comment]
> * [x]  I can confirm this problem is not reproducible with ECharts itself.

It *is* reproducible with ECharts alone: https://codepen.io/Justineo/pen/GRBgbRb

Please report this to [apache/echarts](https://github.com/apache/echarts).
