### ISSUE TITLE
新功能建议, 自定义图表销毁时间

### ISSUE THREAD

**Issue by l246804** [ecomfe/vue-echarts#682]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

我看到有做 `web-component` 卸载时再销毁 `echarts` 实例，但实际上我的应用运行在 `web-view` 中，可能并不支持自定义元素。

目前在转场动画时图表仍然会提前卸载而出现空白，所以采用 `pnpm patch` 方法增加了 `cleanupDelay` 属性用以解决，所以希望能否官方支持类似的属性或功能。

![image](https://user-images.githubusercontent.com/53589602/210029077-b9a19d90-c0ac-47f8-91ad-1086be43cdfc.png)

**Comment by l246804** [comment]
我尝试在最新版 `edge` 浏览器中查看自定义元素的卸载是否成功，但好像仍然无效，我并没有看到自定义元素有成功绑定上 `__dispose` 属性，不知道是否是我的使用方式有问题？

![image](https://user-images.githubusercontent.com/53589602/210029437-8c53520b-f728-4176-8992-1b3a6fdbef25.png)

![image](https://user-images.githubusercontent.com/53589602/210029452-5844958c-05e3-4f0e-ac14-21eca6e66efe.png)

**Comment by Justineo** [comment]
`__dispose` 会在 `onBeforeUnmount` 里才绑，你渲染完是看不到的。如果确认在 Edge 中无法生效，请提供一个最小的复现，谢谢。

目前只有自定义元素的 `disconnectedCallback` 可以比较准确地在元素实际被从 DOM 中移除的时候得到通知，而且这个可以不需要额外的 API 配置。手动增加延迟的方式，不是那么准确，我再考虑一下。

**Comment by l246804** [comment]
我删除依赖重新尝试了下，问题已经解决了，在 `App` 端也有效👍。
