### ISSUE TITLE
RangeError: Maximum call stack size exceeded with reactivity

### ISSUE THREAD

**Issue by mass85** [ecomfe/vue-echarts#684]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
example@0.0.0 C:\Users\maad\demo
├─┬ @storybook/testing-vue3@0.0.2
│ └── vue@3.2.45 deduped
├─┬ @storybook/vue3@6.5.5
│ ├─┬ vue-docgen-api@4.46.0
│ │ └─┬ vue-inbrowser-compiler-utils@4.44.23
│ │   ├─┬ vue-inbrowser-compiler-demi@4.44.23
│ │   │ └── vue@3.2.45 deduped
│ │   └── vue@3.2.45 deduped
│ └── vue@3.2.45 deduped
├─┬ @vue/cli-plugin-babel@5.0.4
│ └─┬ @vue/babel-preset-app@5.0.4
│   └── vue@3.2.45 deduped
├─┬ @vue/cli-plugin-typescript@5.0.4
│ └── vue@3.2.45 deduped
├─┬ @vue/test-utils@2.0.0-rc.19
│ └── vue@3.2.45 deduped
├─┬ @vue/vue3-jest@27.0.0
│ └── vue@3.2.45 deduped
├── echarts@5.4.1
├─┬ storybook-vue3-router@2.2.1
│ └── vue@3.2.45 deduped
├─┬ vue-echarts@6.5.0
│ ├── echarts@5.4.1 deduped
│ ├─┬ vue-demi@0.13.11
│ │ └── vue@3.2.45 deduped
│ └── vue@3.2.45 deduped
├─┬ vue-router@4.0.16
│ └── vue@3.2.45 deduped
└─┬ vue@3.2.45
  └─┬ @vue/server-renderer@3.2.45
    └── vue@3.2.45 deduped
```

### Details

Whenever I add reactivity to option and series with `computed` I run into problems with rendering. Currently the main problem is exception `RangeError: Maximum call stack size exceeded`. But occasionally I may see in console logs related to lifecycle, i.e. after resizing window: 
```
`resize` should not be called during main process.
```

### Reproduction

https://codesandbox.io/s/ecstatic-frog-2km23y?file=/src/App.vue

**Comment by Justineo** [comment]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/1726061/210934408-58e9b527-6633-4f82-8c8b-4b9e30612280.png">

You are passing a ref without calling `.value` into the option.
