### ISSUE TITLE
CSP issue - style-src : 'unsafe-inline'

### ISSUE THREAD

**Issue by X-W-W** [ecomfe/vue-echarts#687]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

x-vue-echarts{display:block;width:100%;height:100%}

this style inlines into page and doesn't respect CSP.

Do we have any solution?

**Comment by Justineo** [comment]
`vue-echarts@6.5.2` now provide additional dist files that do not include inline style tags. You can import JS from `vue-echarts/dist/csp/index.esm.min.js` and include `vue-echarts/dist/csp/style.css` yourself.
