### ISSUE TITLE
不注册@vue/composition-api无法使用

### ISSUE THREAD

**Issue by chinesecooly** [ecomfe/vue-echarts#688]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
+-- echarts@5.4.0
+-- vue@2.6.12
+-- vue-echarts@6.2.3
`-- vue-json-editor@1.4.3
  `-- vue@2.6.12  deduped
```

### 问题详情

如果不在我的项目中使用以下代码进行@vue/composition-api的注册

> import Vue from 'vue'
> import VueCompositionAPI from '@vue/composition-api'
> Vue.use(VueCompositionAPI) 

那么图表将不显示且出现以下错误

> [Vue warn]: `createElement()` has been called outside of render function.

### 问题复现

与vue2模板一致

**Comment by Justineo** [comment]
> 要在 `vue@2.7.0` 之前的版本中使用 Vue-ECharts，必须安装 `@vue/composition-api`。

https://github.com/ecomfe/vue-echarts/blob/main/README.zh-Hans.md#vue-2-%E6%94%AF%E6%8C%81
