### ISSUE TITLE
vue3中折线图点击事件无法触发

### ISSUE THREAD

**Issue by chqfly** [ecomfe/vue-echarts#692]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
"dependencies": {
    "echarts": "^5.4.1",
    "vue": "^3.2.45",
    "vue-echarts": "^6.5.2"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^4.0.0",
    "vite": "^4.0.1"
  }
```

### 问题详情

vue3中折线图点击事件无法触发

### 问题复现

https://stackblitz.com/edit/vue-echarts-vue-3-qcbeuk?file=src%2FApp.vue,package.json

**Comment by Justineo** [comment]
这个 `click` 事件是 ECharts 本身的 `click` 事件，是需要点击到数据点上才会触发的。

**Comment by chqfly** [comment]
> 这个 `click` 事件是 ECharts 本身的 `click` 事件，是需要点击到数据点上才会触发的。

Thinks
