### ISSUE TITLE
怎么使用dispose方法

### ISSUE THREAD

**Issue by lzl132264** [ecomfe/vue-echarts#693]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

vue-echarts没有暴露任何方法。要怎么使用dispose

**Comment by Justineo** [comment]
组件销毁时会自动 `dispose`，请问手动调用的场景是？

**Comment by lzl132264** [comment]
> 组销毁时会自动`dispose`，请问手动调整使用的场景是？
我需要根据下拉框的值来切换不同的图形

**Comment by Justineo** [comment]
切换 `option` 或者用 v-if 切换多个组件实例就可以了。没有手动 `dispose` 的必要。
