### ISSUE TITLE
开发环境和生产环境饼图label显示不一致

### ISSUE THREAD

**Issue by chqfly** [ecomfe/vue-echarts#698]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
"echarts": "^5.4.1",
"vue": "^3.2.45",
"vue-echarts": "latest"
```

### 问题详情

1. 开发环境：

```base
npm run dev
```

显示正常，效果如下：
<img width="413" alt="image" src="https://user-images.githubusercontent.com/17806082/218721971-3aba4deb-8d3c-4a0f-bb02-7b2e411fbe35.png">

2. 生产环境

```base
npm run build
npm run preview
```

圆中心label显示重叠，效果如下：
<img width="385" alt="image" src="https://user-images.githubusercontent.com/17806082/218721846-03020422-2123-4f8e-aec8-80f9da5263d7.png">

### 问题复现

https://stackblitz.com/edit/vue-echarts-vue-3-n2cgoq?file=src%2FApp.vue,package.json

**Comment by Justineo** [comment]
可以给 `series[0].label` 添加 `backgroundColor: '#100C2B'` 来绕过，具体原因暂不清楚。
