### ISSUE TITLE
Is it feasible to use Vue 2 and Options API for Vue-Echarts 6?

### ISSUE THREAD

**Issue by LumineLittlelight** [ecomfe/vue-echarts#699]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

Hi, 

May I check is there any documentation guide on how to implement Vue-Echarts with Options API on Vue 2?
Or we must use CompositionAPI when making the Vue component with Vue-Echarts inside?

Looking forward to your explanation.
Thank you.

**Comment by Justineo** [comment]
> *** Vue 2 support
> * If you are using version prior to `vue@2.7.0`, `@vue/composition-api` is required to be installed to use Vue-ECharts with Vue 2.

You can still use options API but Vue-ECharts itself relies on installing `@vue/composition-api`. We have [example code](https://github.com/ecomfe/vue-echarts#vue-2-support:~:text=%3C/style%3E-,Vue%202%20Demo%20%E2%86%92,-We%20encourage%20manually) in the README.
