### ISSUE TITLE
Can we have slider to select the bar chart?

### ISSUE THREAD

**Issue by NaveenReddy1** [ecomfe/vue-echarts#700]
### Confirmation

- [ ] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

Hi first of all thanks for the library, just want to know is there any option to select the bar chart with slider(attaching the screenshot).
<img width="408" alt="Screenshot 2023-02-22 at 4 24 15 PM" src="https://user-images.githubusercontent.com/42110995/220600031-856cc1bc-3e70-448b-a8f8-e3770c377da9.png">

Something like this whenever i change the slider, chart also get selected.

Let me know if this is feasible or not. If feasible, please help me with the sample code?

**Comment by Justineo** [comment]
> [ ] I can confirm this is a feature request for the Vue component instead of ECharts itself.

We add this into the issue template for a reason. Please make such feature requests at https://github.com/apache/echarts.
