### ISSUE TITLE
option.series 动态数组无法触发更新渲染

### ISSUE THREAD

**Issue by jiang-24-gdufs** [ecomfe/vue-echarts#708]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
无输出, 通过Demo Fork重现
```

### 问题详情

如果series为一个数组, 我想动态增减改数组, 增加(push)的时候会触发渲染, 删除(shift/splice)时不会触发渲染

### 问题复现

https://stackblitz.com/edit/vue-echarts-vue-3-3hys4r?file=src%2FApp.vue

**Comment by Justineo** [comment]
你可以使用 `update-options` 这个 prop 把 `notMerge` 设置为 `true`。这个是 ECharts 本身的数据合并逻辑。
