### ISSUE TITLE
Data with timeline + dataset is not displayed

### ISSUE THREAD

**Issue by m-chebli** [ecomfe/vue-echarts#709]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
echarts-timeline@0.0.0 /home/manfred/workspace/echarts-timeline
├─┬ @vitejs/plugin-vue@4.2.1
│ └── vue@3.2.47 deduped
├── echarts@5.4.2
├─┬ element-plus@2.3.4
│ ├─┬ @element-plus/icons-vue@2.1.0
│ │ └── vue@3.2.47 deduped
│ ├─┬ @vueuse/core@9.13.0
│ │ ├─┬ @vueuse/shared@9.13.0
│ │ │ └─┬ vue-demi@0.14.0
│ │ │   └── vue@3.2.47 deduped
│ │ └─┬ vue-demi@0.14.0
│ │   └── vue@3.2.47 deduped
│ └── vue@3.2.47 deduped
├─┬ vue-echarts@6.5.5
│ ├── echarts@5.4.2 deduped
│ ├─┬ vue-demi@0.13.11
│ │ └── vue@3.2.47 deduped
│ └── vue@3.2.47 deduped
└─┬ vue@3.2.47
  └─┬ @vue/server-renderer@3.2.47
    └── vue@3.2.47 deduped
```

### Details

Hi,

I am trying to display data using echart's timeline feature. I want to display data by date (in category, not time axis), and switch between quarters when modifying the timeline.

I wrote a first implementation that works, using echarts natively: https://stackblitz.com/edit/js-jufvxz?file=index.html

However, when I try to wrap everything into vue-echarts, the data is not loaded: https://stackblitz.com/edit/vitejs-vite-tved4q?file=src%2FApp.vue

I have no error message, and my configuration between the two projects is the same (the vuejs one is a bit simplier).

Do you have any idea why the data does not load?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-tved4q?file=src%2FApp.vue

**Comment by Justineo** [comment]
You need to import and use `DatasetComponent` as well:

https://stackblitz.com/edit/vitejs-vite-cuwt5t?file=src%2FApp.vue
