### ISSUE TITLE
Huge bundle is a problem. Some instruction or functionality for reducing is required.

### ISSUE THREAD

**Issue by Claus1** [ecomfe/vue-echarts#710]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

Adding 1 chart to a program increases bundle size + 1.1MB.  vue-echarts takes 300 KB , 800KB - echarts. There is no clear instruction and examples how to make reasonable size for using the library when use 1-2 charts. https://github.com/apache/echarts/blob/master/src/echarts.all.ts and https://github.com/apache/echarts/pull/13890 are parts of puzzle and require more experience then most users have.  Direct following instructions reduces the bundle to >600k for 1 chart and not more.

**Comment by Justineo** [comment]
Please read the examples provided in the [README](https://github.com/ecomfe/vue-echarts#example).

**Comment by Claus1** [comment]
The Readme method adds 600k+ for 1 chart as described above. If it is a minimum bundle size, ok.

**Comment by Justineo** [comment]
https://bundlephobia.com/package/vue-echarts@6.5.5

`vue-echarts` is only 11.2kB minified. If it takes 300kB in your build, there’s definitely something wrong in your build config.

**Comment by Claus1** [comment]
vue-echarts imports eharts/core as I saw. anyway  a minimum bundle size is a question.
