### ISSUE TITLE
Events not firing on Line Charts for vue 2

### ISSUE THREAD

**Issue by Turqueso** [ecomfe/vue-echarts#712]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
"echarts": "^5.4.2",
"vue": "^2.7.14",
"vue-echarts": "^6.5.4"
```

### Details

Events for line chart are not firing, I created a very minimal line chart on stackblitz and added a click event but it is not firing. I tried other events like mouseover and neither is firing.

Example of line chart not firing click event: https://stackblitz.com/edit/vue-echarts-vue-2-fmrulj
Example with Pie chart working for comparison: https://stackblitz.com/edit/vue-echarts-vue-2-rjd5c8

### Reproduction

https://stackblitz.com/edit/vue-echarts-vue-2-fmrulj

**Comment by Justineo** [comment]
It's working as expected. Line chart clicks only work when you click on nodes.
