### ISSUE TITLE
group分组

### ISSUE THREAD

**Issue by kenixFog** [ecomfe/vue-echarts#713]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

目前分组联动，需要手动调用connect ，稍微有些麻烦~~是否可以根据group值，自动联动？如果group有效，创建过程中自动调用connect

**Comment by Justineo** [comment]
是否 connect 是设置在组上的，不是设置在图表实例上，所以我理解图表实例上不应该有自动 connect 的逻辑。而且这个会和手动 disconnect 的时机产生冲突，不能说我 disconnect 以后又渲染一个带 group 的图，又自动全部 connect 了。
