### ISSUE TITLE
配置了autoresize,echarts的resize事件不会重绘graphic的元素

### ISSUE THREAD

**Issue by zjx960124** [ecomfe/vue-echarts#714]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

配置了autoresize,echarts的resize事件不会重绘graphic的元素。

**Comment by Justineo** [comment]
如果绑在 `finished` 事件的时候去更新符合预期吗？

**Comment by zjx960124** [comment]
resize事件好像也不会触发finished,我监听了DIV变化，dispatchAction激活finished也无效，当配置数据有变化时才会生效finished

···
nextTick(() => {
  // vChartRef为vue-charts实例
  console.log(vChartRef.value);
  vChartRef.value!.chart.on('finished', function () {
    console.log('渲染完成');
  });
  const resizeObserver = new ResizeObserver((entries) => {
    for (let entry of entries) {
      vChartRef.value!.chart.dispatchAction({
        type: 'finished',
      });
    }
  });
  resizeObserver.observe(vChartRef.value!.root);
});
···

**Comment by Justineo** [comment]
Implemented in `v6.6.0`. Now `autoresize` accepts an options object like `{ onResize: () => { /* custom callback */ } }` so that you can specify a custom resize callback.
