### ISSUE TITLE
readme demo，点击vue2 仍然会进入vue3的demo

### ISSUE THREAD

**Issue by songkainpu** [ecomfe/vue-echarts#715]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

readme demo，点击vue2 仍然会进入vue3的demo

**Comment by Justineo** [comment]
具体是哪个链接？

**Comment by songkainpu** [comment]
<img width="906" alt="image" src="https://github.com/ecomfe/vue-echarts/assets/43289139/5b7e5675-7836-43e4-9ec9-7d5b978dfc18">

https://stackblitz.com/edit/vue-echarts-vue-2?file=src%2FApp.vue

<img width="2026" alt="image" src="https://github.com/ecomfe/vue-echarts/assets/43289139/1861c377-41d5-493b-97ad-82afb3b5d282">

**Comment by songkainpu** [comment]
点了一下 vue3 的link， 发现是这两个项目配置反了

**Comment by Justineo** [comment]
没有配置反，Vue 2 的例子是基于 Vue 2.7 的。
