### ISSUE TITLE
View not updated

### ISSUE THREAD

**Issue by l406054531** [ecomfe/vue-echarts#718]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
no error
```

### 问题详情

   <v-chart class="chart" ref="chartRef" :option="option" />
I can add data to option, such as yAxis or series, but the next assignment is missing the existing yAxis or series and the view will not be updated

### 问题复现

https://codesandbox.io/s/intelligent-kate-q8k22f

**Comment by Justineo** [comment]
https://codesandbox.io/s/intelligent-kate-q8k22f

This link only contains default demo of this project. Please add a minimal reproduction of your issue.
