### ISSUE TITLE
Click does not work at LineChart rich configuration.  ToolboxView.js is not accessible. 

### ISSUE THREAD

**Issue by Claus1** [ecomfe/vue-echarts#725]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
vue@3.2.47 deduped
├── echarts@5.4.2
├─┬ gitart-vue-dialog@1.1.0
│ └── vue@3.2.47 deduped
├─┬ vue-echarts@6.5.5
│ ├── echarts@5.4.2 deduped
│ ├─┬ vue-demi@0.13.11
│ │ └── vue@3.2.47 deduped
│ └── vue@3.2.47 deduped
├─┬ vue-router@4.1.1
│ └── vue@3.2.47 deduped
└─┬ vue@3.2.47
  └─┬ @vue/server-renderer@3.2.47
    └── vue@3.2.47 deduped
```

### Details

Click event does not work in my LineChart. Also although the same code produce in my project a normal chart, at Codesandbox it produces an error
```
Unable to open 'ToolboxView.js': File not found (file:///sandbox/node_modules/echarts/lib/component/toolbox/ToolboxView.js).
``` 

### Reproduction

https://codesandbox.io/s/wonderful-https-dkgjpw?file=/src/App.vue

**Comment by Justineo** [comment]
> * [x]  I can confirm this problem is not reproducible with ECharts itself.

Your `option` doesn't work for ECharts itself. You should pass in a [`onclick` callback to `toolbox.feature.mySwitcher`](https://echarts.apache.org/en/option.html#toolbox.feature). 

And [it works at CodeSandbox](https://codesandbox.io/s/condescending-orla-mzht47).

**Comment by Claus1** [comment]
Thanks for help, I does not face issues with toolbox, with click on chart area only. the problem still exist in your example, @click on chart does not work, 
this.$refs.chart.chart.on('click', (e) => alert('!')) does not work also, as you can see https://codesandbox.io/s/vigorous-roman-g5cpvd?file=/src/App.vue with added mounted and removed toolbox.

**Comment by Justineo** [comment]
For line charts, ECharts only triggers a click callback on symbols while you added `symbol: 'none'` in your option so that the click callback won't be called.

Please check the problem isn't reproducible with ECharts alone before reporting to this repo.

**Comment by Claus1** [comment]
Thanks!
