### ISSUE TITLE
Can you provide an example of vue2.6.14, preferably with an online address .

### ISSUE THREAD

**Issue by mdxiaohu** [ecomfe/vue-echarts#726]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

Although this address is from Vue2, the version is 2.7 or higher .
`https://stackblitz.com/edit/vue-echarts-vue-2?file=src%2FApp.vue`
It would be great to provide an online address of 2.6.14 .

**Comment by Justineo** [comment]
You should use `@vue/composition-api` for Vue 2.6. There's nothing else different from 2.7.

**Comment by mdxiaohu** [comment]
@Justineo  vue2.6.14没有这个defineComponent

**Comment by Justineo** [comment]
> You should use
> # `@vue/composition-api`
> for Vue 2.6. There's nothing else different from 2.7.
