### ISSUE TITLE
The `Component [feature] is used but not imported.` warnings are only partially implemented..

### ISSUE THREAD

**Issue by francisashley** [ecomfe/vue-echarts#733]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
^6.6.1
```

### Details

Spent ages trying to figure out why `xAxis.markArea` was not working until testing another feature that threw `Component visualMap is used but not imported.` This issue would have been resolved faster if this warning was in place for `markArea`.

### Reproduction

null

**Comment by Justineo** [comment]
Please report this to https://github.com/apache/echarts.
