### ISSUE TITLE
vue3 使用vue-echarts会报错    help me

### ISSUE THREAD

**Issue by ZhangMin1998** [ecomfe/vue-echarts#734]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
echarts ^5.4.3
vue-echarts ^6.6.1
```

### Details

[Vue warn]: Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function. 
![image](https://github.com/ecomfe/vue-echarts/assets/66857222/5840bec7-7608-4702-b7bb-e1a5bf4a31f6)

### Reproduction

0.0

**Comment by Justineo** [comment]
Minimal reproduction is required.

**Comment by Justineo** [comment]
Closing this for now. Please open a new issue if you can provide a minimal reproduction.

**Comment by ZhangMin1998** [comment]
I didn't understand why an error was reported in Vue3

**Comment by ChengJieLiu3** [comment]
same problem for me!

**Comment by Justineo** [comment]
Maybe you are importing multiple versions of `vue`.
