### ISSUE TITLE
echarts 的 getInstanceByDom 无法正常获取到实例

### ISSUE THREAD

**Issue by twt898xu** [ecomfe/vue-echarts#740]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
vue-echarts:6.6.1
```

### 问题详情

<img width="1073" alt="image" src="https://github.com/ecomfe/vue-echarts/assets/28769187/a1de2306-02cf-4164-bc24-eefdb526796c">

最新的vue-echarts生成的dom 

_echarts_instance_ 这个属性在 内部的DIV元素上而不是在 x-vue-echarts这个元素上，导致 getInstanceByDom 方法无法通过 x-vue-echarts 拿到chat实例。这与之前版本的表现不同

### 问题复现

none

**Comment by Justineo** [comment]
Vue-ECharts 并不对外保证自身的 DOM 结构，所以这并不是一个 bug。你是用 `getInstanceByDom` 的场景是什么？

**Comment by twt898xu** [comment]
@Justineo  通过实例的 getOption 方法来获取配置。之前逻辑类似于 `getInstanceByDom(document.querySelector('x-vue-echarts')).getOption()` 6.6.1之后得修改成 `getInstanceByDom(document.querySelector('x-vue-echarts').firstChild).getOption()` 了

**Comment by Justineo** [comment]
你可以用 ref 获取组件实例，上面有 `getOption` 方法。
