### ISSUE TITLE
getInstanceByDom stopped working

### ISSUE THREAD

**Issue by DMOAbove** [ecomfe/vue-echarts#742]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
echarts 5.4.3
vue-echarts 6.6.1
```

### Details

With echarts 5.4.2  and vue-echarts 6.6.0 it works.
If I update only echarts to 5.4.3 it still works.
 
BUT if I update vue-echarts to 6.6.1 it stops working.

The line that returns undefined after updating is: const chartInstance = getInstanceByDom(chartContainer as HTMLElement);

### Reproduction

Sorry, dont know how to create an example showing the problem

**Comment by Justineo** [comment]
We do not really guarantee the DOM structure of the chart component. It’s not a part of the public API. You can access the chart instance via the `chart` property on the component ref.

**Comment by DMOAbove** [comment]
What do you mean by "It’s not a part of the public API"?

I can see that it's a function from echart API:
https://echarts.apache.org/en/api.html#echarts.getInstanceByDom

**Comment by Justineo** [comment]
In ECharts it ensures you can get the instance from the element with which you initialize the it. But in the Vue component version we actually don't expose where we would initialize the chart instance and that's kind of the point of encapsulating a component: hiding the implementation details.
