### ISSUE TITLE
 import code generator 如何使用

### ISSUE THREAD

**Issue by lihaozzx** [ecomfe/vue-echarts#744]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
https://vue-echarts.dev/#codegen
```

### 问题详情

`options = {}`

`var options = {}`

`export const options = {}`

`export default {options = {}}`

都报错
```

/* Invalid ECharts option */

// Cannot read properties of undefined (reading 'options')
```

### 问题复现

- -

**Comment by zws-code** [comment]
确定一样的问题.   怎么换姿势都不对

**Comment by Justineo** [comment]
直接贴 `option` 的值（没有 `option = ` 这种）。

**Comment by Justineo** [comment]
Fixed and added example code.
