### ISSUE TITLE
'"vue-demi"' has no exported member named 'DefineComponent'

### ISSUE THREAD

**Issue by slavonicsniper** [ecomfe/vue-echarts#750]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
├─┬ vue-echarts@6.6.2
│ ├── echarts@5.4.3 deduped
│ ├─┬ vue-demi@0.13.11
│ │ └── vue@2.6.14 deduped
│ └── vue@2.6.14 deduped
```

### Details

ERROR in .../node_modules/vue-echarts/dist/index.vue2.d.ts(1,10):
1:10 '"vue-demi"' has no exported member named 'DefineComponent'. Did you mean 'defineComponent'?
  > 1 | import { DefineComponent, Ref } from 'vue-demi';

### Reproduction

https://codesandbox.io/p/sandbox/suspicious-glitter-mk66j

**Comment by slavonicsniper** [comment]
[related issue](https://github.com/ecomfe/vue-echarts/issues/520)

**Comment by slavonicsniper** [comment]
I setup a test vue project via vue-cli and I could not reproduce the issue using vue@2.6.14 and the vue-echarts@6.6.2 but it's not identical to the project where I have the issue, I cannot share that project though, will try to match all the other config, tsconfig, eslintrc.js, etc... whether I manage to reproduce it. If you have any insights what I should look for specifically, please let me know. It looks like people had this issue in past but all of them were closed without any specific solution.

**Comment by slavonicsniper** [comment]
[reproduced here](https://github.com/slavonicsniper/vue-echarts-test)

updating 'typescrit' npm seems to help

**Comment by Justineo** [comment]
Oh I see, the `DefineComponent` type is only exported from `vue` after v2.7. I'd suggest you to upgrade to `vue@2.7`.

**Comment by Justineo** [comment]
Hello, this issue should be resolved in v6.6.8. Could you please confirm?

**Comment by kingyue737** [comment]
@Justineo https://www.npmjs.com/package/vue-echarts?activeTab=versions
 v6.6.8 has not been published on npm

**Comment by Justineo** [comment]
> v6.6.8 has not been published on npm

I'm sorry, didn't check the publish result 😅

It's published now.
