### ISSUE TITLE
From version 6.6.1 setting min-height make the chart disappear (height=0px)

### ISSUE THREAD

**Issue by digEmAll** [ecomfe/vue-echarts#761]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

`<script> tag`

### Versions

```sh
from 6.6.1 to the latest (currently 6.6.8)
```

### Details

In versions `<= 6.0.0`, setting the `min-height` of the chart element to a fixed value and letting echarts automatically compute the size  worked flawlessly.
From version `6.6.1+` this does not work anymore, the chart is not visible because the computed `height` is `0px`.
Please check the following very small codepen:
https://codepen.io/digemall/pen/BabvGOE

If you change the `vue-echarts` library version to `6.6.1` (or more) the chart disappears.

### Reproduction

https://codepen.io/digemall/pen/BabvGOE

**Comment by Justineo** [comment]
It should be fixed in v6.6.9.
