### ISSUE TITLE
Default ESM package

### ISSUE THREAD

**Issue by Shyam-Chen** [ecomfe/vue-echarts#762]
### Confirmation

- [X] I can confirm this is a feature request for the Vue component instead of ECharts itself.

### Details

Ref: https://github.com/apache/echarts/pull/19513 (`echarts` v5.5)

Would you like to follow the updates?

**Comment by Shyam-Chen** [comment]
If supported, Vitest could do without this line.

```diff
# vitest
  resolve: {
    alias: {
      '~': path.resolve(__dirname, 'src'),
      '@': path.resolve(__dirname, 'src'),
      mock: path.resolve(__dirname, 'mock/src/routes'),
    },
-   mainFields: ['module'],
  },
```

**Comment by Justineo** [comment]
Let's track this at #627.
