### ISSUE TITLE
useAutoresize throttle switch to requestAnimationFrame method

### ISSUE THREAD

**Issue by xstxhjh** [ecomfe/vue-echarts#768]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

changing the component size like this will be smoother.

**Comment by Justineo** [comment]
This required the re-render of all charts on a same page within ~16ms. Do you have an actual use case?

**Comment by xstxhjh** [comment]
> 这需要在大约 16 毫秒内重新渲染同一页面上的所有图表。您有实际的用例吗？

Some chart components need to gradually become wider or higher, which can appear a bit laggy at times.

**Comment by xstxhjh** [comment]
> 这需要在大约 16 毫秒内重新渲染同一页面上的所有图表。您有实际的用例吗？

我的图表组件会有一些动画效果，慢慢的变的更高或更宽，这时就会显得有一些卡顿。

**Comment by xstxhjh** [comment]
> This required the re-render of all charts on a same page within ~16ms. Do you have an actual use case?

My chart component will have some animation effects, gradually becoming higher or wider, which will appear a bit jerky at that time.

**Comment by Justineo** [comment]
As ResizeObserver only triggers once in an animation frame, I think setting `:autoresize="{ throttle: 0 }"` will make the resizing smooth enough *if the time for resizing all charts all fits in one frame*.
