### ISSUE TITLE
安装报错 Invalid response body while trying to fetch https://registry.npmjs.org/resize-detector: Cannot read properties of null (reading 'pickAlgorithm')

### ISSUE THREAD

**Issue by jiahui336** [ecomfe/vue-echarts#784]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
Invalid response body while trying to fetch https://registry.npmjs.org/resize-detector: Cannot read properties of null (reading 'pickAlgorithm')
```

### 问题详情

Invalid response body while trying to fetch https://registry.npmjs.org/resize-detector: Cannot read properties of null (reading 'pickAlgorithm')

### 问题复现

https://codesandbox.io/p/sandbox/charming-night-2y6m6?file=%2Fsrc%2FApp.vue

**Comment by jiahui336** [comment]
去

**Comment by Justineo** [comment]
Not related to this project.
