### ISSUE TITLE
use autoresize;When the height changes decreases, the chart is abnormal

### ISSUE THREAD

**Issue by zhang761750981** [ecomfe/vue-echarts#794]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
6.7.3
```

### Details

``` html
<v-chart :style="{ height: 400 + 'px' }"  :option="option" autoresize></v-chart>
<v-chart :style="{ height: 300 + 'px' }"  :option="option" autoresize></v-chart>
```

When the height decreases, the chart does not render properly

### Reproduction

null

**Comment by Justineo** [comment]
Reproduction link is required.

**Comment by zhang761750981** [comment]
Caused by using another plugin
