### ISSUE TITLE
geoMap中的@click事件绑定无效

### ISSUE THREAD

**Issue by llifangyin** [ecomfe/vue-echarts#799]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
6.6.9
```

### Details

vue部分---
以下click事件不会打印， 正常的非gl组件，都是正常打印的
  ```<v-chart
    ref="vChartRef"
    :init-options="initOptions"
    :theme="themeColor"
    :manual-update="isPreview()"
    autoresize
    @highlight="(e)=>{console.log(e,'highlight')}" 
    @click='(e)=>{console.log(e,"click")}'
    @native:click="(e:any)=>{console.log(e,'native click')}"
    >
  </v-chart>
``` html
```
import VChart from 'vue-echarts'
import 'echarts-gl'

//option
 geo3D: {
    map: 'china',
    itemStyle: {
      // 图形的颜色。 默认从全局调色盘 option.color 获取颜色
      color: '#1781B5',
      opacity:'1',
      borderWidth:1,
      borderColor: '#93EBF8FF',
    },
    instancing:true,
    boxHeight:10,
    shading:'realistic',
    realisticMaterial:{
      detailTexture:null,
      roughness:0.5,
      metalness:0
    },
    lambertMaterial:{
      detailTexture : null,
    },
    colorMaterial:{
      detailTexture : null,
    },
    regionHeight : 8,
    viewControl: {
      projection:'perspective',//投影方式，默认为透视投影 perspective
      beta: 0, //x轴旋转
      alpha: 55, //Y轴旋转  
      distance:120,
      autoRotate:false,
      panSensitivity:'0',//不允许平移
      zoomSensitivity :'0.5',//不允许缩放
      rotateSensitivity:'0',//不允许旋转
      // panMouseButton: '', //平移操作使用的鼠标按键
      // rotateMouseButton: 'left', //旋转操作使用的鼠标按键
    },
    label: {
      show: false,
      distance :10,
      color: '#ffffff', //地图初始化区域字体颜色
      fontSize: 20
    },
    emphasis: {
      //当鼠标放上去  地区区域是否显示名称
      label: {
        show: true,
        textStyle: {
          color: '#fff',
        },
      },
      itemStyle: {
        // 图形的颜色。 默认从全局调色盘 option.color 获取颜色
        color: '#FFB800',
        opacity: '1',
      },
    },
    light: {
      //光照阴影
      main: {
        color: '#fff', //光照颜色
        intensity: 1, //光照强度
        shadowQuality: 'high', //阴影亮度
        shadow: true, //是否显示阴影
        alpha: 55,
        beta: 10,
      },
      // 全局的环境光设置。
      ambient: {
        color:'#fff',
        intensity: 0.2,
      },
    },
  },
```js
### Reproduction

none
```[tasklist]
### Tasks
```

**Comment by Justineo** [comment]
请按 issue 模板填写复现链接，否则将直接关闭。谢谢。
