### ISSUE TITLE
nuxt3 vue-echarts从6.7.3升级到7.0.1报错

### ISSUE THREAD

**Issue by vozhuo** [ecomfe/vue-echarts#801]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
vue 3.4.35
nuxt 3.12.4
echarts 5.5.1
vue-echarts 7.0.1
```

### 问题详情

nuxt3，vue-echarts从6.7.3升级到7.0.1报错Cannot read properties of undefined (reading 'head')，只出现在ssr: true时，ssr: false则无问题

### 问题复现

https://stackblitz.com/edit/nuxt-starter-fgxdpt

**Comment by kingyue737** [comment]
问题在于打包出来的`index.js`是通过下面的方式引入样式的。但是在服务端`document`是undefined。这个问题可能需要修复一下。 

```js
document.head.innerHTML += "<style>x-vue-echarts{display:block;width:100%;height:100%;min-width:0}\n</style>";
```

顺便一提，现在vue-echarts 和echarts 都支持ESM，不需要在nuxt config 中transpile他们：
```diff
export default defineNuxtConfig({
  ssr: true,
  compatibilityDate: '2024-04-03',
  devtools: { enabled: false },
- build: {
-   transpile: [/echarts/],
- },
});
```

再顺便打个广告，用nuxt又需要ssr支持的话可以考虑一下[Nuxt ECharts](https://nuxt.com/modules/echarts)哦。用法和vue-echarts几乎相同哦（因为我就是照搬的）。

**Comment by kingyue737** [comment]
### Workaround

如[文档所述](https://github.com/ecomfe/vue-echarts?tab=readme-ov-file#csp-style-src-or-style-src-elem)，你可以从`vue-echarts/csp`从导入`VChart`，这样就不会出错了。

https://stackblitz.com/edit/nuxt-starter-szf46q

**Comment by Justineo** [comment]
See @kingyue737's comments.

**Comment by Justineo** [comment]
@kingyue737 I’m thinking if we can find a way to merge Vue-ECharts and Nuxt ECharts to reduce duplication and future alignment, and also make it easier to use. WDYT?

**Comment by kingyue737** [comment]
@Justineo I would be very happy if Nuxt ECharts could be merged into Vue-ECharts. Will open a new discussion to track this.
