### ISSUE TITLE
类型错误

### ISSUE THREAD

**Issue by RanMaoting** [ecomfe/vue-echarts#803]
### 请确认

- [X] 我可以确认这个问题无法在 ECharts 项目本身中复现。

### 您是如何将 Vue-ECharts 引入项目的？

通过 ES 模块 import

### 版本信息

```sh
7.0.1
```

### 问题详情

在ts项目中导入路径似乎有问题
![image](https://github.com/user-attachments/assets/52d3e927-13ac-46a8-b5c7-fbb2a301d84f)

### 问题复现

无

**Comment by Justineo** [comment]
你贴的错误信息中已经告诉了你问题和解决方案了。

**Comment by Justineo** [comment]
请再仔细读一下错误提示……
