### ISSUE TITLE
从6.7.3升级到7.0.1后，页面原有样式将被限制加载

### ISSUE THREAD

**Issue by lt1067066026** [ecomfe/vue-echarts#805]
### Confirmation

- [X] I can confirm this problem is not reproducible with ECharts itself.

### How are you introducing Vue-ECharts into your project?

ES Module imports

### Versions

```sh
"vue": "^3.4.35",
"echarts": "^5.5.1",
"vue-echarts": "^7.0.1",
```

### Details

图表式页面的一个组件，原6.7.3下页面显示全部正常，升级到7.0.1之后页面样式失效。失效位置图表组件所在的父级元素的class没有被注入加载。
使用vue-echarts/csp代替vue-echarts导入，并引入vue-echarts/csp/style.css后页面正常显示了，但自定义的echarts-tooltip样式backdrop-filter属性表现失效。

### Reproduction

https://stackblitz.com/edit/vue-echarts-vue-3?file=src%2FApp.vue

**Comment by ovo-Tim** [comment]
Same issues

**Comment by daidaibg** [comment]
+1

**Comment by daidaibg** [comment]
去除style 中的scoped也可恢复样式，但是这并不是想要的方式，昨天想描述没想到好的方式，我本来以为升级vue 或者vite问题样式加载失败，一步一步排查没想到是vue-echart问题，希望尽快解决，7.0.0  7.0.1均有此问题。

**Comment by lt1067066026** [comment]
> 去除style 中的scoped也可恢复样式，但是这并不是想要的方式，昨天想描述没想到好的方式，我本来以为升级vue 或者vite问题样式加载失败，一步一步排查没想到是vue-echart问题，希望尽快解决，7.0.0 7.0.1均有此问题。

不去掉scoped也能解决，按照文档中https://github.com/ecomfe/vue-echarts?tab=readme-ov-file#csp-style-src-or-style-src-elem修改导入，这样子虽然页面样式正常了，但是图表样式backdrop-filter属性就不生效

**Comment by yqtu** [comment]
Yes, I also encountered the same problem

**Comment by lt1067066026** [comment]
> 去除style 中的scoped也可恢复样式，但是这并不是想要的方式，昨天想描述没想到好的方式，我本来以为升级vue 或者vite问题样式加载失败，一步一步排查没想到是vue-echart问题，希望尽快解决，7.0.0 7.0.1均有此问题。

如果图表提示样式没有使用backdrop-filter属性，可考虑这种方式解决

**Comment by daidaibg** [comment]
> 是的，我也遇到了同样的问题

说中文 🤯

**Comment by lt1067066026** [comment]
> > 去除style 中的scoped也可恢复样式，但是这并不是想要的方式，昨天想描述没想到好的方式，我本来以为升级vue 或者vite问题样式加载失败，一步一步排查没想到是vue-echart问题，希望尽快解决，7.0.0 7.0.1均有此问题。
> 
> 不去掉scoped也能解决，按照文档中[https://github.com/ecomfe/vue-echarts?tab=readme-ov-file#csp-style-src-or-style-src-elem修改导入，这样子虽然页面样式正常了，但是图表样式backdrop-filter属性就不生效](https://github.com/ecomfe/vue-echarts?tab=readme-ov-file#csp-style-src-or-style-src-elem%E4%BF%AE%E6%94%B9%E5%AF%BC%E5%85%A5%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%AD%90%E8%99%BD%E7%84%B6%E9%A1%B5%E9%9D%A2%E6%A0%B7%E5%BC%8F%E6%AD%A3%E5%B8%B8%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AF%E5%9B%BE%E8%A1%A8%E6%A0%B7%E5%BC%8Fbackdrop-filter%E5%B1%9E%E6%80%A7%E5%B0%B1%E4%B8%8D%E7%94%9F%E6%95%88)

如果图表提示样式没有使用backdrop-filter属性，可考虑这种方式解决

**Comment by daidaibg** [comment]
> > > 去除style 中的scoped也可恢复样式，但是这并不是想要的方式，昨天想描述没想到好的方式，我本来以为升级vue 或者vite问题样式加载失败，一步一步排查没想到是vue-echart问题，希望尽快解决，7.0.0 7.0.1均有此问题。
> > 
> > 
> > 不去掉scoped也能解决，按照文档中[https://github.com/ecomfe/vue-echarts?tab=readme-ov-file#csp-style-src-or-style-src-elem修改导入，这样子虽然页面样式正常了，但是图表样式backdrop-filter属性就不生效](https://github.com/ecomfe/vue-echarts?tab=readme-ov-file#csp-style-src-or-style-src-elem%E4%BF%AE%E6%94%B9%E5%AF%BC%E5%85%A5%EF%BC%8C%E8%BF%99%E6%A0%B7%E5%AD%90%E8%99%BD%E7%84%B6%E9%A1%B5%E9%9D%A2%E6%A0%B7%E5%BC%8F%E6%AD%A3%E5%B8%B8%E4%BA%86%EF%BC%8C%E4%BD%86%E6%98%AF%E5%9B%BE%E8%A1%A8%E6%A0%B7%E5%BC%8Fbackdrop-filter%E5%B1%9E%E6%80%A7%E5%B0%B1%E4%B8%8D%E7%94%9F%E6%95%88)
> 
> 如果图表提示样式没有使用backdrop-filter属性，可考虑这种方式解决

谢谢，我目前回退6.7.3版本，最新版等作者提出的解决方案。

**Comment by daidaibg** [comment]
> Yes, I also encountered the same problem

说中文🤯

**Comment by Justineo** [comment]
> https://stackblitz.com/edit/vue-echarts-vue-3?file=src%2FApp.vue

请给一个可以运行的最小重现，而不是原封不动地贴一个项目 demo 地址。

**Comment by Euraxluo** [comment]
+1

**Comment by Euraxluo** [comment]
https://github.com/ecomfe/vue-echarts/discussions/798

**Comment by daidaibg** [comment]
> > https://stackblitz.com/edit/vue-echarts-vue-3?file=src%2FApp.vue
> 
> 请给一个可以运行的最小重现，而不是原封不动地贴一个项目 demo 地址。

https://github.com/daidaibg/vue-echarts-style-bug  
切换vue-echarts 版本至7.0.0以下样式恢复

**Comment by spbgzh** [comment]
> > > https://stackblitz.com/edit/vue-echarts-vue-3?file=src%2FApp.vue
> > 
> > 
> > 请给一个可以运行的最小重现，而不是原封不动地贴一个项目 demo 地址。
> 
> https://github.com/daidaibg/vue-echarts-style-bug 切换vue-echarts 版本至7.0.0以下样式恢复

solved

**Comment by Justineo** [comment]
We switched to `rollup-plugin-import-css` in v7 but it’s [CSS injection](https://github.com/jleeson/rollup-plugin-import-css/blob/38c9316c28bb6a8442de360f027c4ccf3eebb154/src/index.js#L66) doesn’t seem to play well with Vite. I’ll fix this after I finished my vacation.
