### ISSUE TITLE
导出实例的类型

### ISSUE THREAD

**Issue by StardustOvO-000** [ecomfe/vue-echarts#815]
### 提前确认

- [X] 我可以确认这个新功能建议是提交给此 Vue 组件的，而不应该提交到 ECharts 项目本身。

### 新功能详情

`<v-chart ref="chartInstance"/>
const chartInstance = ref<?>()`
问号处ref函数的泛型该写什么？好像没有找到类型导出

**Comment by Justineo** [comment]
`InstanceType<typeof VChart>`
